# **The Begain**

In [1]:
!pip install wikipedia
!pip install -U langchain-community
!pip install -U langchain-core
!pip install faiss-cpu
!pip install langchain-google-genai
!pip install cohere
!pip install langchain
!pip install -U bitsandbytes langchain_huggingface
!pip install langchain_chroma
!pip install nltk
!pip install pypdf
!pip install unstructured
!pip install transformers sentencepiece
!pip install tiktoken

Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.1.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (2.8.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (4.15.0)
Building wheels for collected packages: wikipedia
  Building wheel for wikipedia (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11678 sha256=d1e2777f284638da890119710f23ec93315c2cd0d8535752bb11a52a2f9b6b04
  Stored in directory: /root/.cache/pip/wheels/63/47/7c/a9688349aa74d228ce0a9023229c6c0ac52ca2a40fe87679b8
Successfully built wikipedia
Installing collected packages: wikipedia
Successfully installed wikipedia-1.4.0
Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.2.6)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.45)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.2)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.0 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading langchain_text_splitters-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (1.33)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (0.13.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.1.4)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain-community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.41.4)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 43.0 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading langchain_classic-1.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 68.4 MB/s eta 0:00:00
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 7.7 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.0-py3-none-any.whl (34 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 6.1 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: requests, mypy-extensions, marshmallow, typing-inspect, dataclasses-json, langchain-text-splitters, langchain-classic, langchain-community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
Successfully installed dataclasses-json-0.6.7 langchain-classic-1.0.1 langchain-community-0.4.1 langchain-text-splitters-1.1.0 marshmallow-3.26.2 mypy-extensions-1.1.0 requests-2.32.5 typing-inspect-0.9.0
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (1.2.6)
Collecting langchain-core
  Downloading langchain_core-1.2.7-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (25.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.13.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2.5.0)
Downloading langchain_core-1.2.7-py3-none-any.whl (490 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 490.2/490.2 kB 33.2 MB/s eta 0:00:00
Installing collected packages: langchain-core
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.2.6
    Uninstalling langchain-core-1.2.6:
      Successfully uninstalled langchain-core-1.2.6
Successfully installed langchain-core-1.2.7
Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (25.0)
Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 84.6 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2
Collecting langchain-google-genai
  Downloading langchain_google_genai-4.2.0-py3-none-any.whl.metadata (2.7 kB)
Collecting filetype<2.0.0,>=1.2.0 (from langchain-google-genai)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting google-genai<2.0.0,>=1.56.0 (from langchain-google-genai)
  Downloading google_genai-1.59.0-py3-none-any.whl.metadata (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 4.9 MB/s eta 0:00:00
Requirement already satisfied: langchain-core<2.0.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (1.2.7)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (2.12.3)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.12.1)
Collecting google-auth<3.0.0,>=2.47.0 (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai)
  Downloading google_auth-2.47.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2.32.5)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (9.1.2)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.3.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (0.13.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.16.0)

Collecting cohere
  Downloading cohere-5.20.1-py3-none-any.whl.metadata (3.5 kB)
Collecting fastavro<2.0.0,>=1.9.4 (from cohere)
  Downloading fastavro-1.12.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: httpx>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from cohere) (0.28.1)
Requirement already satisfied: pydantic>=1.9.2 in /usr/local/lib/python3.12/dist-packages (from cohere) (2.12.3)
Requirement already satisfied: pydantic-core>=2.18.2 in /usr/local/lib/python3.12/dist-packages (from cohere) (2.41.4)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cohere) (2.32.5)
Requirement already satisfied: tokenizers<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from cohere) (0.22.2)
Collecting types-requests<3.0.0,>=2.0.0 (from cohere)
  Downloading types_requests-2.32.4.20260107-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from cohere) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->cohere) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->cohere) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->cohere) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->cohere) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.21.2->cohere) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->cohere) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->cohere) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->cohere) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->cohere) (2.5.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers<1,>=0.15->cohere) (0.36.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (3.20.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (1.2.0)
Downloading cohere-5.20.1-py3-none-any.whl (318 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.0/319.0 kB 20.2 MB/s eta 0:00:00
Downloading fastavro-1.12.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 12.0 MB/s eta 0:00:00
Downloading types_requests-2.32.4.20260107-py3-none-any.whl (20 kB)
Installing collected packages: types-requests, fastavro, cohere
Successfully installed cohere-5.20.1 fastavro-1.12.1 types-requests-2.32.4.20260107
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.3)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.7)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.13.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.5.0)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting langchain_huggingface
  Downloading langchain_huggingface-1.2.0-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (25.0)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (0.36.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (1.2.7)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (0.22.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (3.20.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (1.2.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (0.6.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (2.12.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (9.1.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (0.13.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0.0,>=0.33.4->langchain_huggingface) (2026.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain_huggingface) (0.16.0)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 13.6 MB/s eta 0:00:00
Downloading langchain_huggingface-1.2.0-py3-none-any.whl (30 kB)
Installing collected packages: bitsandbytes, langchain_huggingface
Successfully installed bitsandbytes-0.49.1 langchain_huggingface-1.2.0
Collecting langchain_chroma
  Downloading langchain_chroma-1.1.0-py3-none-any.whl.metadata (1.9 kB)
Collecting chromadb<2.0.0,>=1.3.5 (from langchain_chroma)
  Downloading chromadb-1.4.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (1.2.7)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (2.0.2)
Collecting build>=1.0.3 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading build-1.4.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.12.3)
Collecting pybase64>=1.4.1 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.40.0)
Collecting posthog<6.0.0,>=2.4.0 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading posthog-5.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading onnxruntime-1.23.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.1 kB)

In [2]:
!pip install -U langchain
!pip install -U langchain_google_genai

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.3)
Collecting langchain
  Downloading langchain-1.2.4-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.7)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.13.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.5.0)
Downloading langchain-1.2.4-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.9/107.9 kB 11.1 MB/s eta 0:00:00
Installing collected packages: langchain
  Attempting uninstall: langchain
    Found existing installation: langchain 1.2.3
    Uninstalling langchain-1.2.3:
      Successfully uninstalled langchain-1.2.3
Successfully installed langchain-1.2.4
Requirement already satisfied: langchain_google_genai in /usr/local/lib/python3.12/dist-packages (4.2.0)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (1.2.0)
Requirement already satisfied: google-genai<2.0.0,>=1.56.0 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (1.59.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (1.2.7)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (2.12.3)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (4.12.1)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (2.32.5)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (9.1.2)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (1.3.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (0.13.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (0.4.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (0.25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (2.5.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (0.6.1)

In [106]:
from dotenv import dotenv_values
env_values = dotenv_values("./app.env")

In [107]:
gemini_api_key = env_values['GEMINI_API_KEY']

In [27]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage , AIMessage , SystemMessage

chat = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash-lite",
    temperature = 0.7 ,
    google_api_key = gemini_api_key
)

In [108]:
print(gemini_api_key)

AIzaSyDW6HqLxg0Z6YXjTeN02ZI5ov0YnE_Q8Q8

# **2. Hugging Face Open Sourced Models**

In [29]:
from transformers import LlamaTokenizer ,  LlamaForCausalLM ,  GenerationConfig, pipeline, BitsAndBytesConfig
import torch
from langchain_huggingface.llms import HuggingFacePipeline

In [30]:
model_id = "h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-3b"
tokenizer = LlamaTokenizer.from_pretrained(model_id)
base_model = LlamaForCausalLM.from_pretrained(model_id,
                                              load_in_8bit=True,
                                              device_map='auto')

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.

In [31]:
hf_pipeline = pipeline('text-generation',
                       model=base_model,
                       tokenizer=tokenizer)

Device set to use cuda:0

In [32]:
llm = HuggingFacePipeline(pipeline=hf_pipeline)

In [33]:
prompt = """ Below is an intruction that describes a task. write a response that appropriately completes the request.
### Instruction:
[INSTRUCTION]
tell me 2 ways to lose weight

Answer:
""".strip()

In [34]:
print(llm.invoke(prompt , max_new_tokens=265))

Below is an intruction that describes a task. write a response that appropriately completes the request.
### Instruction:
[INSTRUCTION]
tell me 2 ways to lose weight

Answer:
1. Eat less
2. Exercise more

# **3. API Based Language Models**

In [35]:
!pip install -U langchain
!pip install -U langchain_google_genai

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.4)
Collecting langchain
  Downloading langchain-1.2.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.7 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.7)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (0.13.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.7->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (2.5.0)
Downloading langchain-1.2.5-py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.7/108.7 kB 8.1 MB/s eta 0:00:00
Installing collected packages: langchain
  Attempting uninstall: langchain
    Found existing installation: langchain 1.2.4
    Uninstalling langchain-1.2.4:
      Successfully uninstalled langchain-1.2.4
Successfully installed langchain-1.2.5
Requirement already satisfied: langchain_google_genai in /usr/local/lib/python3.12/dist-packages (4.2.0)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (1.2.0)
Requirement already satisfied: google-genai<2.0.0,>=1.56.0 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (1.59.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (1.2.7)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (2.12.3)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (4.12.1)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (2.32.5)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (9.1.2)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain_google_genai) (1.3.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (0.13.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (0.4.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain_google_genai) (0.25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (2.5.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain_google_genai) (0.6.1)

In [36]:
from dotenv import dotenv_values
env_values = dotenv_values("./app.env")

In [37]:
gemini_api_key = env_values['GEMINI_API_KEY']

In [38]:
from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-lite",
      google_api_key=gemini_api_key,
    temperature=0.7
)

In [39]:
prompt1 = """
tell me 2 ways to lose weight
""".strip()

In [40]:
print(llm.invoke(prompt1))

content="Here are two effective ways to lose weight, focusing on sustainable and healthy approaches:\n\n1.  **Create a Sustainable Calorie Deficit Through Diet:**\n    *   **What it means:** This is the fundamental principle of weight loss. You need to consume fewer calories than your body burns.\n    *   **How to do it:**\n        *   **Focus on Nutrient-Dense Foods:** Prioritize whole, unprocessed foods that are rich in vitamins, minerals, and fiber. This includes fruits, vegetables, lean proteins (chicken, fish, beans, tofu), whole grains (oats, brown rice, quinoa), and healthy fats (avocado, nuts, seeds, olive oil). These foods are more filling and provide essential nutrients, making it easier to stick to a calorie deficit without feeling deprived.\n        *   **Control Portion Sizes:** Be mindful of how much you're eating. Use smaller plates, measure out servings, and pay attention to your body's hunger and fullness cues.\n        *   **Reduce Intake of Processed Foods, Sugary Drinks, and Excessive Fats:** These items are often high in calories and low in nutrients, contributing to weight gain without providing satiety. Cutting back on sodas, sweets, fried foods, and heavily processed snacks can significantly reduce your calorie intake.\n        *   **Hydration is Key:** Drinking plenty of water throughout the day can help you feel fuller, aid digestion, and boost your metabolism.\n    *   **Why it works:** When your body consistently receives fewer calories than it needs to maintain its current weight, it will tap into its stored fat for energy, leading to weight loss. The key is to make this deficit manageable and sustainable so you can maintain it long-term.\n\n2.  **Increase Your Physical Activity and Build Muscle:**\n    *   **What it means:** This involves incorporating regular exercise into your routine to burn more calories and build lean muscle mass.\n    *   **How to do it:**\n        *   **Combine Cardiovascular Exercise and Strength Training:**\n            *   **Cardio (Aerobic Exercise):** Activities like brisk walking, running, cycling, swimming, or dancing help burn a significant number of calories during the activity itself. Aim for at least 150 minutes of moderate-intensity or 75 minutes of vigorous-intensity cardio per week.\n            *   **Strength Training (Resistance Training):** Lifting weights, using resistance bands, or doing bodyweight exercises (like squats, push-ups, lunges) builds lean muscle. Muscle tissue is more metabolically active than fat tissue, meaning it burns more calories even at rest. This can help increase your overall daily calorie expenditure.\n        *   **Increase Non-Exercise Activity Thermogenesis (NEAT):** This refers to the calories you burn from everyday activities that aren't structured exercise. Think taking the stairs, parking further away, walking during phone calls, or doing household chores. Even small increases in NEAT can add up.\n        *   **Find Activities You Enjoy:** Consistency is crucial for weight loss. Choose forms of exercise that you genuinely like, as you're more likely to stick with them long-term.\n    *   **Why it works:** Exercise directly contributes to calorie expenditure, creating a larger calorie deficit. Furthermore, building muscle increases your resting metabolic rate, meaning your body burns more calories throughout the day, even when you're not exercising. This combination makes weight loss more efficient and helps with body composition changes.\n\n**Important Considerations:**\n\n*   **Consult a Healthcare Professional:** Before starting any new diet or exercise program, it's always recommended to talk to your doctor or a registered dietitian, especially if you have any underlying health conditions.\n*   **Consistency is Key:** Weight loss is a journey, not a race. Focus on making gradual, sustainable changes to your lifestyle rather than seeking quick fixes.\n*   **Listen to Your Body:** Pay attention to how your body feels and adjust your approach as needed.\n*   **Focus on Overall Health:** While weight loss is a goal, prioritize improving your overall health and well-being. This includes getting enough sleep, managing stress, and fostering a positive relationship with food and your body." additional_kwargs={} response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'} id='lc_run--019bc796-8e24-74e1-98be-989ffb34b71c-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 9, 'output_tokens': 868, 'total_tokens': 877, 'input_token_details': {'cache_read': 0}}

In [41]:
response = llm.invoke(prompt)
print(response.text.strip())

Here are two common and effective ways to lose weight:

1.  **Create a Caloric Deficit through Diet:** This is the most fundamental principle of weight loss. You need to consume fewer calories than your body burns. This can be achieved by:
    *   **Reducing portion sizes:** Eating smaller amounts of food at each meal.
    *   **Choosing nutrient-dense, lower-calorie foods:** Focusing on fruits, vegetables, lean proteins, and whole grains, while limiting processed foods, sugary drinks, and excessive unhealthy fats.
    *   **Mindful eating:** Paying attention to hunger and fullness cues, and eating slowly.

2.  **Increase Physical Activity:** Burning more calories through exercise complements dietary changes and contributes to weight loss. This can involve:
    *   **Cardiovascular exercise:** Activities like brisk walking, running, swimming, cycling, or dancing that elevate your heart rate and burn calories. Aim for at least 150 minutes of moderate-intensity or 75 minutes of vigorous-intensity aerobic activity per week.
    *   **Strength training:** Building muscle mass through weightlifting or bodyweight exercises. Muscle burns more calories at rest than fat, so increasing muscle can boost your metabolism over time.

In [42]:
#clculate tokens
print(response.usage_metadata)

{'input_tokens': 41, 'output_tokens': 255, 'total_tokens': 296, 'input_token_details': {'cache_read': 0}}

In [43]:
from langchain_core.prompts import PromptTemplate
user_subject = "Linear algebra"
user_language = "arabic"
string_prompt = PromptTemplate(
    template = "explain {subject} like i am 5 , write the answer in {language}",
    input_variables = ['subject' , 'language']
)
prompt = string_prompt.format(subject = user_subject , language = user_language)
response = llm.invoke(prompt)
print(response.text.strip())

تخيل أن لديك صندوقًا كبيرًا من المكعبات الملونة.

**الجبر الخطي** يشبه اللعب بهذه المكعبات بطرق منظمة.

*   **المتجهات (Vectors):** تخيل أنك تأخذ بعض المكعبات وتضعها في صف واحد. هذا الصف من المكعبات هو "متجه". يمكن أن يكون لديك صف من المكعبات الحمراء، أو صف من المكعبات الزرقاء، أو صف مختلط.

    *   مثال: لو عندك 2 مكعب أحمر و 3 مكعبات زرقاء، ممكن تمثلهم في صف: [أحمر، أحمر، أزرق، أزرق، أزرق]

*   **المصفوفات (Matrices):** الآن تخيل أن لديك عدة صفوف من المكعبات، ومرتبة في شكل مربع أو مستطيل. هذه "المصفوفة". كأنك عملت طبقات من الصفوف.

    *   مثال: ممكن يكون عندك صف فوق فيه 2 مكعب أحمر و 1 مكعب أزرق، وصف تحت فيه 3 مكعبات حمراء و 2 مكعبات زرقاء. هذه مصفوفة!

*   **العمليات (Operations):**
    *   **الجمع (Addition):** لو عندك صندوقين من المكعبات، ممكن تجمع كل المكعبات من الصندوق الأول مع المكعبات من الصندوق الثاني بنفس اللون. هذا يشبه جمع المتجهات أو المصفوفات.
    *   **الضرب (Multiplication):** هذه شوية أصعب. تخيل أنك تريد أن تجعل كل مكعب أحمر يتحول إلى 2 مكعب أحمر. أو أنك تريد أن تغير ترتيب المكعبات. الضرب في الجبر الخطي يشبه هذه التغييرات.

**لماذا نستخدم الجبر الخطي؟**

لأنه يساعدنا على فهم كيف تتفاعل الأشياء مع بعضها البعض. مثل:

*   **كيف تتحرك الأشياء:** لو كنت تحرك سيارة لعبة، فالجبر الخطي يساعدنا نفهم كيف تتغير مكانها.
*   **كيف تتغير الأشياء:** لو كنت تغير لون المكعبات، فالجبر الخطي يساعدنا نفهم كيف تتغير الألوان.
*   **حل الألغاز:** لو كان عندك لغز فيه مكعبات كثيرة، فالجبر الخطي يساعدنا نلاقي الحلول.

باختصار، الجبر الخطي هو طريقة منظمة للتعامل مع مجموعات من الأرقام (أو المكعبات!) وفهم كيف تتغير وتتفاعل مع بعضها البعض. إنه مثل لغة سحرية تساعدنا نفهم العالم من حولنا بشكل أفضل.

In [44]:
print(prompt)

explain Linear algebra like i am 5 , write the answer in arabic

In [45]:
string_prompt

PromptTemplate(input_variables=['language', 'subject'], input_types={}, partial_variables={}, template='explain {subject} like i am 5 , write the answer in {language}')

# **5. LangChain Chat Schema**

# **5.1 Base Conversation**

In [46]:
import google.generativeai as genai
genai.configure(api_key = gemini_api_key)

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [47]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage , AIMessage , SystemMessage

chat = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash-lite",
    temperature = 0.7 ,
    google_api_key = gemini_api_key
)

In [48]:
base_conversation = [
    SystemMessage(content="You are a chief , you , want to ask me some things to find out my favorite dish"),
    AIMessage(content="Where are you from?"),
    HumanMessage(content="Egypt"),
    AIMessage (content="Do you like spicy food?"),
    HumanMessage (content="Not too much"),
    AIMessage (content="Do you suffer from diabetes?"),
    HumanMessage (content="yes"),

]
response = chat.invoke(base_conversation)
print(response.content.strip())

Alright, an Egyptian dish that isn't too spicy and is suitable for someone with diabetes. That narrows it down a bit!

Now, tell me:

*   **Do you prefer something hearty and filling, or something lighter?** Think along the lines of a main course with grains and vegetables, or perhaps something more vegetable-focused.

In [49]:
base_conversation = [
    SystemMessage(content="You are a chief, you want to ask me some things to find out my favorite dish"),
    HumanMessage(content="Hello Chief!") # Add an initial HumanMessage)
]
response = None
for i in range(3):
  response = chat.invoke(base_conversation)
  print("AI" , response.content.strip())
  base_conversation.append(response)
  user_response = HumanMessage(content= input("Tou: "))
  base_conversation.append(user_response)

AI Ah, welcome, welcome! Come in, have a seat. It's good to see you.

I've been curious, you know. We've shared meals, talked about all sorts of things, but I've never quite pinned down what truly makes your taste buds sing. So, let's get to the bottom of it.

Tell me, when you're thinking about a truly satisfying meal, what's the first thing that comes to mind? Is it a specific cuisine, a certain type of ingredient, or perhaps a feeling that the dish evokes? Don't hold back, I want the honest truth!
Tou: shawarma
AI Shawarma, you say? Ah, an excellent choice! A classic for a reason.

Now, to really understand what makes shawarma *your* favorite, I have a few more questions for you. Think about it like this: what makes a shawarma truly *sing*?

First off, **what kind of meat is your go-to?** Are you a traditionalist with lamb or beef, or do you lean towards the chicken? Or perhaps something else entirely?

And then, **what about the way it's prepared?** Is there a specific marinade or spice blend that you find irresistible? Is it the char from the spit-roast, or something else that makes it special?

Don't be shy, tell me all about it!
Tou: hot
AI Hot! Interesting! So, you like your shawarma with a bit of a kick, do you? That tells me something!

Now, when you say "hot," are we talking about a gentle warmth that enhances the flavors, or are you craving that full-on, sweat-on-your-brow kind of heat?

And related to that heat, **what kind of "hot" element are we talking about?** Is it a spicy sauce like a fiery chili sauce or harissa? Or perhaps it's in the marinade itself, with peppers or other fiery spices?

I'm trying to paint a picture here, you see. Help me understand the *kind* of heat that makes your shawarma truly perfect!
Tou: meat

In [50]:
base_conversation

[SystemMessage(content='You are a chief, you want to ask me some things to find out my favorite dish', additional_kwargs={}, response_metadata={}),
 HumanMessage(content='Hello Chief!', additional_kwargs={}, response_metadata={}),
 AIMessage(content="Ah, welcome, welcome! Come in, have a seat. It's good to see you.\n\nI've been curious, you know. We've shared meals, talked about all sorts of things, but I've never quite pinned down what truly makes your taste buds sing. So, let's get to the bottom of it.\n\nTell me, when you're thinking about a truly satisfying meal, what's the first thing that comes to mind? Is it a specific cuisine, a certain type of ingredient, or perhaps a feeling that the dish evokes? Don't hold back, I want the honest truth!", additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc797-13d9-7932-a304-5df162b81465-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 22, 'output_tokens': 131, 'total_tokens': 153, 'input_token_details': {'cache_read': 0}}),
 HumanMessage(content='shawarma', additional_kwargs={}, response_metadata={}),
 AIMessage(content="Shawarma, you say? Ah, an excellent choice! A classic for a reason.\n\nNow, to really understand what makes shawarma *your* favorite, I have a few more questions for you. Think about it like this: what makes a shawarma truly *sing*?\n\nFirst off, **what kind of meat is your go-to?** Are you a traditionalist with lamb or beef, or do you lean towards the chicken? Or perhaps something else entirely?\n\nAnd then, **what about the way it's prepared?** Is there a specific marinade or spice blend that you find irresistible? Is it the char from the spit-roast, or something else that makes it special?\n\nDon't be shy, tell me all about it!", additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc797-5ca6-7eb2-ba14-c794c7c93174-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 157, 'output_tokens': 158, 'total_tokens': 315, 'input_token_details': {'cache_read': 0}}),
 HumanMessage(content='hot', additional_kwargs={}, response_metadata={}),
 AIMessage(content='Hot! Interesting! So, you like your shawarma with a bit of a kick, do you? That tells me something!\n\nNow, when you say "hot," are we talking about a gentle warmth that enhances the flavors, or are you craving that full-on, sweat-on-your-brow kind of heat?\n\nAnd related to that heat, **what kind of "hot" element are we talking about?** Is it a spicy sauce like a fiery chili sauce or harissa? Or perhaps it\'s in the marinade itself, with peppers or other fiery spices?\n\nI\'m trying to paint a picture here, you see. Help me understand the *kind* of heat that makes your shawarma truly perfect!', additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc798-26be-78e2-82f9-42c8b65cc07c-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 318, 'output_tokens': 150, 'total_tokens': 468, 'input_token_details': {'cache_read': 0}}),
 HumanMessage(content='meat', additional_kwargs={}, response_metadata={})]

In [51]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage , SystemMessage , AIMessage
from langchain import chat_models

chat =ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite",
                             temperature = 0.7 ,
                             google_api_key = gemini_api_key)

In [52]:
system_context = SystemMessage(content="You are a cyber security engineer, your company coworkers are not profissional and they may ask you for any security problems they may face")
user_message = HumanMessage(content='i just clicked on a malicous link')
response = chat.invoke([system_context, user_message])
print(response.content)

Okay, take a deep breath. It's a common mistake, and the most important thing is that you're telling us about it immediately. This gives us the best chance to mitigate any potential damage.

Here's what we need to do, and I'll guide you through it. Please answer these questions as accurately and quickly as possible:

**1. What kind of device are you on?**
*   Is it your work laptop, your personal laptop, your work phone, your personal phone, or something else?

**2. What operating system is the device running?**
*   Windows (e.g., Windows 10, Windows 11)?
*   macOS?
*   iOS (iPhone/iPad)?
*   Android?

**3. What browser were you using when you clicked the link?**
*   Chrome, Firefox, Edge, Safari, etc.?

**4. What was the link about? Do you remember any of the text or the website address (URL)?**
*   Even a partial URL or a description of the content is helpful (e.g., "it looked like an email about a password reset," "it was a link to a news article," "it said I won a prize").

**5. Did you download anything after clicking the link?**
*   If so, what was the file name and type (e.g., `invoice.zip`, `update.exe`, `document.pdf`)?

**6. Did you enter any information after clicking the link?**
*   Specifically, did you enter any usernames, passwords, credit card details, or personal information on a website that opened? If so, what kind of website was it?

**7. Is your device currently connected to the company network (Wi-Fi or Ethernet)?**
*   If it's a mobile device, are you connected to company Wi-Fi or using cellular data?

**Once you answer these, here's what we'll likely do:**

*   **Isolate the device:** Depending on the answers, we might need to immediately disconnect your device from the network to prevent any spread.
*   **Scan for malware:** We'll run security scans to detect and remove any malicious software.
*   **Password resets:** If you entered any credentials, we'll likely force a reset of those accounts.
*   **Monitor for suspicious activity:** We'll keep an eye on your accounts and network traffic.

**Don't panic.** The sooner we act, the better. Just tell me what you can.

# **5.2 Basic FewShots**

In [53]:
demo_message = """
Country Name: Egypt | Capital Name: Cairo
Country Name: Saudi Arabia | Capital Name: Riyadh
Country Name: Singapore | Capital Name: Singapore
Country Name: Armenia |
""".strip()

In [54]:
from langchain_google_genai import ChatGoogleGenerativeAI
chat = ChatGoogleGenerativeAI(
    model = 'gemini-2.5-flash-lite',
    temperature = 0.7,
    google_api_key = gemini_api_key
)

In [55]:
response = chat.invoke([HumanMessage(content=demo_message)])
print(response.content)

Capital Name: Yerevan

# **5.3 Fewshot using LangChain Prompt Template**

In [56]:
from langchain_core.prompts import FewShotPromptTemplate
from langchain_core.prompts import PromptTemplate

In [57]:
demo_template = PromptTemplate(
    template = "Country Name: {country} | Capital Name:{capital}",
    input_variables = ['country','capital']
)

examples = [
    {'country': 'Egypt', 'capital': 'Cairo'},
    {'country': 'Saudi Arabia', 'capital': 'Riyadh'},
    {'country': 'Singapore', 'capital': 'Singapore'}
]

prompt = FewShotPromptTemplate(
    example_prompt = demo_template,
    examples = examples,
    suffix = "Country Name: {country} |",
    input_variables =['country']
)

In [58]:
user_country = 'Austeria'
message = prompt.format(country = user_country)
print(message)

Country Name: Egypt | Capital Name:Cairo

Country Name: Saudi Arabia | Capital Name:Riyadh

Country Name: Singapore | Capital Name:Singapore

Country Name: Austeria |

In [59]:
print(chat.invoke([HumanMessage(content=message)]))

content='Capital Name:Vienna' additional_kwargs={} response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'} id='lc_run--019bc799-2bf1-75f3-8265-850f9a00ae5e-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 40, 'output_tokens': 4, 'total_tokens': 44, 'input_token_details': {'cache_read': 0}}

In [60]:
message = "What is the ingredients to cook a pizza?"
response =chat.invoke(message)
print(response.content)

Here's a breakdown of the essential ingredients to cook a pizza, covering the dough, sauce, cheese, and toppings. You can adjust these based on your preferences!

## The Core Ingredients for Pizza:

### 1. For the Dough:

This is the foundation of your pizza. You have a few options:

*   **Homemade Dough:**
    *   **Flour:** All-purpose flour is the most common and works well. "00" flour is a finely milled Italian flour that's ideal for Neapolitan-style pizzas, giving a lighter and chewier crust. Bread flour has a higher protein content, leading to a chewier crust.
    *   **Yeast:** Active dry yeast or instant yeast is needed to make the dough rise.
    *   **Water:** Lukewarm water is best for activating the yeast.
    *   **Salt:** Enhances flavor and controls yeast activity.
    *   **Olive Oil (Optional but Recommended):** Adds flavor, tenderness, and helps with browning.
    *   **Sugar (Optional):** A pinch can help feed the yeast and aid in browning.

*   **Pre-made Dough:** You can buy fresh or frozen pizza dough from most grocery stores. This is a great time-saver!

### 2. For the Sauce:

This adds moisture and a burst of flavor.

*   **Tomato-Based Sauce:**
    *   **Crushed Tomatoes or Tomato Puree:** The base of most pizza sauces. San Marzano tomatoes are highly prized for their sweet, less acidic flavor.
    *   **Garlic:** Freshly minced or garlic powder for aromatic flavor.
    *   **Onion (Optional):** Finely minced or onion powder.
    *   **Herbs:** Dried oregano, basil, and sometimes a pinch of thyme or rosemary are classic. Fresh basil can be added at the end of cooking or as a garnish.
    *   **Olive Oil:** For sautéing aromatics and adding richness.
    *   **Salt and Black Pepper:** To taste.
    *   **Sugar (Optional):** To balance the acidity of the tomatoes.
    *   **Red Pepper Flakes (Optional):** For a touch of heat.

*   **Other Sauce Options:**
    *   **Pesto:** A vibrant green sauce made from basil, pine nuts, garlic, Parmesan cheese, and olive oil.
    *   **White Sauce (Alfredo or Bechamel):** A creamy sauce made with butter, flour, milk, and cheese.
    *   **BBQ Sauce:** For a smoky, sweet, and tangy pizza.

### 3. For the Cheese:

This is where the gooey, melty goodness comes from!

*   **Mozzarella Cheese:** The undisputed king of pizza cheese.
    *   **Low-Moisture Mozzarella:** This is what you'll find in shredded form in most grocery stores. It melts well and doesn't make the pizza too watery.
    *   **Fresh Mozzarella:** Comes in balls and is very soft and creamy. It has a higher moisture content, so it's best to drain it well and use it in moderation or bake it on top of other cheeses.
*   **Other Cheeses (for added flavor and complexity):**
    *   **Parmesan Cheese:** Adds a salty, nutty flavor.
    *   **Provolone Cheese:** Melts well and has a slightly sharper taste than mozzarella.
    *   **Cheddar Cheese:** Can be used in blends for a different flavor profile.
    *   **Gouda Cheese:** Offers a smoky, caramel-like sweetness.
    *   **Ricotta Cheese:** Often dolloped on top for creamy pockets.

### 4. For the Toppings:

This is where you can get creative! The possibilities are endless.

*   **Vegetables:**
    *   **Onions:** Red, white, yellow, or green.
    *   **Peppers:** Bell peppers (green, red, yellow, orange), jalapeños, banana peppers.
    *   **Mushrooms:** White button, cremini, shiitake.
    *   **Olives:** Black, green, Kalamata.
    *   **Tomatoes:** Sliced fresh tomatoes, cherry tomatoes.
    *   **Spinach:** Fresh or wilted.
    *   **Artichoke Hearts:** Canned or jarred.
    *   **Broccoli:** Small florets.
    *   **Corn:** Fresh or canned.
    *   **Pineapple:** For those who love a Hawaiian!

*   **Meats:**
    *   **Pepperoni:** A classic for a reason.
    *   **Sausage:** Italian sausage, crumbled or sliced.
    *   **Bacon:** Cooked and crumbled.
    *   **Ham:** Diced or sliced.
    *   **Chicken:** Cooked and shredded or diced.
    *   **Prosciutto:** Thinly sliced cured ham, often added after baking.
    *   **Anchovies:** For a salty, umami kick.

*   **Other Toppings:**
    *   **Fresh Herbs:** Basil, parsley, cilantro.
    *   **Garlic:** Sliced or roasted.
    *   **Chiles:** Fresh or pickled.
    *   **Eggs:** Cracked directly onto the pizza before baking.

**In summary, for a basic, classic pizza, you'll need:**

*   **Pizza Dough**
*   **Tomato Sauce**
*   **Mozzarella Cheese**
*   **Your favorite toppings!**

Enjoy making your delicious pizza!

# **6. Custom Output Parser**

# **6.1 CommaSeparatedListOutputParser**

In [61]:
from langchain_core.output_parsers import CommaSeparatedListOutputParser
from langchain_core.prompts import PromptTemplate

In [62]:
output_parser = CommaSeparatedListOutputParser()
format_instructions = output_parser.get_format_instructions()

In [63]:
prompt = PromptTemplate(
    template="List three popular {type} plates,\n{format_instructions}",
    input_variables=["type"],
    partial_variables={"format_instructions": format_instructions}
)

In [64]:
demo_message = prompt.format(type='arabian')

response = chat.invoke(demo_message).text.strip()
output = output_parser.parse(response)
print(output)

['Hummus', 'Shawarma', 'Falafel']

In [65]:
type(output)

list

# **6.5 Your custom (format_instructions)**

In [66]:
from langchain_core.output_parsers import CommaSeparatedListOutputParser
from langchain_core.prompts import PromptTemplate

In [67]:
output_parser = CommaSeparatedListOutputParser()
format_instructions = output_parser.get_format_instructions()

In [68]:
format_instructions = "Replay with a datatime format DD/MM/YYYY like '24/05/2002'."
prompt = PromptTemplate(
    template = 'When was {person} born? .\n{format_instructions}',
    input_variables = ['person','format_instructions']
)

message = prompt.format(person = 'Abdel Fatah EL Sisi' , format_instructions= format_instructions)
print(chat.invoke("The President Abdel Fatah EL Sisi was born in " + message).text.strip())

19/11/1954

# Example

In [69]:
from langchain_core.output_parsers import CommaSeparatedListOutputParser
from langchain_core.prompts import PromptTemplate

In [70]:
output_parser_1 = CommaSeparatedListOutputParser()
format_instructions_1 = output_parser.get_format_instructions()

In [71]:
format_instructions_1 = "Replay with a datatime format {person} was born in DD/MM/YYYY like 'mahdi was born in 24/05/2002'."
prompt = PromptTemplate(
    template = "when was {person} born? .\n{format_instructions}",
    input_variables = ['person', 'format_instructions']
)
message_1 = prompt.format(person = "El Sheakh El Shaarawy" , format_instructions  = format_instructions)
print(chat.invoke(message_1).text.strip())

27/10/1911

# **6.6 PyDantic**

In [72]:
from pydantic import BaseModel , Field
from typing import List
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate

In [73]:
class Plate(BaseModel):
  plate_name: str = Field(description="name of the plate")
  ingredients: List[str] = Field(description="list of names of the ingredients")

In [74]:
  parser = PydanticOutputParser(pydantic_object=Plate)

In [75]:
format_instructions = parser.get_format_instructions()

prompt = PromptTemplate(
    template = "Answer the query.\n{plate_name}\n{format_instructions}",
    input_variables =['plate_name'],
    partial_variables={"format_instructions":format_instructions}
)

In [76]:
plate_name ="shawerma"
message = prompt.format(plate_name=plate_name)
response = chat.invoke(message).text.strip()
output = parser.parse(response)

In [77]:
print(format_instructions)

The output should be formatted as a JSON instance that conforms to the JSON schema below.

As an example, for the schema {"properties": {"foo": {"title": "Foo", "description": "a list of strings", "type": "array", "items": {"type": "string"}}}, "required": ["foo"]}
the object {"foo": ["bar", "baz"]} is a well-formatted instance of the schema. The object {"properties": {"foo": ["bar", "baz"]}} is not well-formatted.

Here is the output schema:
```
{"properties": {"plate_name": {"description": "name of the plate", "title": "Plate Name", "type": "string"}, "ingredients": {"description": "list of names of the ingredients", "items": {"type": "string"}, "title": "Ingredients", "type": "array"}}, "required": ["plate_name", "ingredients"]}
```

In [78]:
print(message)

Answer the query.
shawerma
The output should be formatted as a JSON instance that conforms to the JSON schema below.

As an example, for the schema {"properties": {"foo": {"title": "Foo", "description": "a list of strings", "type": "array", "items": {"type": "string"}}}, "required": ["foo"]}
the object {"foo": ["bar", "baz"]} is a well-formatted instance of the schema. The object {"properties": {"foo": ["bar", "baz"]}} is not well-formatted.

Here is the output schema:
```
{"properties": {"plate_name": {"description": "name of the plate", "title": "Plate Name", "type": "string"}, "ingredients": {"description": "list of names of the ingredients", "items": {"type": "string"}, "title": "Ingredients", "type": "array"}}, "required": ["plate_name", "ingredients"]}
```

In [79]:
print(response)

```json
{
  "plate_name": "Shawerma",
  "ingredients": [
    "Marinated meat (chicken, lamb, or beef)",
    "Pita bread or flatbread",
    "Tahini sauce",
    "Garlic sauce (toum)",
    "Tomatoes",
    "Cucumbers",
    "Onions",
    "Pickles"
  ]
}
```

In [80]:
print(output)

plate_name='Shawerma' ingredients=['Marinated meat (chicken, lamb, or beef)', 'Pita bread or flatbread', 'Tahini sauce', 'Garlic sauce (toum)', 'Tomatoes', 'Cucumbers', 'Onions', 'Pickles']

In [81]:
output.plate_name

'Shawerma'

In [82]:
output.ingredients

['Marinated meat (chicken, lamb, or beef)',
 'Pita bread or flatbread',
 'Tahini sauce',
 'Garlic sauce (toum)',
 'Tomatoes',
 'Cucumbers',
 'Onions',
 'Pickles']

#7. Conversation Buffer (Memory)

# **7.1 Basic Memory (Conversation Buffer Memory)**

In [83]:
message_1 = "list 3 places to visit in paris"
response = chat.invoke(message_1).text.strip()
print(response)

Here are 3 iconic and diverse places to visit in Paris, offering different experiences:

1.  **The Eiffel Tower:** This is arguably the most recognizable landmark in Paris and a must-see for any first-time visitor. You can admire it from various vantage points, have a picnic on the Champ de Mars, or ascend to its summit for breathtaking panoramic views of the city. It's particularly magical when it sparkles at night.

2.  **The Louvre Museum:** Home to thousands of works of art, including the Mona Lisa and the Venus de Milo, the Louvre is the world's largest art museum. Even if you're not a huge art buff, the sheer scale and grandeur of the building itself, a former royal palace, are impressive. You could easily spend a full day (or more!) exploring its vast collections.

3.  **Montmartre & Sacré-Cœur Basilica:** This charming hilltop neighborhood offers a different vibe from the grand boulevards. Wander through its cobblestone streets, discover artists at Place du Tertre, and soak in the bohemian atmosphere. The stunning white Sacré-Cœur Basilica at the summit offers incredible views over Paris and is a beautiful place to visit for its architecture and spiritual ambiance.

In [84]:
message_2= "which one of them has a lake view?"
response = chat.invoke(message_2).text.strip()
print(response)

To answer your question about which one has a lake view, I need more information!

Please tell me:

*   **What are "them"?** Are you referring to a list of properties, hotels, apartments, or something else?
*   **Can you provide the list or describe the options you're considering?** For example, if you're looking at hotels, you might say "Which of these hotels has a lake view: Hotel A, Hotel B, or Hotel C?"

Once I have that information, I can help you figure out which one has a lake view.

In [85]:
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash-lite",
    google_api_key = gemini_api_key,
    temperature = 0.7
)

In [86]:
# 7.1 Basic Memory (Conversation Buffer Memory)


from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.runnables import RunnableWithMessageHistory

store ={}
def get_session_history(session_id: str) -> InMemoryChatMessageHistory:
  if session_id not in store:
    store[session_id] = InMemoryChatMessageHistory()
  return store[session_id]

chain = RunnableWithMessageHistory(llm , get_session_history)
response = chain.invoke(
    "list 3 places to visit in paris" ,
    config={"configurable" : {"session_id":"1"}}


)
print(response.content)
print("*"*30)
response = chain.invoke(
    "which one of the has a lake view?",
    config = {"configurable":{"session_id":"1"}},
)
print(response.content)

Here are 3 iconic and diverse places to visit in Paris, catering to different interests:

1.  **The Eiffel Tower:** This is an absolute must-see for any first-time visitor to Paris. Its iconic silhouette dominates the skyline, and the views from its various levels are breathtaking, especially at sunset or when it sparkles at night. You can ascend by elevator or, for the more adventurous, climb the stairs to the first and second floors.

2.  **The Louvre Museum:** Home to an unparalleled collection of art and artifacts from around the world, the Louvre is a treasure trove. Beyond the Mona Lisa and Venus de Milo, you'll find Egyptian antiquities, Renaissance masterpieces, and so much more. It's vast, so plan your visit and perhaps focus on specific wings or periods if time is limited.

3.  **Montmartre & Sacré-Cœur Basilica:** This charming hilltop neighborhood offers a different side of Paris. Wander through its winding cobblestone streets, discover hidden squares, and soak in the bohemian atmosphere that once inspired artists like Picasso and Van Gogh. The stunning white Sacré-Cœur Basilica at the summit provides panoramic views of the city and is a beautiful architectural marvel in itself.
******************************
None of the three iconic places I listed (Eiffel Tower, Louvre Museum, Montmartre & Sacré-Cœur Basilica) directly *have* a lake view as their primary feature.

However, if you're looking for a place in Paris with a lake view, here's how you can get a taste of it from those locations or nearby:

*   **From the Eiffel Tower:** While not a lake, you get a fantastic view of the **Seine River** from the Eiffel Tower. The Seine is a major waterway that winds through Paris, and from the top, you can see it stretching out, with its bridges and boats. It's a beautiful water view, even if it's not a lake.

*   **From Montmartre & Sacré-Cœur Basilica:** The view from the Sacré-Cœur is primarily of the city of Paris. However, on a very clear day, you might be able to discern the **Bois de Boulogne** (a large park on the western edge of Paris) which contains several lakes, like the **Lac Inférieur** and **Lac Supérieur**. It's a distant and less prominent view of water, though.

**If you are specifically looking for a lake view in Paris, you might consider:**

*   **The Bois de Boulogne:** This expansive park has several beautiful lakes, such as the **Lac Inférieur** (Lower Lake) and the **Lac Supérieur** (Upper Lake). You can rent rowboats on these lakes and enjoy a peaceful afternoon surrounded by nature.
*   **The Parc des Buttes-Chaumont:** This hilly park features a picturesque artificial lake with a grotto and a temple perched on an island, accessible by a bridge. It offers a charming and tranquil water view.

In [87]:
# Print all conversation messages
history = store["1"]  # same session_id you used above
print("\nFull conversation:")
print("=" * 40)
for msg in history.messages:
    role = "User" if msg.type == "human" else "AI"
    print(f"{role}: {msg.content}\n")

Full conversation:
========================================
User: list 3 places to visit in paris

AI: Here are 3 iconic and diverse places to visit in Paris, catering to different interests:

1.  **The Eiffel Tower:** This is an absolute must-see for any first-time visitor to Paris. Its iconic silhouette dominates the skyline, and the views from its various levels are breathtaking, especially at sunset or when it sparkles at night. You can ascend by elevator or, for the more adventurous, climb the stairs to the first and second floors.

2.  **The Louvre Museum:** Home to an unparalleled collection of art and artifacts from around the world, the Louvre is a treasure trove. Beyond the Mona Lisa and Venus de Milo, you'll find Egyptian antiquities, Renaissance masterpieces, and so much more. It's vast, so plan your visit and perhaps focus on specific wings or periods if time is limited.

3.  **Montmartre & Sacré-Cœur Basilica:** This charming hilltop neighborhood offers a different side of Paris. Wander through its winding cobblestone streets, discover hidden squares, and soak in the bohemian atmosphere that once inspired artists like Picasso and Van Gogh. The stunning white Sacré-Cœur Basilica at the summit provides panoramic views of the city and is a beautiful architectural marvel in itself.

User: which one of the has a lake view?

AI: None of the three iconic places I listed (Eiffel Tower, Louvre Museum, Montmartre & Sacré-Cœur Basilica) directly *have* a lake view as their primary feature.

However, if you're looking for a place in Paris with a lake view, here's how you can get a taste of it from those locations or nearby:

*   **From the Eiffel Tower:** While not a lake, you get a fantastic view of the **Seine River** from the Eiffel Tower. The Seine is a major waterway that winds through Paris, and from the top, you can see it stretching out, with its bridges and boats. It's a beautiful water view, even if it's not a lake.

*   **From Montmartre & Sacré-Cœur Basilica:** The view from the Sacré-Cœur is primarily of the city of Paris. However, on a very clear day, you might be able to discern the **Bois de Boulogne** (a large park on the western edge of Paris) which contains several lakes, like the **Lac Inférieur** and **Lac Supérieur**. It's a distant and less prominent view of water, though.

**If you are specifically looking for a lake view in Paris, you might consider:**

*   **The Bois de Boulogne:** This expansive park has several beautiful lakes, such as the **Lac Inférieur** (Lower Lake) and the **Lac Supérieur** (Upper Lake). You can rent rowboats on these lakes and enjoy a peaceful afternoon surrounded by nature.
*   **The Parc des Buttes-Chaumont:** This hilly park features a picturesque artificial lake with a grotto and a temple perched on an island, accessible by a bridge. It offers a charming and tranquil water view.

In [88]:
history.messages

[HumanMessage(content='list 3 places to visit in paris', additional_kwargs={}, response_metadata={}),
 AIMessage(content="Here are 3 iconic and diverse places to visit in Paris, catering to different interests:\n\n1.  **The Eiffel Tower:** This is an absolute must-see for any first-time visitor to Paris. Its iconic silhouette dominates the skyline, and the views from its various levels are breathtaking, especially at sunset or when it sparkles at night. You can ascend by elevator or, for the more adventurous, climb the stairs to the first and second floors.\n\n2.  **The Louvre Museum:** Home to an unparalleled collection of art and artifacts from around the world, the Louvre is a treasure trove. Beyond the Mona Lisa and Venus de Milo, you'll find Egyptian antiquities, Renaissance masterpieces, and so much more. It's vast, so plan your visit and perhaps focus on specific wings or periods if time is limited.\n\n3.  **Montmartre & Sacré-Cœur Basilica:** This charming hilltop neighborhood offers a different side of Paris. Wander through its winding cobblestone streets, discover hidden squares, and soak in the bohemian atmosphere that once inspired artists like Picasso and Van Gogh. The stunning white Sacré-Cœur Basilica at the summit provides panoramic views of the city and is a beautiful architectural marvel in itself.", additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc799-cf00-7a82-b5fe-a136e4a0612c-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 9, 'output_tokens': 251, 'total_tokens': 260, 'input_token_details': {'cache_read': 0}}),
 HumanMessage(content='which one of the has a lake view?', additional_kwargs={}, response_metadata={}),
 AIMessage(content="None of the three iconic places I listed (Eiffel Tower, Louvre Museum, Montmartre & Sacré-Cœur Basilica) directly *have* a lake view as their primary feature.\n\nHowever, if you're looking for a place in Paris with a lake view, here's how you can get a taste of it from those locations or nearby:\n\n*   **From the Eiffel Tower:** While not a lake, you get a fantastic view of the **Seine River** from the Eiffel Tower. The Seine is a major waterway that winds through Paris, and from the top, you can see it stretching out, with its bridges and boats. It's a beautiful water view, even if it's not a lake.\n\n*   **From Montmartre & Sacré-Cœur Basilica:** The view from the Sacré-Cœur is primarily of the city of Paris. However, on a very clear day, you might be able to discern the **Bois de Boulogne** (a large park on the western edge of Paris) which contains several lakes, like the **Lac Inférieur** and **Lac Supérieur**. It's a distant and less prominent view of water, though.\n\n**If you are specifically looking for a lake view in Paris, you might consider:**\n\n*   **The Bois de Boulogne:** This expansive park has several beautiful lakes, such as the **Lac Inférieur** (Lower Lake) and the **Lac Supérieur** (Upper Lake). You can rent rowboats on these lakes and enjoy a peaceful afternoon surrounded by nature.\n*   **The Parc des Buttes-Chaumont:** This hilly park features a picturesque artificial lake with a grotto and a temple perched on an island, accessible by a bridge. It offers a charming and tranquil water view.", additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc799-d6b7-7aa3-aae7-5044380566c9-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 271, 'output_tokens': 370, 'total_tokens': 641, 'input_token_details': {'cache_read': 0}})]

In [89]:
store

{'1': InMemoryChatMessageHistory(messages=[HumanMessage(content='list 3 places to visit in paris', additional_kwargs={}, response_metadata={}), AIMessage(content="Here are 3 iconic and diverse places to visit in Paris, catering to different interests:\n\n1.  **The Eiffel Tower:** This is an absolute must-see for any first-time visitor to Paris. Its iconic silhouette dominates the skyline, and the views from its various levels are breathtaking, especially at sunset or when it sparkles at night. You can ascend by elevator or, for the more adventurous, climb the stairs to the first and second floors.\n\n2.  **The Louvre Museum:** Home to an unparalleled collection of art and artifacts from around the world, the Louvre is a treasure trove. Beyond the Mona Lisa and Venus de Milo, you'll find Egyptian antiquities, Renaissance masterpieces, and so much more. It's vast, so plan your visit and perhaps focus on specific wings or periods if time is limited.\n\n3.  **Montmartre & Sacré-Cœur Basilica:** This charming hilltop neighborhood offers a different side of Paris. Wander through its winding cobblestone streets, discover hidden squares, and soak in the bohemian atmosphere that once inspired artists like Picasso and Van Gogh. The stunning white Sacré-Cœur Basilica at the summit provides panoramic views of the city and is a beautiful architectural marvel in itself.", additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc799-cf00-7a82-b5fe-a136e4a0612c-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 9, 'output_tokens': 251, 'total_tokens': 260, 'input_token_details': {'cache_read': 0}}), HumanMessage(content='which one of the has a lake view?', additional_kwargs={}, response_metadata={}), AIMessage(content="None of the three iconic places I listed (Eiffel Tower, Louvre Museum, Montmartre & Sacré-Cœur Basilica) directly *have* a lake view as their primary feature.\n\nHowever, if you're looking for a place in Paris with a lake view, here's how you can get a taste of it from those locations or nearby:\n\n*   **From the Eiffel Tower:** While not a lake, you get a fantastic view of the **Seine River** from the Eiffel Tower. The Seine is a major waterway that winds through Paris, and from the top, you can see it stretching out, with its bridges and boats. It's a beautiful water view, even if it's not a lake.\n\n*   **From Montmartre & Sacré-Cœur Basilica:** The view from the Sacré-Cœur is primarily of the city of Paris. However, on a very clear day, you might be able to discern the **Bois de Boulogne** (a large park on the western edge of Paris) which contains several lakes, like the **Lac Inférieur** and **Lac Supérieur**. It's a distant and less prominent view of water, though.\n\n**If you are specifically looking for a lake view in Paris, you might consider:**\n\n*   **The Bois de Boulogne:** This expansive park has several beautiful lakes, such as the **Lac Inférieur** (Lower Lake) and the **Lac Supérieur** (Upper Lake). You can rent rowboats on these lakes and enjoy a peaceful afternoon surrounded by nature.\n*   **The Parc des Buttes-Chaumont:** This hilly park features a picturesque artificial lake with a grotto and a temple perched on an island, accessible by a bridge. It offers a charming and tranquil water view.", additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc799-d6b7-7aa3-aae7-5044380566c9-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 271, 'output_tokens': 370, 'total_tokens': 641, 'input_token_details': {'cache_read': 0}})])}

In [90]:
store.clear()

In [91]:
store

{}

# **Example**

In [92]:
from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.runnables import RunnableWithMessageHistory

store ={}

def get_session_history1(session_id:str) -> InMemoryChatMessageHistory:
  if session_id not in store:
    store[session_id] = InMemoryChatMessageHistory()
  return store[session_id]

chain = RunnableWithMessageHistory(llm  , get_session_history1)
response = chain.invoke(
    "list 3 places to visit in Egypt",
    config ={"configurable" : {"session_id" : "1"}},
)
print(response.content)
print("*"*30)
response = chain.invoke(
    "which one of the has the greatest history?",
    config = {"configurable" : {"session_id" : "1"}},
)

print(response.content)

Here are 3 fantastic places to visit in Egypt, offering a mix of history, culture, and natural beauty:

1.  **The Pyramids of Giza and the Sphinx (Giza):** This is arguably the most iconic and essential Egyptian experience. Standing before the Great Pyramid of Giza, the last of the Seven Wonders of the Ancient World still standing, is awe-inspiring. You can explore the complex, learn about their history, and marvel at the enigmatic Sphinx, a mythical creature with the body of a lion and the head of a human. It's a journey back in time to one of humanity's greatest achievements.

2.  **Luxor (Upper Egypt):** Often called the "world's greatest open-air museum," Luxor is a treasure trove of ancient Egyptian history. It's home to two magnificent temple complexes:
    *   **Karnak Temple Complex:** A vast and sprawling complex that was built and expanded over centuries, dedicated to the god Amun-Ra. Its massive columns, obelisks, and sanctuaries are incredibly impressive.
    *   **Luxor Temple:** Beautifully illuminated at night, this temple is dedicated to the rejuvenation of kingship.
    Beyond the temples, you can also visit the **Valley of the Kings** on the West Bank, where pharaohs like Tutankhamun were buried in elaborate tombs, and the **Temple of Hatshepsut**, a stunning mortuary temple carved into a cliff face.

3.  **Aswan (Upper Egypt):** Located on the Nile River, Aswan offers a more relaxed and picturesque experience compared to the bustling cities. It's a gateway to Nubian culture and stunning natural landscapes. Key attractions include:
    *   **Philae Temple:** An incredibly beautiful temple dedicated to the goddess Isis, meticulously relocated to Agilkia Island to save it from flooding.
    *   **The High Dam:** A marvel of modern engineering that controls the Nile's floods and generates electricity.
    *   **Nubian Villages:** Take a boat trip to visit vibrant Nubian villages, experience their unique culture, and enjoy colorful houses and warm hospitality.
    *   **A Felucca Ride on the Nile:** Enjoy a traditional sailboat ride on the Nile, especially at sunset, for breathtaking views of the river and surrounding islands.

These three locations provide a fantastic introduction to the rich history, monumental architecture, and vibrant culture of Egypt.
******************************
While all three locations are steeped in incredible history, **Luxor** arguably has the **greatest concentration and breadth of historical significance.**

Here's why:

*   **Thebes, the Ancient Capital:** Luxor was once the ancient Egyptian capital of Thebes, a powerful and wealthy city for over a thousand years. This means it was the center of political, religious, and cultural life for a significant portion of ancient Egyptian history.
*   **Unparalleled Concentration of Sites:** As mentioned, Luxor is often called the "world's greatest open-air museum." It boasts:
    *   **Karnak Temple Complex:** The largest religious building ever constructed, representing centuries of continuous worship and construction.
    *   **Luxor Temple:** A testament to royal power and religious rituals.
    *   **Valley of the Kings:** The burial ground of numerous pharaohs from the New Kingdom, offering direct insights into their beliefs about the afterlife and their earthly power.
    *   **Valley of the Queens:** The burial place for queens, princes, and other royal family members.
    *   **Mortuary Temples:** Like Hatshepsut's temple, showcasing unique architectural styles and historical narratives.
*   **Continuous Occupation and Development:** Unlike the Pyramids of Giza, which are primarily a necropolis from the Old Kingdom, Luxor's history spans multiple dynasties and periods, with continuous development and rebuilding of its religious and monumental structures.

**Why the others are still historically significant, but perhaps not to the same *breadth* as Luxor:**

*   **Pyramids of Giza:** Their historical significance is immense, primarily representing the pinnacle of Old Kingdom engineering and the power of the pharaohs of that era. They are incredibly important for understanding the early development of Egyptian civilization and monumental architecture. However, their primary focus is on a specific period and function (burial and monumental display).
*   **Aswan:** Aswan has a rich history, particularly as a strategic trading post and a gateway to Nubia. It has ancient sites like Philae and Abu Simbel (though Abu Simbel is a day trip from Aswan, often considered part of the broader Aswan region's historical offerings). It's also crucial for understanding later periods and interactions with neighboring cultures. However, the sheer density and continuous development of major religious and royal sites in Luxor make it stand out for its historical depth.

**In summary:** If you are looking for a place that encapsulates the vast sweep of ancient Egyptian civilization, its religious practices, royal power, and architectural achievements across multiple dynasties, **Luxor** is the destination with the greatest historical depth and breadth.

In [93]:
# Print all conversation messages
history = store["1"]  # same session_id you used above
print("\nFull conversation:")
print("=" * 40)
for msg in history.messages:
    role = "User" if msg.type == "human" else "AI"
    print(f"{role}: {msg.content}\n")

Full conversation:
========================================
User: list 3 places to visit in Egypt

AI: Here are 3 fantastic places to visit in Egypt, offering a mix of history, culture, and natural beauty:

1.  **The Pyramids of Giza and the Sphinx (Giza):** This is arguably the most iconic and essential Egyptian experience. Standing before the Great Pyramid of Giza, the last of the Seven Wonders of the Ancient World still standing, is awe-inspiring. You can explore the complex, learn about their history, and marvel at the enigmatic Sphinx, a mythical creature with the body of a lion and the head of a human. It's a journey back in time to one of humanity's greatest achievements.

2.  **Luxor (Upper Egypt):** Often called the "world's greatest open-air museum," Luxor is a treasure trove of ancient Egyptian history. It's home to two magnificent temple complexes:
    *   **Karnak Temple Complex:** A vast and sprawling complex that was built and expanded over centuries, dedicated to the god Amun-Ra. Its massive columns, obelisks, and sanctuaries are incredibly impressive.
    *   **Luxor Temple:** Beautifully illuminated at night, this temple is dedicated to the rejuvenation of kingship.
    Beyond the temples, you can also visit the **Valley of the Kings** on the West Bank, where pharaohs like Tutankhamun were buried in elaborate tombs, and the **Temple of Hatshepsut**, a stunning mortuary temple carved into a cliff face.

3.  **Aswan (Upper Egypt):** Located on the Nile River, Aswan offers a more relaxed and picturesque experience compared to the bustling cities. It's a gateway to Nubian culture and stunning natural landscapes. Key attractions include:
    *   **Philae Temple:** An incredibly beautiful temple dedicated to the goddess Isis, meticulously relocated to Agilkia Island to save it from flooding.
    *   **The High Dam:** A marvel of modern engineering that controls the Nile's floods and generates electricity.
    *   **Nubian Villages:** Take a boat trip to visit vibrant Nubian villages, experience their unique culture, and enjoy colorful houses and warm hospitality.
    *   **A Felucca Ride on the Nile:** Enjoy a traditional sailboat ride on the Nile, especially at sunset, for breathtaking views of the river and surrounding islands.

These three locations provide a fantastic introduction to the rich history, monumental architecture, and vibrant culture of Egypt.

User: which one of the has the greatest history?

AI: While all three locations are steeped in incredible history, **Luxor** arguably has the **greatest concentration and breadth of historical significance.**

Here's why:

*   **Thebes, the Ancient Capital:** Luxor was once the ancient Egyptian capital of Thebes, a powerful and wealthy city for over a thousand years. This means it was the center of political, religious, and cultural life for a significant portion of ancient Egyptian history.
*   **Unparalleled Concentration of Sites:** As mentioned, Luxor is often called the "world's greatest open-air museum." It boasts:
    *   **Karnak Temple Complex:** The largest religious building ever constructed, representing centuries of continuous worship and construction.
    *   **Luxor Temple:** A testament to royal power and religious rituals.
    *   **Valley of the Kings:** The burial ground of numerous pharaohs from the New Kingdom, offering direct insights into their beliefs about the afterlife and their earthly power.
    *   **Valley of the Queens:** The burial place for queens, princes, and other royal family members.
    *   **Mortuary Temples:** Like Hatshepsut's temple, showcasing unique architectural styles and historical narratives.
*   **Continuous Occupation and Development:** Unlike the Pyramids of Giza, which are primarily a necropolis from the Old Kingdom, Luxor's history spans multiple dynasties and periods, with continuous development and rebuilding of its religious and monumental structures.

**Why the others are still historically significant, but perhaps not to the same *breadth* as Luxor:**

*   **Pyramids of Giza:** Their historical significance is immense, primarily representing the pinnacle of Old Kingdom engineering and the power of the pharaohs of that era. They are incredibly important for understanding the early development of Egyptian civilization and monumental architecture. However, their primary focus is on a specific period and function (burial and monumental display).
*   **Aswan:** Aswan has a rich history, particularly as a strategic trading post and a gateway to Nubia. It has ancient sites like Philae and Abu Simbel (though Abu Simbel is a day trip from Aswan, often considered part of the broader Aswan region's historical offerings). It's also crucial for understanding later periods and interactions with neighboring cultures. However, the sheer density and continuous development of major religious and royal sites in Luxor make it stand out for its historical depth.

**In summary:** If you are looking for a place that encapsulates the vast sweep of ancient Egyptian civilization, its religious practices, royal power, and architectural achievements across multiple dynasties, **Luxor** is the destination with the greatest historical depth and breadth.

In [94]:
history.messages

[HumanMessage(content='list 3 places to visit in Egypt', additional_kwargs={}, response_metadata={}),
 AIMessage(content='Here are 3 fantastic places to visit in Egypt, offering a mix of history, culture, and natural beauty:\n\n1.  **The Pyramids of Giza and the Sphinx (Giza):** This is arguably the most iconic and essential Egyptian experience. Standing before the Great Pyramid of Giza, the last of the Seven Wonders of the Ancient World still standing, is awe-inspiring. You can explore the complex, learn about their history, and marvel at the enigmatic Sphinx, a mythical creature with the body of a lion and the head of a human. It\'s a journey back in time to one of humanity\'s greatest achievements.\n\n2.  **Luxor (Upper Egypt):** Often called the "world\'s greatest open-air museum," Luxor is a treasure trove of ancient Egyptian history. It\'s home to two magnificent temple complexes:\n    *   **Karnak Temple Complex:** A vast and sprawling complex that was built and expanded over centuries, dedicated to the god Amun-Ra. Its massive columns, obelisks, and sanctuaries are incredibly impressive.\n    *   **Luxor Temple:** Beautifully illuminated at night, this temple is dedicated to the rejuvenation of kingship.\n    Beyond the temples, you can also visit the **Valley of the Kings** on the West Bank, where pharaohs like Tutankhamun were buried in elaborate tombs, and the **Temple of Hatshepsut**, a stunning mortuary temple carved into a cliff face.\n\n3.  **Aswan (Upper Egypt):** Located on the Nile River, Aswan offers a more relaxed and picturesque experience compared to the bustling cities. It\'s a gateway to Nubian culture and stunning natural landscapes. Key attractions include:\n    *   **Philae Temple:** An incredibly beautiful temple dedicated to the goddess Isis, meticulously relocated to Agilkia Island to save it from flooding.\n    *   **The High Dam:** A marvel of modern engineering that controls the Nile\'s floods and generates electricity.\n    *   **Nubian Villages:** Take a boat trip to visit vibrant Nubian villages, experience their unique culture, and enjoy colorful houses and warm hospitality.\n    *   **A Felucca Ride on the Nile:** Enjoy a traditional sailboat ride on the Nile, especially at sunset, for breathtaking views of the river and surrounding islands.\n\nThese three locations provide a fantastic introduction to the rich history, monumental architecture, and vibrant culture of Egypt.', additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc799-edb7-7f73-8e87-492966c75d97-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 9, 'output_tokens': 509, 'total_tokens': 518, 'input_token_details': {'cache_read': 0}}),
 HumanMessage(content='which one of the has the greatest history?', additional_kwargs={}, response_metadata={}),
 AIMessage(content='While all three locations are steeped in incredible history, **Luxor** arguably has the **greatest concentration and breadth of historical significance.**\n\nHere\'s why:\n\n*   **Thebes, the Ancient Capital:** Luxor was once the ancient Egyptian capital of Thebes, a powerful and wealthy city for over a thousand years. This means it was the center of political, religious, and cultural life for a significant portion of ancient Egyptian history.\n*   **Unparalleled Concentration of Sites:** As mentioned, Luxor is often called the "world\'s greatest open-air museum." It boasts:\n    *   **Karnak Temple Complex:** The largest religious building ever constructed, representing centuries of continuous worship and construction.\n    *   **Luxor Temple:** A testament to royal power and religious rituals.\n    *   **Valley of the Kings:** The burial ground of numerous pharaohs from the New Kingdom, offering direct insights into their beliefs about the afterlife and their earthly power.\n    *   **Valley of the Queens:** The burial place for queens, princes, and other royal family members.\n    *   **Mortuary Temples:** Like Hatshepsut\'s temple, showcasing unique architectural styles and historical narratives.\n*   **Continuous Occupation and Development:** Unlike the Pyramids of Giza, which are primarily a necropolis from the Old Kingdom, Luxor\'s history spans multiple dynasties and periods, with continuous development and rebuilding of its religious and monumental structures.\n\n**Why the others are still historically significant, but perhaps not to the same *breadth* as Luxor:**\n\n*   **Pyramids of Giza:** Their historical significance is immense, primarily representing the pinnacle of Old Kingdom engineering and the power of the pharaohs of that era. They are incredibly important for understanding the early development of Egyptian civilization and monumental architecture. However, their primary focus is on a specific period and function (burial and monumental display).\n*   **Aswan:** Aswan has a rich history, particularly as a strategic trading post and a gateway to Nubia. It has ancient sites like Philae and Abu Simbel (though Abu Simbel is a day trip from Aswan, often considered part of the broader Aswan region\'s historical offerings). It\'s also crucial for understanding later periods and interactions with neighboring cultures. However, the sheer density and continuous development of major religious and royal sites in Luxor make it stand out for its historical depth.\n\n**In summary:** If you are looking for a place that encapsulates the vast sweep of ancient Egyptian civilization, its religious practices, royal power, and architectural achievements across multiple dynasties, **Luxor** is the destination with the greatest historical depth and breadth.', additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc799-fb65-72a1-b2ce-d51754cb3d1f-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 529, 'output_tokens': 554, 'total_tokens': 1083, 'input_token_details': {'cache_read': 0}})]

In [95]:
store

{'1': InMemoryChatMessageHistory(messages=[HumanMessage(content='list 3 places to visit in Egypt', additional_kwargs={}, response_metadata={}), AIMessage(content='Here are 3 fantastic places to visit in Egypt, offering a mix of history, culture, and natural beauty:\n\n1.  **The Pyramids of Giza and the Sphinx (Giza):** This is arguably the most iconic and essential Egyptian experience. Standing before the Great Pyramid of Giza, the last of the Seven Wonders of the Ancient World still standing, is awe-inspiring. You can explore the complex, learn about their history, and marvel at the enigmatic Sphinx, a mythical creature with the body of a lion and the head of a human. It\'s a journey back in time to one of humanity\'s greatest achievements.\n\n2.  **Luxor (Upper Egypt):** Often called the "world\'s greatest open-air museum," Luxor is a treasure trove of ancient Egyptian history. It\'s home to two magnificent temple complexes:\n    *   **Karnak Temple Complex:** A vast and sprawling complex that was built and expanded over centuries, dedicated to the god Amun-Ra. Its massive columns, obelisks, and sanctuaries are incredibly impressive.\n    *   **Luxor Temple:** Beautifully illuminated at night, this temple is dedicated to the rejuvenation of kingship.\n    Beyond the temples, you can also visit the **Valley of the Kings** on the West Bank, where pharaohs like Tutankhamun were buried in elaborate tombs, and the **Temple of Hatshepsut**, a stunning mortuary temple carved into a cliff face.\n\n3.  **Aswan (Upper Egypt):** Located on the Nile River, Aswan offers a more relaxed and picturesque experience compared to the bustling cities. It\'s a gateway to Nubian culture and stunning natural landscapes. Key attractions include:\n    *   **Philae Temple:** An incredibly beautiful temple dedicated to the goddess Isis, meticulously relocated to Agilkia Island to save it from flooding.\n    *   **The High Dam:** A marvel of modern engineering that controls the Nile\'s floods and generates electricity.\n    *   **Nubian Villages:** Take a boat trip to visit vibrant Nubian villages, experience their unique culture, and enjoy colorful houses and warm hospitality.\n    *   **A Felucca Ride on the Nile:** Enjoy a traditional sailboat ride on the Nile, especially at sunset, for breathtaking views of the river and surrounding islands.\n\nThese three locations provide a fantastic introduction to the rich history, monumental architecture, and vibrant culture of Egypt.', additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc799-edb7-7f73-8e87-492966c75d97-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 9, 'output_tokens': 509, 'total_tokens': 518, 'input_token_details': {'cache_read': 0}}), HumanMessage(content='which one of the has the greatest history?', additional_kwargs={}, response_metadata={}), AIMessage(content='While all three locations are steeped in incredible history, **Luxor** arguably has the **greatest concentration and breadth of historical significance.**\n\nHere\'s why:\n\n*   **Thebes, the Ancient Capital:** Luxor was once the ancient Egyptian capital of Thebes, a powerful and wealthy city for over a thousand years. This means it was the center of political, religious, and cultural life for a significant portion of ancient Egyptian history.\n*   **Unparalleled Concentration of Sites:** As mentioned, Luxor is often called the "world\'s greatest open-air museum." It boasts:\n    *   **Karnak Temple Complex:** The largest religious building ever constructed, representing centuries of continuous worship and construction.\n    *   **Luxor Temple:** A testament to royal power and religious rituals.\n    *   **Valley of the Kings:** The burial ground of numerous pharaohs from the New Kingdom, offering direct insights into their beliefs about the afterlife and their earthly power.\n    *   **Valley of the Queens:** The burial place for queens, princes, and other royal family members.\n    *   **Mortuary Temples:** Like Hatshepsut\'s temple, showcasing unique architectural styles and historical narratives.\n*   **Continuous Occupation and Development:** Unlike the Pyramids of Giza, which are primarily a necropolis from the Old Kingdom, Luxor\'s history spans multiple dynasties and periods, with continuous development and rebuilding of its religious and monumental structures.\n\n**Why the others are still historically significant, but perhaps not to the same *breadth* as Luxor:**\n\n*   **Pyramids of Giza:** Their historical significance is immense, primarily representing the pinnacle of Old Kingdom engineering and the power of the pharaohs of that era. They are incredibly important for understanding the early development of Egyptian civilization and monumental architecture. However, their primary focus is on a specific period and function (burial and monumental display).\n*   **Aswan:** Aswan has a rich history, particularly as a strategic trading post and a gateway to Nubia. It has ancient sites like Philae and Abu Simbel (though Abu Simbel is a day trip from Aswan, often considered part of the broader Aswan region\'s historical offerings). It\'s also crucial for understanding later periods and interactions with neighboring cultures. However, the sheer density and continuous development of major religious and royal sites in Luxor make it stand out for its historical depth.\n\n**In summary:** If you are looking for a place that encapsulates the vast sweep of ancient Egyptian civilization, its religious practices, royal power, and architectural achievements across multiple dynasties, **Luxor** is the destination with the greatest historical depth and breadth.', additional_kwargs={}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash-lite', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--019bc799-fb65-72a1-b2ce-d51754cb3d1f-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 529, 'output_tokens': 554, 'total_tokens': 1083, 'input_token_details': {'cache_read': 0}})])}

In [96]:
store.clear()

In [97]:
store

{}

# 7.2 Conversation Buffer Window Memory

# Keeps the last n turns of the conversation. Drops the oldest turn when the buffer is full.

In [98]:
from langchain_core.messages import trim_messages

selected_messages = trim_messages(
    history.messages,
    token_counter=len,  # <-- len will simply count the number of messages rather than tokens
    max_tokens=3,  # <-- allow up to 2 messages.
    strategy="last",
    # Most chat models expect that chat history starts with either:
    # (1) a HumanMessage or
    # (2) a SystemMessage followed by a HumanMessage
    # start_on="human" makes sure we produce a valid chat history
    start_on="human",
    # Usually, we want to keep the SystemMessage
    # if it's present in the original history.
    # The SystemMessage has special instructions for the model.
    include_system=True,
    allow_partial=False,
)

for msg in selected_messages:
    msg.pretty_print()

================================ Human Message =================================

which one of the has the greatest history?
================================== Ai Message ==================================

While all three locations are steeped in incredible history, **Luxor** arguably has the **greatest concentration and breadth of historical significance.**

Here's why:

*   **Thebes, the Ancient Capital:** Luxor was once the ancient Egyptian capital of Thebes, a powerful and wealthy city for over a thousand years. This means it was the center of political, religious, and cultural life for a significant portion of ancient Egyptian history.
*   **Unparalleled Concentration of Sites:** As mentioned, Luxor is often called the "world's greatest open-air museum." It boasts:
    *   **Karnak Temple Complex:** The largest religious building ever constructed, representing centuries of continuous worship and construction.
    *   **Luxor Temple:** A testament to royal power and religious rituals.
    *   **Valley of the Kings:** The burial ground of numerous pharaohs from the New Kingdom, offering direct insights into their beliefs about the afterlife and their earthly power.
    *   **Valley of the Queens:** The burial place for queens, princes, and other royal family members.
    *   **Mortuary Temples:** Like Hatshepsut's temple, showcasing unique architectural styles and historical narratives.
*   **Continuous Occupation and Development:** Unlike the Pyramids of Giza, which are primarily a necropolis from the Old Kingdom, Luxor's history spans multiple dynasties and periods, with continuous development and rebuilding of its religious and monumental structures.

**Why the others are still historically significant, but perhaps not to the same *breadth* as Luxor:**

*   **Pyramids of Giza:** Their historical significance is immense, primarily representing the pinnacle of Old Kingdom engineering and the power of the pharaohs of that era. They are incredibly important for understanding the early development of Egyptian civilization and monumental architecture. However, their primary focus is on a specific period and function (burial and monumental display).
*   **Aswan:** Aswan has a rich history, particularly as a strategic trading post and a gateway to Nubia. It has ancient sites like Philae and Abu Simbel (though Abu Simbel is a day trip from Aswan, often considered part of the broader Aswan region's historical offerings). It's also crucial for understanding later periods and interactions with neighboring cultures. However, the sheer density and continuous development of major religious and royal sites in Luxor make it stand out for its historical depth.

**In summary:** If you are looking for a place that encapsulates the vast sweep of ancient Egyptian civilization, its religious practices, royal power, and architectural achievements across multiple dynasties, **Luxor** is the destination with the greatest historical depth and breadth.

In [109]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, AIMessage
from langgraph.graph import StateGraph, END

gemini_api_key = gemini_api_key

model = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-lite",
    google_api_key=gemini_api_key,
    temperature=0.7,
)

# --- STEP 1: Define the state ---
from typing import List, TypedDict

class State(TypedDict):
    messages: List
    summary: str

# --- STEP 2: Define your summarization reducer ---
def summarize_conversation(state: State):
    summary = state.get("summary", "")
    if summary:
        summary_message = (
            f"This is a summary of the conversation so far: {summary}\n\n"
            "Extend the summary by considering the new messages above."
        )
    else:
        summary_message = "Create a summary of the conversation above."

    # Add the summarization instruction to the messages
    messages = state["messages"] + [HumanMessage(content=summary_message)]
    response = model.invoke(messages)

    # Keep the last 2 messages and store new summary
    return {
        "summary": response.content,
        "messages": state["messages"][-2:]  # keep short memory
    }

# --- STEP 3: Define the main conversation node ---
def chat_node(state: State):
    response = model.invoke(state["messages"])
    return {"messages": state["messages"] + [response]}

# --- STEP 4: Build the graph ---
graph = StateGraph(State)

graph.add_node("chat", chat_node)
graph.add_node("summarize", summarize_conversation)
graph.add_edge("chat", "summarize")
graph.add_edge("summarize", END)

graph.set_entry_point("chat")

app = graph.compile()

# --- STEP 5: Run the conversation ---
state = {"messages": [HumanMessage(content="List 3 places to visit in Paris.")], "summary": ""}

state = app.invoke(state)
print("Bot:", state["messages"][-1].content)
print("Summary:", state["summary"])

# Continue conversation
state["messages"].append(HumanMessage(content="Which one of them has a lake view?"))
state = app.invoke(state)

print("\nBot:", state["messages"][-1].content)
print("Updated summary:", state["summary"])

Bot: Here are 3 iconic places to visit in Paris:

1.  **The Eiffel Tower:** This is probably the most recognizable landmark in Paris and a must-see for any visitor. You can admire it from below, go up to the different levels for breathtaking panoramic views of the city, or even have a meal at one of its restaurants.

2.  **The Louvre Museum:** Home to thousands of works of art, including the Mona Lisa and the Venus de Milo, the Louvre is one of the world's largest and most famous museums. Even if you're not an art aficionado, the sheer scale and grandeur of the building and its collections are impressive.

3.  **Notre-Dame Cathedral:** While currently undergoing restoration after the fire, Notre-Dame remains a powerful symbol of Paris and a magnificent example of Gothic architecture. You can still admire its exterior and the ongoing reconstruction efforts, and the surrounding Île de la Cité is a charming area to explore.
Summary: The conversation started with a request for three places to visit in Paris. I provided a list of three iconic locations: the Eiffel Tower, the Louvre Museum, and Notre-Dame Cathedral, along with brief descriptions of why each is worth visiting.

Bot: None of the three places listed (Eiffel Tower, Louvre Museum, Notre-Dame Cathedral) directly overlook a lake.

Paris is not known for having large natural lakes within the city center. However, here's a slight clarification:

*   **Eiffel Tower:** While not a lake, the Eiffel Tower offers spectacular views of the **Seine River**, which is a prominent waterway flowing through the city. You can see the river from the tower.
*   **Louvre Museum:** The Louvre is located near the **Tuileries Garden**, which has several small ornamental ponds, but not a lake.
*   **Notre-Dame Cathedral:** Notre-Dame is situated on the **Île de la Cité**, an island in the Seine River. You'll see the river surrounding the island.

If you are specifically looking for a place with a lake view in Paris, you might need to consider locations a bit further out or specific parks.
Updated summary: This is a summary of the conversation so far: The conversation started with a request for three places to visit in Paris. I provided a list of three iconic locations: the Eiffel Tower, the Louvre Museum, and Notre-Dame Cathedral, along with brief descriptions of why each is worth visiting. When asked which of these locations has a lake view, I clarified that none of the initially suggested places directly overlook a lake. I explained that while the Eiffel Tower and Notre-Dame are situated near the Seine River, and the Louvre is close to ornamental ponds in the Tuileries Garden, none offer a true lake view within the city center.

 ## 7.5 Save messages into File

In [110]:
from langchain_core.messages import AIMessage , HumanMessage , messages_to_dict , messages_from_dict
import json

messages = [
    HumanMessage(content = "Hello"),
    AIMessage(content="Hi There! How can i help you?"),
    HumanMessage(content="Tell me a joke."),
    AIMessage(content="Why did the computer go to art school? Because it had a lot of cache!")
]

# Convert messages to dictionary format
messages_dict = messages_to_dict(messages)

# Save to a json file
with open("Conversation-memory.json","w") as f:
  json.dump(messages_dict , f, indent=2 , ensure_ascii=False)

print("Conversation saved to conversation-memory.json")

Conversation saved to conversation-memory.json

# 7.6 Load Saved Messages into history

In [111]:
from langchain_core.messages import messages_from_dict
from langchain_community.chat_message_histories import ChatMessageHistory
import json

# Load From Json
with open("Conversation-memory.json" , "r") as f:
  dicts = json.load(f)

In [112]:
# Convert to Message objects
messages = messages_from_dict(dicts)

# Create ChatMessageHistory and load them
history = ChatMessageHistory()
for msg in messages:
    history.add_message(msg)

print("Loaded history:")
for m in history.messages:
    print(f"{m.type}: {m.content}")

Loaded history:
human: Hello
ai: Hi There! How can i help you?
human: Tell me a joke.
ai: Why did the computer go to art school? Because it had a lot of cache!

In [113]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.runnables.history import RunnableWithMessageHistory

chat = ChatGoogleGenerativeAI(
      model = "gemini-2.5-flash-lite",
      temperature = 0.7 ,
      google_api_key = gemini_api_key
)
store = {"session_1": history}  # reuse loaded history

def get_session_history(session_id: str):
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]

chain = RunnableWithMessageHistory(chat, get_session_history)

response = chain.invoke(
    "as an egyptian, which place from the 3 i will like most?",
    config={"configurable": {"session_id": "session_1"}},
)

print(response.content)

To give you the best recommendation, I need a little more information! Please tell me the **three places** you're considering.

Once you tell me the places, I can think about what kind of things Egyptians often enjoy and recommend the one that aligns best. 😊

#8. Loaders

##8.1 Data Frame Loader

In [114]:
!wget -O youtube-sub.csv https://raw.githubusercontent.com/petlja/jupyterBookSrCyr/master/podaci/Top%2025%20YouTubers.csv

--2026-01-16 16:33:29--  https://raw.githubusercontent.com/petlja/jupyterBookSrCyr/master/podaci/Top%2025%20YouTubers.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1153 (1.1K) [text/plain]
Saving to: ‘youtube-sub.csv’

youtube-sub.csv     100%[===================>]   1.13K  --.-KB/s    in 0s

2026-01-16 16:33:29 (81.1 MB/s) - ‘youtube-sub.csv’ saved [1153/1153]

In [115]:
import pandas as pd
df = pd.read_csv("./youtube-sub.csv" , sep=",")

In [116]:
df.head()

   RANK GRADE                        NAME  VIDEOS  SUBSCRIBERS       VIEWES
0     1   A++                    T-Series   13629    105783888  76945588449
1     2     A                   PewDiePie    3898     97853589  22298927681
2     3    A+             5-Minute Crafts    3341     58629572  14860695079
3     4   A++  Cocomelon - Nursery Rhymes     441     53163816  33519273951
4     5   A++                   SET India   31923     51784081  36464793233

In [117]:
df = df[["NAME","VIDEOS","SUBSCRIBERS","VIEWES"]]
df.head()

                         NAME  VIDEOS  SUBSCRIBERS       VIEWES
0                    T-Series   13629    105783888  76945588449
1                   PewDiePie    3898     97853589  22298927681
2             5-Minute Crafts    3341     58629572  14860695079
3  Cocomelon - Nursery Rhymes     441     53163816  33519273951
4                   SET India   31923     51784081  36464793233

In [118]:
from langchain_community.document_loaders import DataFrameLoader
llm_loader = DataFrameLoader(df , page_content_column="NAME")

In [119]:
llm_data = llm_loader.load()

In [120]:
llm_data

[Document(metadata={'VIDEOS': 13629, 'SUBSCRIBERS': 105783888, 'VIEWES': 76945588449}, page_content='T-Series'),
 Document(metadata={'VIDEOS': 3898, 'SUBSCRIBERS': 97853589, 'VIEWES': 22298927681}, page_content='PewDiePie'),
 Document(metadata={'VIDEOS': 3341, 'SUBSCRIBERS': 58629572, 'VIEWES': 14860695079}, page_content='5-Minute Crafts'),
 Document(metadata={'VIDEOS': 441, 'SUBSCRIBERS': 53163816, 'VIEWES': 33519273951}, page_content='Cocomelon - Nursery Rhymes'),
 Document(metadata={'VIDEOS': 31923, 'SUBSCRIBERS': 51784081, 'VIEWES': 36464793233}, page_content='SET India'),
 Document(metadata={'VIDEOS': 1100, 'SUBSCRIBERS': 50560964, 'VIEWES': 25446405744}, page_content='Canal KondZilla'),
 Document(metadata={'VIDEOS': 42404, 'SUBSCRIBERS': 46098586, 'VIEWES': 34085586984}, page_content='WWE'),
 Document(metadata={'VIDEOS': 134, 'SUBSCRIBERS': 45873439, 'VIEWES': 625649566}, page_content='Justin Bieber'),
 Document(metadata={'VIDEOS': 209, 'SUBSCRIBERS': 43796634, 'VIEWES': 8354321862}, page_content='Dude Perfect'),
 Document(metadata={'VIDEOS': 4406, 'SUBSCRIBERS': 41131131, 'VIEWES': 13175713909}, page_content='Badabun'),
 Document(metadata={'VIDEOS': 151, 'SUBSCRIBERS': 40883164, 'VIEWES': 17420235764}, page_content='Ed Sheeran'),
 Document(metadata={'VIDEOS': 4305, 'SUBSCRIBERS': 40675210, 'VIEWES': 18597258212}, page_content='Zee Music Company'),
 Document(metadata={'VIDEOS': 137, 'SUBSCRIBERS': 39549835, 'VIEWES': 3963774207}, page_content='HolaSoyGerman.'),
 Document(metadata={'VIDEOS': 117, 'SUBSCRIBERS': 38321579, 'VIEWES': 723182792}, page_content='EminemMusic'),
 Document(metadata={'VIDEOS': 323, 'SUBSCRIBERS': 36937062, 'VIEWES': 6495653129}, page_content='Marshmello'),
 Document(metadata={'VIDEOS': 128, 'SUBSCRIBERS': 36748165, 'VIEWES': 852378143}, page_content='Ariana Grande'),
 Document(metadata={'VIDEOS': 363, 'SUBSCRIBERS': 36059417, 'VIEWES': 2965932071}, page_content='whinderssonnunes'),
 Document(metadata={'VIDEOS': 1635, 'SUBSCRIBERS': 35648722, 'VIEWES': 9524890177}, page_content='JuegaGerman'),
 Document(metadata={'VIDEOS': 809, 'SUBSCRIBERS': 35324033, 'VIEWES': 7772447040}, page_content='elrubiusOMG'),
 Document(metadata={'VIDEOS': 166, 'SUBSCRIBERS': 34920060, 'VIEWES': 255089844}, page_content='Taylor Swift'),
 Document(metadata={'VIDEOS': 97, 'SUBSCRIBERS': 34416819, 'VIEWES': 361332307}, page_content='Katy Perry'),
 Document(metadata={'VIDEOS': 1872, 'SUBSCRIBERS': 33549096, 'VIEWES': 7458531306}, page_content='Felipe Neto'),
 Document(metadata={'VIDEOS': 122, 'SUBSCRIBERS': 33514535, 'VIEWES': 18873475304}, page_content='JustinBieberVEVO'),
 Document(metadata={'VIDEOS': 534, 'SUBSCRIBERS': 33378699, 'VIEWES': 7201866552}, page_content='Fernanfloo'),
 Document(metadata={'VIDEOS': 10542, 'SUBSCRIBERS': 33362512, 'VIEWES': 16519572219}, page_content='TheEllenShow')]

In [121]:
llm_data[5].dict()

/tmp/ipython-input-1977685222.py:1: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
  llm_data[5].dict()

{'id': None,
 'metadata': {'VIDEOS': 1100, 'SUBSCRIBERS': 50560964, 'VIEWES': 25446405744},
 'page_content': 'Canal KondZilla',
 'type': 'Document'}

#8.2 URL Loader

In [122]:
from langchain_community.document_loaders import UnstructuredURLLoader

In [123]:
urls = [
    "https://www.geeksforgeeks.org/courses/data-science-live",
    "https://prayertimes3.today/egypt-eg/alexandria-158.html"
]

In [124]:
llm_loader = UnstructuredURLLoader(urls = urls)
llm_data = llm_loader.load()

In [125]:
llm_data

[Document(metadata={'source': 'https://www.geeksforgeeks.org/courses/data-science-live'}, page_content='geeksforgeeks\n\nCourses\n\nGet 90% Refund\n\nTutorials\n\nInterview Prep\n\nAll Courses\n\nSelf-Paced\n\nData Science Project Based Learning\n\nSelf-Paced Course\n\n\n\ninterested count\n\n554k+ interested Geeks\n\nMaster Data Science and Machine Learning with this intensive project-first course by GeeksforGeeks. Learn Python, Statistics, Analytics, ML by completing industry-level projects. Build a Job-ready portfolio with Expert online classes.\n\n\n\nlevel\n\nBeginner to Advanced\n\n\n\ncourse duration\n\n24 Weeks\n\n\n\ninterested count\n\n554k+ interested Geeks\n\nBeginner FriendlyCourse CertificateIndustry ReadinessCapstone Projects\n\n\n\nwarning\n\nEnrol in this course today to be eligible for 90% Fee Refund!\n\nEnrol in this course today to be eligible for 90% Fee Refund!\n\nCourse Overview\n\nKey Highlights\n\nBeginner-friendly, end-to-end program covering Python, math, statistics, ML, Deep Learning, NLP, and Generative AI.\n\nOne year of self-paced access to premium recorded lectures, articles, assignments, and practice problems.\n\nIndustry-aligned tools & skills including Python, Pandas, NumPy, SQL, Power BI, web scraping, AI pipelines, and more.\n\nExpert guidance & doubt support with TA assistance, live sessions, and mentorship for resumes, LinkedIn, and placements.\n\nIdeal for beginners & career-switchers looking for a structured, practical, and flexible way to enter Data Science and AI.\n\nBuild Portfolio Ready Projects (21 Projects Included):\n\nTitanic Survival Prediction (ML)\n\nReal-Time Object Detection (DL)\n\nSmart OCR Bot for Document Automation\n\nDigit Recognizer from Scratch\n\nRead more\n\n\n\n\n\nCourse Content\n\n01Python for Data Science\n\nIntroducing Python - Python Basics, Operators, Loops, Functions, Strings, List, Tuples, Dictionary, Set, Object-oriented concepts (OOPs) and much more.\n\nData Toolkit - Getting started with Files, Inventory Management System with Files, Inventory Management System with JSON, Mastering Numpy Arrays, Getting Started with OS, Jupyter Notebook Setup, OS with Python, etc.\n\nLibraries - Numpy, Pandas, Matplotlib, Streamlit, etc.\n\n02Statistics\n\nLinear Algebra Essentials - Scalars, Vectors, Matrices, Matrix Operations, Inverse, Rank\n\nSystems of Equations & Eigen Concepts - Solving Linear Systems, Determinants, Eigenvalues & Eigenvectors\n\nVector Spaces & Norms - Dot Product, Norms, Distance Metrics\n\nCalculus Basics - Derivatives, Partial Derivatives, Chain Rule, Gradients\n\nOptimization - Gradient Descent, Cost Functions, Minima/Maxima\n\nMultivariable Calculus\n\n03Data Analytics\n\nData Analysis with Python - Getting started with Pandas, Data Preprocessing with Google Play Store, Introduction to EDA, Data Cleaning, Data Visualization, Data Analysis\n\nExcel - Exploring Data, Preparing Data, Analysing Data, Important Interview Questions\n\nPower BI - Introduction to Power BI, Understanding Parameters, Basic Plots, Fundamentals of Power BI, Designing the Plots, etc.\n\nWeb Scraping - Learn how to Scrape, Selenium, Image Dataset Creation, and much more\n\nSQL - Databases Fundamentals, SQL Fundamentals, Data Manipulation (DML), Querying, Intermediate SQL Queries, Joining and Combining Data, Set Theory Clauses, Subqueries, Window Functions, Data Preprocessing and Analysis\n\n04Machine Learning & AI\n\nIntroduction to AI - How Data Science Comes into Play\n\nRegression - Linear Regression, Multiple Linear Regression & Polynomial Linear Regression\n\nMachine Learning Algorithms - Support Vector Machines, Decision Trees, Random Forests, Classification Algorithms, Clustering Algorithms, Feature Engineering, and much more\n\nStatistical Foundation for ML - Descriptive & Inferential Statistics, Correlation & Covariance, Outlier Detection, Sampling Strategies, Statistical Bias & Variance, Central Limit Theorem\n\nWhat Sets Us Apart\n\n24 X 7 Doubt Support\n\n24 X 7 Doubt Support\n\nAI Chat Support for instant doubt resolution, plus a dedicated Teaching Assistant exclusively assigned to your batch.\n\nRecognised Certification\n\nRecognised Certification\n\nEarn an industry-recognized GeeksforGeeks Training Certificate for credible validation, career advancement, and lifetime\n\nPlacement Assistance\n\nPlacement Assistance\n\nGet end-to-end career support, Personalized Career Mapping, Tailored Job Opportunities, Resume & LinkedIn Optimization\n\nComplimentary Course\n\nComplimentary Course\n\nYou also get 21 Projects in 21 Days with daily ML and GenAI builds, ending with 21 portfolio-ready AI projects.\n\nCourse Benefits\n\nCourse Benefits\n\n1-year Access to the online Course materials and Premium Recorded videos\n\n\n\nUnable to load\n\n\n\nUnable to load\n\nPricing\n\nTestimonials\n\n\n\nquote\n\nThis course was instrumental in my journey to landing a job at Google. The curriculum is comprehensive and perfectly aligned with what top tech compan...\n\n\n\nAyush Deep\n\nAyush Deep\n\nPlaced at Google\n\n\n\nquote\n\nAs a newbie in the field of Data Science, Python, and Machine Learning, this course was extremely helpful to me in a variety of ways. First, it was so...\n\n\n\nEshant Das\n\nEshant Das\n\nPlaced at GeeksforGeeks\n\n\n\nquote\n\nProvides Simplified ML concepts and hands-on projects. Helped me to build consistency with the 90 day challenge. I would advise this course to anyone ...\n\n\n\nRaviKiran Kandegula\n\nRaviKiran Kandegula\n\nAchieved a fair understanding/hands-on with ML Algos and Data Handling.\n\n\n\nquote\n\n"The GeeksforGeeks ML course exceeded my expectations. The content is well-organized, and the instructors break down complex topics into manageable se...\n\n\n\nArjun Bhandari\n\nArjun Bhandari\n\nJust learning now, will become a Data Scientist in few months\n\n\n\nquote\n\nThis course helped me enhance my data analytics skills, enabling me to analyze large datasets effectively, derive meaningful insights, and make inform...\n\n\n\nSagar Patle\n\nSagar Patle\n\nGot Placed at Quantity kiosk Technology\n\n\n\nquote\n\nI found the course to be very informative and well-structured. The materials and resources provided were helpful and gave me a solid understanding of ...\n\n\n\nPrateek Singh\n\nPrateek Singh\n\nPlaced in Ericsson Global India Limited\n\nFrequently Asked Questions\n\n01\n\nWill I get 90% of my course fee back?\n\n\n\n\n\n02\n\nHow long will I get access to the online course material available with this course?\n\n\n\n\n\n03\n\nTotal Duration of the Course is ?\n\n\n\n\n\n04\n\nHow are the doubt sessions conducted?\n\n\n\n\n\n05\n\nWill I get internship certificate after completing this course ?\n\n\n\n\n\n06\n\nAre refunds offered for courses?\n\n\n\n\n\n07\n\nWhat are the prerequisites and required software/hardware?\n\n\n\n\n\n08\n\nCan I make the payment through PayPal?\n\n\n\n\n\nGeeksforGeeks\n\nlocation\n\nCorporate & Communications Address:\n\nA-143, 7th Floor, Sovereign Corporate Tower, Sector- 136, Noida, Uttar Pradesh (201305)\n\nlocation\n\nRegistered Address:\n\nK 061, Tower K, Gulshan Vivante Apartment, Sector 137, Noida, Gautam Buddh Nagar, Uttar Pradesh, 201305\n\nGFG App on Play Store\n\nGFG App on App Store\n\nAdvertise with us\n\nCompany\n\nAbout Us\n\nLegal\n\nPrivacy Policy\n\nCareers\n\nContact Us\n\nCorporate Solution\n\nCampus Training Program\n\nExplore\n\nPOTD\n\nPractice Problems\n\nConnect\n\nBlogs\n\n90% Refund on Courses\n\nTutorials\n\nProgramming Languages\n\nDSA\n\nWeb Technology\n\nAI, ML & Data Science\n\nDevOps\n\nCS Core Subjects\n\nGATE\n\nSchool Subjects\n\nSoftware and Tools\n\nCourses\n\nML and Data Science\n\nDSA and Placements\n\nWeb Development\n\nData Science\n\nProgramming Languages\n\nDevOps & Cloud\n\nGATE\n\nTrending Technologies\n\nOffline Centers\n\nNoida\n\nBengaluru\n\nPune\n\nHyderabad\n\nKolkata\n\nPreparation Corner\n\nInterview Corner\n\nAptitude\n\nPuzzles\n\nGfG 160\n\nSystem Design\n\n@GeeksforGeeks, Sanchhaya Education Private Limited, All rights reserved'),
 Document(metadata={'source': 'https://prayertimes3.today/egypt-eg/alexandria-158.html'}, page_content='adplus-dvertising\n\nمواعيد الاذان في الاسكندرية\n\nتوقيت مواعيد الصلاة في الاسكندرية حسب الوقت المحلي معرفة موعد صلاة الفجر الظهر العصر المغرب العشاء في الاسكندرية ومتى يتم رفع الاذان فيها.\n\nامساكية رمضان\n\nاضف الى موقعك\n\nPrivacy Policy\n\nاتصل بنا\n\nالصفحة الرئيسية\n\nمصر\n\nالاسكندرية\n\nمواقيت الصلاة في الاسكندرية اليوم\n\nمواعيد الصلاة في مدينة الاسكندرية، اليوم الجمعة بتاريخ 16 يناير, 2026 الموافق 27 رجب, 1447. هجري : 27 رجب, 1447 هـ ميلادي : 16 يناير, 2026 مـ التوقيت : 06:33:44 مساءً الصلاة القادمة عشاء يتبقى على رفع الاذان 00:17:16 ساعة فجر ظهر عصر مغرب عشاء 05:32 am 12:10 pm 03:02 pm 05:21 pm 06:51 pm أضف هذا التوقيت إلى موقعك\n\nقائمة المدن\n\nمواقيت الصلاة في الاسكندرية مواقيت الصلاة في اسوان مواقيت الصلاة في دمنهور مواقيت الصلاة في الفيوم مواقيت الصلاة في كفر الشيخ مواقيت الصلاة في المنيا مواقيت الصلاة في سوهاج مواقيت الصلاة في دمياط مواقيت الصلاة في بنها مواقيت الصلاة في الجيزة مواقيت الصلاة في الاقصر مواقيت الصلاة في بور سعيد مواقيت الصلاة في اسيوط مواقيت الصلاة في القاهرة مواقيت الصلاة في بني سويف مواقيت الصلاة في عين السخنة مواقيت الصلاة في الغردقة مواقيت الصلاة في مرسى مطروح مواقيت الصلاة في قنا مواقيت الصلاة في طنطا مواقيت الصلاة في الزقازيق مواقيت الصلاة في شرم الشيخ مواقيت الصلاة في المنوفية مواقيت الصلاة في الاسماعيلي مواقيت الصلاة في العريش مواقيت الصلاة في السويس\n\nمعلومات عن مدينة الإسكندرية\n\nتلقب الإسكندرية بلقب عروس البحر الأبيض المتوسط وهي عبارة عن عاصمة مصر الثانية، كما أنها كانت عاصمة البلاد تاريخياً ولها إطلاله على ساحل البحر الأبيض المتوسط على امتداد سبعين كيلو متراً في الشمال الغربي لدلتا النيل.\n\nلمدينة الإسكندرية حدود شمالية مع البحر المتوسط وجنوبية مع بحيرة مريوط إلى حدود الكيلو رقم 71 على الطريق الصحراوي القاهرة - الإسكندرية، كما أن لها حدود شرقية مع مدينة إدكو وخليج أبو قير، وغربية مع منطقة سيدي كرير إلى حدود الكيلو رقم 63.30 على الطريق السريع الإسكندرية - مطروح.\n\nتتميز مدينة الإسكندرية بوجود العديد من المعالم الرائعة كما أنها تحتوي على ميناء الدخيلة وميناء الإسكندرية وهما من بين أكبر الموانئ البحرية في جمهورية مصر العربية ولذلك فإن نحو 80 بالمائة من مجموع الصادرات والواردات تمر عبر المدينة.\n\nكما تحتوي على مكتبة الإسكندرية الجديدة وهي مكتبة ضخمة بامتياز وتحتوي على ما يناهز ثمانية ملايين كتاب بالإضافة إلى عدة مواقع أثرية ومتاحف على غرار عمود السواري وقلعة قايتباي وغيرها.\n\nوحسب التعداد السكاني لسنة 2006 فقد بلغ عدد سكان مدينة الإسكندرية نحو أربعة ملايين و123 ألف نسمة وجلهم يشتغلون في القطاع الزراعي والصناعي والتجاري، كما تتكون مدينة الإسكندرية من نحو سبعة أحياء مقسمة إدارياً.\n\nقائمة الدول\n\n\n\nمواعيد الصلاة في اليمن\n\n\n\nمواعيد الصلاة في السعودية\n\n\n\nمواعيد الصلاة في الإمارات\n\n\n\nمواعيد الصلاة في البحرين\n\n\n\nمواعيد الصلاة في قطر\n\n\n\nمواعيد الصلاة في الكويت\n\n\n\nمواعيد الصلاة في عمان\n\n\n\nمواعيد الصلاة في سوريا\n\n\n\nمواعيد الصلاة في ليبيا\n\n\n\nمواعيد الصلاة في فلسطين\n\n\n\nمواعيد الصلاة في المغرب\n\n\n\nمواعيد الصلاة في السودان\n\n\n\nمواعيد الصلاة في لبنان\n\n\n\nمواعيد الصلاة في العراق\n\n\n\nمواعيد الصلاة في الأردن\n\n\n\nمواعيد الصلاة في تونس\n\n\n\nمواعيد الصلاة في الجزائر\n\n\n\nمواعيد الصلاة في مصر\n\n\n\nمواعيد الصلاة في امريكا\n\n\n\nمواعيد الصلاة في بريطانيا\n\n\n\nمواعيد الصلاة في ايطاليا\n\n\n\nمواعيد الصلاة في فرنسا\n\n\n\nمواعيد الصلاة في اسبانيا\n\n\n\nمواعيد الصلاة في الهند\n\n\n\nمواعيد الصلاة في تركيا\n\n\n\nمواعيد الصلاة في روسيا\n\n\n\nمواعيد الصلاة في كندا\n\n\n\nمواعيد الصلاة في المانيا\n\n\n\nمواعيد الصلاة في ماليزيا\n\n\n\nمواعيد الصلاة في النرويج\n\n\n\nمواعيد الصلاة في السويد\n\n\n\nمواعيد الصلاة في الفلبين\n\n\n\nمواعيد الصلاة في الصين\n\n\n\nمواعيد الصلاة في جورجيا\n\n\n\nمواعيد الصلاة في هولندا\n\n\n\nمواعيد الصلاة في اوكرانيا\n\n')]

#8.3 Wikipedia Loader

In [126]:
from langchain_community.document_loaders import WikipediaLoader
query = "Mohamed Salah"
llm_data = WikipediaLoader(
    query = query,
    load_max_docs = 3,
    doc_content_chars_max = 20_000).load()

In [127]:
len(llm_data)

3

In [128]:
llm_data[0].page_content

'Mohamed Salah Hamed Mahrous Ghaly (born 15 June 1992) is an Egyptian professional footballer who plays as a right winger or right midfielder for Premier League club Liverpool and captains the Egypt national team. He is widely regarded as one of the best players of his generation and one of the greatest wingers of all time. He is the all-time top foreign goalscorer in the Premier League and the all-time top African goalscorer in the UEFA Champions League.\nSalah began his senior career in 2010 at Al-Mokawloon, departing in 2012 to join Basel, where he won two Swiss Super League titles. In 2014, he joined Chelsea for a reported fee of £11 million, but limited gametime led to successive loans to Fiorentina and Roma, who later signed him permanently for €15 million. In the 2016–17 season, Salah was a key figure in Roma\'s unsuccessful title bid, reaching double figures in both goals and assists. In 2017, Salah moved to Liverpool for £36.9 million, a club record at the time. In his first season, he set the record for most Premier League goals scored (32) in a 38-game season and helped Liverpool to the 2018 Champions League final. Having formed a formidable attacking trio with Roberto Firmino and Sadio Mané, Salah went on to be an integral player in the club\'s Champions League and Premier League title successes in the following two seasons. He has since also won the FA Cup, EFL Cup, FA Community Shield, UEFA Super Cup and the FIFA Club World Cup. In the 2024–25 season, he won a second league title while breaking the record for the most goal contributions in a 38 game Premier League campaign. For his performances during the season, he won the PFA Players\' Player of the Year award for a record-breaking third time.\nSalah\'s other individual accolades include three FWA Footballer of the Year awards, four Premier League Golden Boots, two Premier League Player of the Season awards, two Premier League Playmaker of the Season awards, finished third for the Best FIFA Men\'s Player in 2018 and 2021, and finished fourth in the 2025 Ballon d\'Or, respectively. He received the 2018 FIFA Puskás Award for his winning strike in the first Merseyside derby of the 2017–18 season. In 2023, Salah became Liverpool\'s all-time top goalscorer in the history of the Premier League, and also became the fifth player to score 200 goals for the club. In 2025, he became Liverpool\'s third-highest goalscorer in the club\'s history behind Roger Hunt and Ian Rush.\nAt international level, Salah represented Egypt at youth level before making his senior debut in 2011. Following his performances at the 2012 Summer Olympics, he was named CAF Most Promising African Talent of the Year. Since then, he finished as runner-up in the 2017 and 2021 Africa Cup of Nations, and was top scorer during CAF qualification as Egypt qualified for the 2018 FIFA World Cup. Salah was named CAF African Footballer of the Year (2017 and 2018), BBC African Footballer of the Year (2017 and 2018), and was selected in the 2017 Africa Cup of Nations Team of the Tournament, 2021 Africa Cup of Nations Team of the Tournament and the CAF Team of the Year on several occasions.\nSalah is regarded as a symbol of national pride in Egypt for his achievements and was named in theTime magazine\'s list of the 100 Most Influential People in 2019. Salah has also been credited for raising the profile of Liverpool among Egyptians.\n\n\n== Club career ==\n\n\n=== Al Mokawloon ===\nSalah started out playing for the youth setups of local teams Ittihad Basyoun and Othmason Tanta. He names Ronaldo, Zinedine Zidane and Francesco Totti as his childhood idols. In 2006, he joined the youth team of Al Mokawloon Al Arab aged 14 after being spotted by a scout who had originally come to watch another child play but was distracted by Salah. Salah frequently had to miss school to make the three-hour journey to training. When Salah was 15 he was noticed by first-team manager Mohamed Radwan, who moved him to the first-team squad immediately. Salah had to be given a special diet and training program due to his muscles not being fully formed because of his young age.\nSalah made his first-team debut on 3 May 2010 in the Egyptian Premier League, coming on as a substitute in a 1–1 away draw against El Mansoura. During the 2010–11 season Salah continued earning minutes on the pitch, eventually becoming a regular in the team. Even though he was getting regular game time, Salah struggled to score. In the dressing room after matches he would sometimes be in tears because of this, and Radwan says it only motivated him to become better. He scored his first goal for them on 25 December 2010 in a 1–1 away draw against Al Ahly. He remained a regular for Al Mokawloon, appearing in every game of the 2011–12 season. Following the Port Said Stadium riot on 1 February 2012, the Egyptian Premier League was suspended, and on 10 March, the Egyptian Football Association announced their decision to cancel the remainder of the season.\n\n\n=== Basel ===\n\n\n==== 2012–2013: Development and breakthrough ====\n\nSwiss Super League club Basel had been monitoring Salah for some time, so following the Egyptian Premier League suspension, the club organised a friendly match with the Egypt national under-23 team. The match took place on 16 March at the Stadion Rankhof in Basel, and despite only playing the second half, Salah scored twice, helping the Egyptians to a 4–3 win. Basel subsequently invited Salah to remain in the city for a week\'s training. On 10 April 2012, it was announced that Salah had signed for Basel on a four-year contract starting from 15 June 2012. He initially found it difficult to settle, having arrived unable to speak the language and been signed as a replacement for Xherdan Shaqiri. Salah scored on his unofficial debut on 23 June 2012 against FCSB during a friendly match, a 4–2 defeat. He made his official Basel debut in a UEFA Champions League preliminary stage match against the Norwegian club Molde on 8 August, coming on as a substitute in the 74th minute. He made his league debut on 12 August against Thun, playing the full match.\nHe scored his first league goal a week later, the second goal in a 2–0 home win against Lausanne-Sport. Salah scored his first UEFA Europa League goal in the quarter-finals on 11 April 2013, as Basel advanced to the semi-finals by beating Tottenham Hotspur 4–1 in a penalty shoot-out after a 4–4 aggregate draw. In the semi-final on 2 May, Salah scored away to Chelsea, although Basel were beaten 5–2 on aggregate. Despite late disappointment in Europe, Basel won the 2012–13 Swiss Super League title and finished runners-up in the Swiss Cup.\n\n\n==== 2013–2014: Final season and league championship ====\nAhead of the 2013–14 Swiss Super League season, Salah was a member of the Basel team that won the 2013 Uhrencup. Salah scored in his first league appearance of the season against Aarau on 13 July 2013. He scored his first Champions League goal a month later against Maccabi Tel Aviv on 6 August 2013 in the third qualifying round. Salah was the subject of major controversy following the game, after he appeared to deliberately avoid shaking hands with the players of the Israeli club in both the home and away legs.\nHe scored twice against the Bulgarian league champions PFC Ludogorets Razgrad on 21 August 2013 in the play-off round. On 18 September 2013, Salah scored the equaliser against Chelsea in the 2–1 away win during the group stage. During the return tie on 26 November at St. Jakob-Park, Salah scored the winning goal as Basel beat Chelsea for the second time with a 1–0 home win. However, he was unable to prevent Basel being eliminated in the group stage.\nOn the domestic stage, Salah continued to perform. Scoring four goals in 18 games, including a double against title rivals Young Boys, he helped Basel win the league title for the fifth time in a row.\nOn 23 January 2014, it was announced that Salah would leave Basel. During his time with the club, Salah played a total of 79 games for Basel, scoring a total of 20 goals. 47 of these games were in the Swiss Super League, six in the Swiss Cup, and 26 in UEFA competitions (Champions League and Europa League). He scored nine goals in the domestic league, four in the cup, and seven in European matches.\n\n\n=== Chelsea ===\n\n\n==== 2014 ====\nOn 23 January 2014, Premier League club Chelsea announced that a deal had been agreed with Basel to sign Salah for a fee reported to be in the region of £11 million. Three days later the transfer was completed, making him the first Egyptian to sign for the London-based club. Liverpool had been interested in Salah, and had made an offer of £11 million but were beaten to his signature by Chelsea.\nOn 8 February, Salah made his debut for Chelsea in the Premier League, coming on as a substitute in the 3–0 win over Newcastle United. Seven games later, on 22 March, Salah scored his first goal for Chelsea against Arsenal in the London derby, coming on as a substitute for Oscar, in a match which ended as a 6–0 home win. Then, on 5 April, Salah opened the scoring and later won a penalty and assisted the third goal in Chelsea\'s 3–0 win over Stoke City.\n\n\n==== 2014–2015 ====\n\nBefore the 2014–15 season, Salah\'s future with Chelsea looked to be in doubt after reports suggested he could be forced to return to Egypt to carry out military service after his registration for an education scheme was rescinded by the Egyptian Minister of Higher Education. He was spared from military service after a meeting with Egyptian prime minister Ibrahim Mahlab, the Minister of Higher Education, and the Egypt national team manager Shawky Gharieb. Salah changed squad numbers from 15 to 17 for the start of the season, with his new number having been vacated by Eden Hazard changing to number 10.\nSalah was rarely used during the season, making just three Premier League, two Champions League and three cup appearances, failing to score in any of them. On 28 October 2014, after a poor performance in a 2–1 win away to League Two team Shrewsbury Town in the fourth round of the League Cup, he and fellow winger André Schürrle were criticised publicly by manager José Mourinho. Although Salah only made three league appearances before his loan move to Fiorentina, Mourinho stated that he would receive a replica winner\'s medal from the club for his contributions that season.\n\n\n==== 2015: Loan to Fiorentina ====\n\nOn the transfer deadline day, 2 February 2015, Chelsea confirmed that Salah would join Italian club Fiorentina on an 18-month loan until the end of the 2015–16 season, as part of a transfer deal which saw Juan Cuadrado moving in the opposite direction. Six days after signing, he made his debut coming off the bench in the 65th minute as a replacement for Joaquín in a 3–2 home victory against Atalanta in Serie A. Salah chose the number 74 shirt in honour of the victims of the Port Said Stadium riot.\nSalah made his first start for Fiorentina on 14 February against Sassuolo, scoring his first goal for the club in the 30th minute. He then provided an assist to Khouma Babacar just two minutes after scoring; the match ended in a 3–1 win for Fiorentina. Twelve days later, Salah scored his first European goal for Fiorentina, as his side advanced to the round of sixteen of the Europa League, beating Tottenham 3–1 on aggregate. Salah scored the winning goal for Fiorentina against Inter Milan on 1 March, his third goal in Serie A. Four days after that, Salah scored both of Fiorentina\'s goals in their 2–1 win away to Juventus in the Coppa Italia semi-final first leg. At the end of the season, Fiorentina activated an option to make the loan move permanent, but Salah refused the move. Even though the loan agreement was for 18 months, Salah refused to return to Fiorentina and instead joined fellow Serie A club Roma. On 11 September, Fiorentina filed a complaint to FIFA, claiming that Chelsea had breached the agreed contract when they allowed Salah to join Roma on loan. The Court of Arbitration for Sport cleared Salah and Chelsea of any wrongdoing.\n\n\n==== 2015–2016: Loan to Roma ====\nOn 6 August 2015, Salah joined Roma on a season-long loan for €5 million; with the option to make the deal permanent, for a reported €15 million. He wore the number 11 shirt. He made his debut on 22 August, as the new season began with a 1–1 draw away Hellas Verona. On 20 September, Salah scored his first goal of the season against Sassuolo to help Roma salvage a point as the match ended in a 2–2 draw. He went on to score in his following two matches, a 2–1 loss against Sampdoria and a 5–1 win against Carpi. On 25 October, Salah scored the opener against his former club Fiorentina in a 2–1 away victory to help earn a fourth straight league win for Roma. On his return, Salah was also sent off after picking up a second yellow in the closing minutes of the match, just seconds after picking up his first yellow. On 4 November, he scored the opening goal of a 3–2 Champions League win over Bayer Leverkusen.\nOn 4 March, he faced his former side Fiorentina again and scored another double as Roma won 4–1 and broke into the top three. Salah would go onto score another three goals that season, scoring against Bologna, Genoa, and AC Milan, the latter on the final day. In the 2015–16 season, Salah scored 15 goals in 42 matches as Roma finished in third place in Serie A and qualified for the Champions League. In June, it was announced that Salah won the club\'s 2015–16 Player of the Season award.\n\n\n=== Roma ===\n\n\n==== 2016–2017: Permanent transfer, Serie A runner-up ====\nOn 3 August 2016, Roma announced the signing of Salah on a permanent deal for €15 million. He scored his first goal of the season in a 4–0 win over Udinese in the opening game of the season on 20 August. On 6 November, Salah scored a hat-trick in a 3–0 win over Bologna, his first club career hat-trick. However, a ruptured ankle ligament kept him out for the first half of December. He returned as a half-time substitute in a 1–0 defeat against title rivals Juventus on 17 December. Salah then endured a two-month period without a goal, he broke his drought on 19 February, scoring against Torino in a 4–1 win. On 9 March, he scored Roma\'s opening goal in an eventual 4–2 defeat to Lyon in the first leg of the round of sixteen in the 2016–17 Europa League. Despite winning the second leg 2–1, they were unable to turn the tie around and were knocked out 5–4 on aggregate. On 28 May, in the final game of the season, Salah was substituted for captain Francesco Totti, who was playing his final game with the club, in a 3–2 win over Genoa. Roma finished the season in second, just four points behind champions Juventus. Salah scored 19 goals in all competitions.\n\n\n=== Liverpool ===\n\n\n==== 2017–2018: Record-breaking individual success ====\n\nOn 22 June 2017, Salah agreed a transfer to Premier League club Liverpool. He signed a long-term contract with the Reds for an initial £36.5m fee that could rise to £43m. The fee was a club record, eclipsing the £35m spent on Andy Carroll in 2011. He was assigned the number 11 shirt previously worn by Roberto Firmino who instead switched to number 9. He joined the club on 1 July upon the opening of the summer transfer window, becoming Liverpool\'s first Egyptian player, and scored on his Premier League debut against Watford in a 3–3 away draw on 12 August. On 24 August, Salah scored his second goal for Liverpool, in a 2017–18 Champions League play-off round 4–2 win (6–3 agg) against 1899 Hoffenheim, his first goal at Anfield. Three days later, Salah scored and assisted a goal in a 4–0 victory over Arsenal. For his performances in August, Salah was awarded Player of the Month by Liverpool supporters. On 17 October, Salah netted twice in a 7–0 Champions League win over Maribor, helping Liverpool to the joint-largest ever away win in the competition, and the largest away win by an English club.\n\nOn 26 November 2017, Salah scored the opener and refused to celebrate in a 1–1 home draw with his former team Chelsea out of respect for the club as well as victims of the Sinai mosque attack two days earlier. Salah rose the top of the Premier League goalscoring charts by scoring twice after coming on as a substitute away at Stoke City on 29 November in a 3–0 win. The following month, Salah netted in a 4–0 win over Bournemouth; a result which saw Liverpool become the first team in Premier League history to win four consecutive away league matches by a margin of at least three goals. In the process, he also became the joint-second fastest player to reach 20 goals for Liverpool on his 26th appearance, behind George Allan who reached the milestone in 19 appearances in 1895. On 17 March 2018, Salah scored four goals in a 5–0 win over Watford, which was his first hat-trick for Liverpool. In this game, he also broke a record of scoring 36 times in his debut season for Liverpool, and also became the leading goalscorer in Europe\'s top five leagues – overtaking Barcelona\'s Lionel Messi and Tottenham striker Harry Kane. Following Salah\'s record-breaking goal exploits former Liverpool captain Steven Gerrard stated "we are witnessing the start of greatness".\nIn early April 2018, he scored in both Champions League quarter-final matches against Manchester City to help his side advance. On 22 April 2018, Salah was awarded the PFA Players\' Player of the Year award, having earlier been named in the PFA Team of the Year for the Premier League. Two days later, he scored a brace in a 5–2 Champions League semi-final first leg win over former club, Roma. In doing so, he simultaneously became the first player from Africa and the first Liverpool player to score 10 goals in a single campaign in the tournament. His double also took him to 43 goals for the season across all competitions, surpassing Roger Hunt\'s tally of 42, and making him Liverpool\'s second-highest goalscorer in a single season, behind Ian Rush. He had previously also broken the club\'s record for the Premier League era, surpassing Robbie Fowler\'s total of 36 goals set in the 1995–96 campaign, and Fernando Torres\' record of 33 for the most goals by a Liverpool player in a debut season. After his two goals and assists in the first leg against Roma, Salah featured in the second leg as Liverpool beat the Italian club 7–6 on aggregate to qualify for the final for the first time in eleven years. He would then become the Premier League\'s all-time goalscorer for a 38-game season, registering his 32nd league goal in a 4–0 win against Brighton & Hove Albion en route to being awarded the Premier League Golden Boot.\nIn the 2018 Champions League final against Real Madrid, Salah injured his left shoulder in the 30th minute after a challenge by Madrid defender Sergio Ramos. After initially carrying on, he left the field in tears after going to ground again; the match ended in a 3–1 defeat. The Egyptian FA stated that this would have no effect on his availability for the 2018 FIFA World Cup in Russia, and that Salah would still be named in the team\'s final squad on 4 June. The day after the match, Ramos wrote a message and sent him good wishes.\n\n\n==== 2018–2019: European champion and second Golden Boot ====\n\nOn 2 July 2018, Salah signed a new long-term contract with Liverpool. Manager Jürgen Klopp said the news was important as a statement of intent in terms of Liverpool\'s status in the football world in having Salah commit himself further to the club. On 12 August, Salah scored Liverpool\'s first goal of the season, in a 4–0 home win over West Ham United. On 30 August, Salah was named on the three-man shortlist for the UEFA Men\'s Player of the Year, coming in third place, and was also included on the three-man shortlist for the UEFA Forward of the Season, coming in second place. On 3 September he was named on the three-man shortlist for the Bes

In [129]:
llm_data[0].metadata

{'title': 'Mohamed Salah',
 'summary': "Mohamed Salah Hamed Mahrous Ghaly (born 15 June 1992) is an Egyptian professional footballer who plays as a right winger or right midfielder for Premier League club Liverpool and captains the Egypt national team. He is widely regarded as one of the best players of his generation and one of the greatest wingers of all time. He is the all-time top foreign goalscorer in the Premier League and the all-time top African goalscorer in the UEFA Champions League.\nSalah began his senior career in 2010 at Al-Mokawloon, departing in 2012 to join Basel, where he won two Swiss Super League titles. In 2014, he joined Chelsea for a reported fee of £11 million, but limited gametime led to successive loans to Fiorentina and Roma, who later signed him permanently for €15 million. In the 2016–17 season, Salah was a key figure in Roma's unsuccessful title bid, reaching double figures in both goals and assists. In 2017, Salah moved to Liverpool for £36.9 million, a club record at the time. In his first season, he set the record for most Premier League goals scored (32) in a 38-game season and helped Liverpool to the 2018 Champions League final. Having formed a formidable attacking trio with Roberto Firmino and Sadio Mané, Salah went on to be an integral player in the club's Champions League and Premier League title successes in the following two seasons. He has since also won the FA Cup, EFL Cup, FA Community Shield, UEFA Super Cup and the FIFA Club World Cup. In the 2024–25 season, he won a second league title while breaking the record for the most goal contributions in a 38 game Premier League campaign. For his performances during the season, he won the PFA Players' Player of the Year award for a record-breaking third time.\nSalah's other individual accolades include three FWA Footballer of the Year awards, four Premier League Golden Boots, two Premier League Player of the Season awards, two Premier League Playmaker of the Season awards, finished third for the Best FIFA Men's Player in 2018 and 2021, and finished fourth in the 2025 Ballon d'Or, respectively. He received the 2018 FIFA Puskás Award for his winning strike in the first Merseyside derby of the 2017–18 season. In 2023, Salah became Liverpool's all-time top goalscorer in the history of the Premier League, and also became the fifth player to score 200 goals for the club. In 2025, he became Liverpool's third-highest goalscorer in the club's history behind Roger Hunt and Ian Rush.\nAt international level, Salah represented Egypt at youth level before making his senior debut in 2011. Following his performances at the 2012 Summer Olympics, he was named CAF Most Promising African Talent of the Year. Since then, he finished as runner-up in the 2017 and 2021 Africa Cup of Nations, and was top scorer during CAF qualification as Egypt qualified for the 2018 FIFA World Cup. Salah was named CAF African Footballer of the Year (2017 and 2018), BBC African Footballer of the Year (2017 and 2018), and was selected in the 2017 Africa Cup of Nations Team of the Tournament, 2021 Africa Cup of Nations Team of the Tournament and the CAF Team of the Year on several occasions.\nSalah is regarded as a symbol of national pride in Egypt for his achievements and was named in theTime magazine's list of the 100 Most Influential People in 2019. Salah has also been credited for raising the profile of Liverpool among Egyptians.",
 'source': 'https://en.wikipedia.org/wiki/Mohamed_Salah'}

#8.4 PDF Loader

In [130]:
!wget -O coc_deepseek.pdf https://arxiv.org/pdf/2510.18234

--2026-01-16 16:33:53--  https://arxiv.org/pdf/2510.18234
Resolving arxiv.org (arxiv.org)... 151.101.195.42, 151.101.67.42, 151.101.131.42, ...
Connecting to arxiv.org (arxiv.org)|151.101.195.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7631170 (7.3M) [application/pdf]
Saving to: ‘coc_deepseek.pdf’

coc_deepseek.pdf    100%[===================>]   7.28M  --.-KB/s    in 0.05s

2026-01-16 16:33:53 (139 MB/s) - ‘coc_deepseek.pdf’ saved [7631170/7631170]

In [131]:
from langchain_community.document_loaders import PyPDFLoader
llm_loader = PyPDFLoader("./coc_deepseek.pdf")
pages = llm_loader.load_and_split()

In [132]:
len(pages)

22

In [133]:
pages[6]

Document(metadata={'producer': 'pikepdf 8.15.1', 'creator': 'arXiv GenPDF (tex2pdf:e76afa9)', 'creationdate': '', 'author': 'Haoran Wei; Yaofeng Sun; Yukun Li', 'doi': 'https://doi.org/10.48550/arXiv.2510.18234', 'license': 'http://creativecommons.org/licenses/by/4.0/', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.28 (TeX Live 2025) kpathsea version 6.4.1', 'title': 'DeepSeek-OCR: Contexts Optical Compression', 'trapped': '/False', 'arxivid': 'https://arxiv.org/abs/2510.18234v1', 'source': './coc_deepseek.pdf', 'total_pages': 22, 'page': 6, 'page_label': '7'}, page_content='Dynamic resolution can be composed of two native resolutions. For example, Gundam\nmode consists of n×640×640 tiles (local views) and a 1024×1024 global view. The tiling method\nfollowing InternVL2.0 [8]. Supporting dynamic resolution is mainly for application considera-\ntions, especially for ultra-high-resolution inputs (such as newspaper images). Tiling is a form of\nsecondary window attention that can effectively reduce activation memory further. It’s worth\nnoting that due to our relatively large native resolutions, images won’t be fragmented too much\nunder dynamic resolution (the number of tiles is controlled within the range of 2 to 9). The\nvision token number output by the DeepEncoder under Gundam mode is: 𝑛× 100 + 256, where\n𝑛 is the number of tiles. For images with both width and height smaller than 640, 𝑛 is set to 0,\ni.e., Gundam mode will degrade to Base mode.\nGundam mode is trained together with the four native resolution modes to achieve the goal\nof one model supporting multiple resolutions. Note that Gundam-master mode (1024×1024 local\nviews+1280×1280 global view) is obtained through continued training on a trained DeepSeek-\nOCR model. This is mainly for load balancing, as Gundam-master’s resolution is too large and\ntraining it together would slow down the overall training speed.\n3.3. The MoE Decoder\nOur decoder uses the DeepSeekMoE [19, 20], specifically DeepSeek-3B-MoE. During inference,\nthe model activates 6 out of 64 routed experts and 2 shared experts, with about 570M activated\nparameters. The 3B DeepSeekMoE is very suitable for domain-centric (OCR for us) VLM\nresearch, as it obtains the expressive capability of a 3B model while enjoying the inference\nefficiency of a 500M small model.\nThe decoder reconstructs the original text representation from the compressed latent vision\ntokens of DeepEncoder as:\n𝑓dec :R 𝑛×𝑑 latent →R 𝑁×𝑑 text; ˆX=𝑓 dec(Z)where𝑛≤𝑁(2)\nwhereZ ∈R 𝑛×𝑑 latent are the compressed latent(vision) tokens from DeepEncoder and ˆX∈R 𝑁×𝑑 text\nis the reconstructed text representation. The function 𝑓dec represents a non-linear mapping\nthat can be effectively learned by compact language models through OCR-style training. It\nis reasonable to conjecture that LLMs, through specialized pretraining optimization, would\ndemonstrate more natural integration of such capabilities.\n3.4. Data Engine\nWe constructe complex and diverse training data for DeepSeek-OCR, including OCR 1.0 data,\nwhich mainly consists of traditional OCR tasks such as scene image OCR and document OCR;\nOCR 2.0 data, which mainly includes parsing tasks for complex artificial images, such as\ncommon charts, chemical formulas, and plane geometry parsing data; General vision data,\nwhich is mainly used to inject certain general image understanding capabilities into DeepSeek-\nOCR and preserve the general vision interface.\n3.4.1. OCR 1.0 data\nDocument data is the top priority for DeepSeek-OCR. We collect 30M pages of diverse PDF\ndata covering about 100 languages from the Internet, with Chinese and English accounting for\napproximately 25M and other languages accounting for 5M. For this data, we create two types\nof ground truth: coarse annotations and fine annotations. Coarse annotations are extracted\n7')

In [134]:
pages[6].page_content

'Dynamic resolution can be composed of two native resolutions. For example, Gundam\nmode consists of n×640×640 tiles (local views) and a 1024×1024 global view. The tiling method\nfollowing InternVL2.0 [8]. Supporting dynamic resolution is mainly for application considera-\ntions, especially for ultra-high-resolution inputs (such as newspaper images). Tiling is a form of\nsecondary window attention that can effectively reduce activation memory further. It’s worth\nnoting that due to our relatively large native resolutions, images won’t be fragmented too much\nunder dynamic resolution (the number of tiles is controlled within the range of 2 to 9). The\nvision token number output by the DeepEncoder under Gundam mode is: 𝑛× 100 + 256, where\n𝑛 is the number of tiles. For images with both width and height smaller than 640, 𝑛 is set to 0,\ni.e., Gundam mode will degrade to Base mode.\nGundam mode is trained together with the four native resolution modes to achieve the goal\nof one model supporting multiple resolutions. Note that Gundam-master mode (1024×1024 local\nviews+1280×1280 global view) is obtained through continued training on a trained DeepSeek-\nOCR model. This is mainly for load balancing, as Gundam-master’s resolution is too large and\ntraining it together would slow down the overall training speed.\n3.3. The MoE Decoder\nOur decoder uses the DeepSeekMoE [19, 20], specifically DeepSeek-3B-MoE. During inference,\nthe model activates 6 out of 64 routed experts and 2 shared experts, with about 570M activated\nparameters. The 3B DeepSeekMoE is very suitable for domain-centric (OCR for us) VLM\nresearch, as it obtains the expressive capability of a 3B model while enjoying the inference\nefficiency of a 500M small model.\nThe decoder reconstructs the original text representation from the compressed latent vision\ntokens of DeepEncoder as:\n𝑓dec :R 𝑛×𝑑 latent →R 𝑁×𝑑 text; ˆX=𝑓 dec(Z)where𝑛≤𝑁(2)\nwhereZ ∈R 𝑛×𝑑 latent are the compressed latent(vision) tokens from DeepEncoder and ˆX∈R 𝑁×𝑑 text\nis the reconstructed text representation. The function 𝑓dec represents a non-linear mapping\nthat can be effectively learned by compact language models through OCR-style training. It\nis reasonable to conjecture that LLMs, through specialized pretraining optimization, would\ndemonstrate more natural integration of such capabilities.\n3.4. Data Engine\nWe constructe complex and diverse training data for DeepSeek-OCR, including OCR 1.0 data,\nwhich mainly consists of traditional OCR tasks such as scene image OCR and document OCR;\nOCR 2.0 data, which mainly includes parsing tasks for complex artificial images, such as\ncommon charts, chemical formulas, and plane geometry parsing data; General vision data,\nwhich is mainly used to inject certain general image understanding capabilities into DeepSeek-\nOCR and preserve the general vision interface.\n3.4.1. OCR 1.0 data\nDocument data is the top priority for DeepSeek-OCR. We collect 30M pages of diverse PDF\ndata covering about 100 languages from the Internet, with Chinese and English accounting for\napproximately 25M and other languages accounting for 5M. For this data, we create two types\nof ground truth: coarse annotations and fine annotations. Coarse annotations are extracted\n7'

In [135]:
pages[6].metadata

{'producer': 'pikepdf 8.15.1',
 'creator': 'arXiv GenPDF (tex2pdf:e76afa9)',
 'creationdate': '',
 'author': 'Haoran Wei; Yaofeng Sun; Yukun Li',
 'doi': 'https://doi.org/10.48550/arXiv.2510.18234',
 'license': 'http://creativecommons.org/licenses/by/4.0/',
 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.28 (TeX Live 2025) kpathsea version 6.4.1',
 'title': 'DeepSeek-OCR: Contexts Optical Compression',
 'trapped': '/False',
 'arxivid': 'https://arxiv.org/abs/2510.18234v1',
 'source': './coc_deepseek.pdf',
 'total_pages': 22,
 'page': 6,
 'page_label': '7'}

#8.6 Directories Loader (txt)

In [140]:
from langchain_community.document_loaders import DirectoryLoader
llm_loader = DirectoryLoader("./md-data",
                             glob = "*.txt",
                             show_progress = True)

In [141]:
llm_data = llm_loader.load()

0it [00:00, ?it/s]

In [142]:
llm_data

[]

#8.7 Directories Loader (PDF)

In [146]:
from langchain_community.document_loaders import PyPDFDirectoryLoader
llm_loader = PyPDFDirectoryLoader("papers")
llm_data = llm_loader.load()

In [145]:
print(len(llm_data))
print(llm_data[2].page_content[:30])
print(llm_data[3].metadata)

0

IndexError: list index out of range

#9. Text Splitter

In [147]:
# Example
from langchain_community.document_loaders import WikipediaLoader

query_1 = "Nikola Tesla"
docs_1 = WikipediaLoader(
    query = query_1,
    load_max_docs = 1,
    doc_content_chars_max = 20_000).load()

document_1 = docs_1[0].page_content

query_2 = "Thomas Edison"
docs_2 = WikipediaLoader(
    query = query_2,
    load_max_docs = 1,
    doc_content_chars_max = 20_000
).load()
document_2 = docs_2[0].page_content


documents = [document_1 , document_2]
metadatas =[{"document":query_1},{"document":query_2}]

In [148]:
len(docs_1)

1

In [149]:
print(docs_1[0].page_content)

Nikola Tesla (10 July 1856 – 7 January 1943) was a Serbian-American engineer, futurist, and inventor. He is known for his contributions to the design of the modern alternating current (AC) electricity supply system.
Born and raised in the Austrian Empire, Tesla first studied engineering and physics in the 1870s without receiving a degree. He then gained practical experience in the early 1880s working in telephony and at Continental Edison in the new electric power industry. In 1884, he migrated to the United States, where he became a naturalized citizen. He worked for a short time at the Edison Machine Works in New York City before he struck out on his own. With the help of partners to finance and market his ideas, Tesla set up laboratories and companies in New York to develop a range of electrical and mechanical devices. His AC induction motor and related polyphase AC patents, licensed by Westinghouse Electric in 1888, earned him a considerable amount of money and became the cornerstone of the polyphase system, which Westinghouse marketed.
Tesla conducted a range of experiments with mechanical oscillators/generators, electrical discharge tubes, and early X-ray imaging among other things, in an attempt to develop inventions he could patent and market. He built a wirelessly controlled boat, one of the first wirelessly controlled vehicles ever produced. Tesla became well known as an inventor and demonstrated his achievements to celebrities and wealthy patrons at his lab. He was noted for his showmanship at public lectures. Throughout the 1890s, Tesla pursued his ideas for wireless lighting and worldwide wireless electric power distribution in his high-voltage, high-frequency power experiments in New York and Colorado Springs. In 1893, he made pronouncements on the possibility of wireless communication with his devices. Tesla tried to put these ideas to practical use in his unfinished Wardenclyffe Tower project, an intercontinental wireless communication and power transmitter, but ran out of funding before he could complete it.
After Wardenclyffe, Tesla experimented with a series of inventions in the 1910s and 1920s with varying degrees of success. Having spent most of his money, Tesla lived in a series of New York hotels, leaving behind unpaid bills. He died in New York City in January 1943. Tesla's work fell into relative obscurity following his death, until 1960, when the General Conference on Weights and Measures named the International System of Units (SI) measurement of magnetic flux density the tesla in his honor. There has been a resurgence in popular interest in Tesla since the 1990s. In 2013, Time named Tesla one of the 100 most significant figures of all time.


== Early years ==


=== Childhood ===

Nikola Tesla was born on 10 July 1856 in the village of Smiljan, in the Military Frontier of the Austrian Empire (present-day Croatia) into an ethnic Serb family. His father, Milutin Tesla (1819–1879), was a priest of the Eastern Orthodox Church. His father's brother Josif was a lecturer at a military academy who wrote several textbooks on mathematics.
Tesla's mother, Georgina "Đuka" Mandić (1822–1892), whose father was also an Eastern Orthodox priest, had a talent for making home craft tools and mechanical appliances and the ability to memorize Serbian epic poems. Đuka had never received a formal education. Tesla credited his eidetic memory and creative abilities to his mother's genetics and influence.
Tesla was the fourth of five children. In 1861, Tesla attended primary school in Smiljan where he studied German, arithmetic, and religion. In 1862, the Tesla family moved to the nearby town of Gospić, where Tesla's father worked as parish priest. Nikola completed primary school, followed by middle school. Later in his patent applications, before he obtained American citizenship, Tesla would identify himself as "of Smiljan, Lika, border country of Austria-Hungary".


=== Education ===

In 1870, Tesla moved to Karlovac to attend high school at the Higher Real Gymnasium where the classes were held in German, as it was usual throughout schools within the Austro-Hungarian Military Frontier. Tesla later wrote that he became interested in his physics professor's demonstrations of electricity. The "mysterious phenomena" made him want "to know more of this wonderful force". He was able to perform integral calculus in his head, prompting his teachers to believe that he was cheating. He finished a four-year term in three years, graduating in 1873.
After graduating Tesla returned to Smiljan but soon contracted cholera, was bedridden for nine months and was near death several times. In a moment of despair, Tesla's father (who had originally wanted him to enter the priesthood), promised to send him to the best engineering school if he recovered from the illness. Tesla later said that he had read Mark Twain's earlier works while recovering from his illness.
The next year Tesla evaded conscription into the Austro-Hungarian Army in Smiljan by running away southeast of Lika to Tomingaj, near Gračac. There he explored the mountains wearing hunter's garb. Tesla said that this contact with nature made him stronger, both physically and mentally. He enrolled at the Imperial-Royal Technical College in Graz in 1875 on a Military Frontier scholarship. Tesla passed nine exams (nearly twice as many as required) and received a letter of commendation from the dean of the technical faculty to his father, which stated, "Your son is a star of first rank." At Graz, Tesla was fascinated by the lectures on electricity presented by professor Jakob Pöschl. But by his third year he was failing in school and never graduated, leaving Graz in December 1878. One biographer suggests Tesla was not studying and may have been expelled for gambling and womanizing.

Tesla's family did not hear from him after he left school. There was a rumor among his classmates that he had drowned in the nearby river Mur but in January one of them ran into Tesla in the town of Maribor and reported that encounter to Tesla's family. It turned out Tesla had been working there as a draftsman for 60 florins per month. In March 1879, Milutin finally located his son and tried to convince him to return home and take up his education in Prague. Tesla returned to Gospić later that month when he was deported for not having a residence permit. Tesla's father died the next month, on 17 April 1879, at the age of 60 after an unspecified illness.
In January 1880, two of Tesla's uncles paid for him to leave Gospić for Prague, where he was to study. He arrived too late to enroll at Charles-Ferdinand University; he had never studied Greek, a required subject; and he was illiterate in Czech, another required subject. He attended lectures in philosophy at the university as an auditor, but he did not receive grades for the courses.


=== Budapest Telephone Exchange ===
Tesla moved to Budapest, Hungary, in 1881 to work under Tivadar Puskás at a telegraph company, the Budapest Telephone Exchange. Upon arrival, Tesla realized that the company, then under construction, was not functional, so he worked as a draftsman in the Central Telegraph Office instead. Within a few months, the Budapest Telephone Exchange became functional, and Tesla was allocated the chief electrician position. Tesla later described how he made many improvements to the Central Station equipment including an improved telephone repeater or amplifier.


== Working at Edison ==
In 1882, Tivadar Puskás got Tesla another job in Paris with the Continental Edison Company. Tesla began working in what was then a brand new industry, installing indoor incandescent lighting citywide in large scale electric power utility. The company had several subdivisions and Tesla worked at the Société Electrique Edison, the division in the Ivry-sur-Seine suburb of Paris, in charge of installing the lighting system. There he gained a great deal of practical experience in electrical engineering. Management took notice of his advanced knowledge in engineering and physics, and soon had him designing and building improved versions of generating dynamos and motors.


=== Moving to the United States ===

In 1884, Edison manager Charles Batchelor, who had been overseeing the Paris installation, was brought back to the United States to manage the Edison Machine Works, a manufacturing division situated in New York City, and asked that Tesla be brought to the United States as well. In June 1884, Tesla emigrated and began working almost immediately at the Machine Works on Manhattan's Lower East Side, an overcrowded shop with a workforce of several hundred machinists, laborers, managing staff, and 20 "field engineers" struggling with the task of building the large electric utility in that city. As in Paris, Tesla was working on troubleshooting installations and improving generators.
Historian W. Bernard Carlson notes Tesla may have met company founder Thomas Edison only a couple of times. One of those times was noted in Tesla's autobiography where, after staying up all night repairing the damaged dynamos on the ocean liner SS Oregon, he ran into Batchelor and Edison, who made a quip about their "Parisian" being out all night. After Tesla told them he had been up all night fixing the Oregon, Edison commented to Batchelor that "this is a damned good man". One of the projects given to Tesla was to develop an arc lamp–based street lighting system. Arc lighting was the most popular type of street lighting but it required high voltages and was incompatible with the Edison low-voltage incandescent system, causing the company to lose contracts in some cities. Tesla's designs were never put into production, possibly because of technical improvements in incandescent street lighting or because of an installation deal that Edison made with an arc lighting company.
Tesla had been working at the Machine Works for a total of six months when he quit. What event precipitated his leaving is unclear. It may have been over a bonus he did not receive, either for redesigning generators or for the arc lighting system that was shelved. Tesla had previous run-ins with the Edison company over unpaid bonuses he believed he had earned. In his autobiography, Tesla stated the manager of the Edison Machine Works offered a $50,000 bonus to design "twenty-four different types of standard machines" "but it turned out to be a practical joke". Later versions of this story have Thomas Edison himself offering and then reneging on the deal, quipping: "Tesla, you don't understand our American humor". The size of the bonus in either story has been noted as odd, since Machine Works manager Batchelor was stingy with pay, and the company did not have that amount of cash (equal to $1,749,815 today) on hand. Tesla's diary contains just one comment on what happened at the end of his employment, a note he scrawled across the two pages covering 7 December 1884, to 4 January 1885, saying "Good By to the Edison Machine Works".


== Tesla Electric Light and Manufacturing ==
Soon after leaving the Edison company, Tesla was working on patenting an arc lighting system, possibly the same one he had developed at Edison. In March 1885, he met with patent attorney Lemuel W. Serrell, the same attorney used by Edison, to obtain help with submitting the patents. Serrell introduced Tesla to two businessmen, Robert Lane and Benjamin Vail, who agreed to finance an arc lighting manufacturing and utility company in Tesla's name, the Tesla Electric Light and Manufacturing Company. Tesla worked for the rest of the year obtaining the patents that included an improved DC generator, the first patents issued to Tesla in the US, and building and installing the system in Rahway, New Jersey.
The investors showed little interest in Tesla's ideas for new types of alternating current motors and electrical transmission equipment. After the utility was up and running in 1886, they decided that the manufacturing side of the business was too competitive and opted to simply run an electric utility. They formed a new utility company, abandoning Tesla's company and leaving the inventor penniless. Tesla even lost control of the patents he had generated, since he had assigned them to the company in exchange for stock. He had to work at various electrical repair jobs and as a ditch digger for $2 per day. Later in life, Tesla recounted that part of 1886 as a time of hardship, writing "My high education in various branches of science, mechanics and literature seemed to me like a mockery".


== AC and the induction motor ==

In late 1886, Tesla met Alfred S. Brown, a Western Union superintendent, and New York attorney Charles Fletcher Peck. The two men were experienced in setting up companies and promoting inventions and patents for financial gain. Based on Tesla's new ideas for electrical equipment, including a thermo-magnetic motor idea, they agreed to back the inventor financially and handle his patents. Together they formed the Tesla Electric Company in April 1887, with an agreement that profits from generated patents would go 1⁄3 to Tesla, 1⁄3 to Peck and Brown, and 1⁄3 to fund development. They set up a laboratory for Tesla at 89 Liberty Street in Manhattan, where he worked on improving and developing new types of electric motors, generators, and other devices.
In 1887, Tesla developed an induction motor that ran on alternating current (AC), a power system format that was rapidly expanding in Europe and the United States because of its advantages in long-distance, high-voltage transmission. The motor used polyphase current, which generated a rotating magnetic field to turn the motor (a principle that Tesla claimed to have conceived in 1882). This innovative electric motor, patented in May 1888, was a simple self-starting design that did not need a commutator, thus avoiding sparking and the high maintenance of constantly servicing and replacing mechanical brushes.
Along with getting the motor patented, Peck and Brown arranged to get the motor publicized, starting with independent testing to verify it was a functional improvement, followed by press releases sent to technical publications for articles to run concurrently with the issue of the patent. Physicist William Arnold Anthony (who tested the motor) and Electrical World magazine editor Thomas Commerford Martin arranged for Tesla to demonstrate his AC motor on 16 May 1888 at the American Institute of Electrical Engineers. Engineers working for the Westinghouse Electric & Manufacturing Company reported to George Westinghouse that Tesla had a viable AC motor and related power system—something Westinghouse needed for the alternating current system he was already marketing. Westinghouse looked into getting a patent on a similar commutator-less, rotating magnetic field-based induction motor developed in 1885 and presented in a paper in March 1888 by Italian physicist Galileo Ferraris, but decided that Tesla's patent would probably control the market.

In July 1888, Brown and Peck negotiated a licensing deal with George Westinghouse for Tesla's polyphase induction motor and transformer designs for $60,000 in cash and stock and a royalty of $2.50 per AC horsepower produced by each motor. Westinghouse also hired Tesla for one year for the large fee of $2,000 ($70,000 in today's dollars) per month to be a consultant at the Westinghouse Electric & Manufacturing Company's Pittsburgh labs.
During that year, Tesla worked in Pittsburgh, helping to create an alternating current system to power the city's streetcars. He found it a frustrating period because of conflicts with the other Westinghouse engineers over how best to implement AC power. Between them, they settled on a 60-cycle AC system that Tesla proposed (to match the working frequency of Tesla's motor), but they soon found that it would not work for streetcars, since Tesla's induction motor could run only at a constant speed. They ended up using a DC traction motor instead.


=== Market turmoil ===
Tesla's demonstration of his induction motor and Westinghouse's subsequent licensing of the patent, both in 1888, came at the time of extreme competition between electric companies. The three big firms, Westinghouse, Edison, and Thomson-Houston Electric Company, were trying to grow in a capital-intensive business while financially undercutting each other. There was even a "war of currents" propaganda campaign going on, with Edison Electric claiming their direct current system was better and safer than the Westinghouse alternating current system and Thomson-Houston sometimes siding with Edison. Competing in this market meant Westinghouse would not have the cash or engineering resources to develop Tesla's motor and the related polyphase system right away.
Two years after signing the Tesla contract, Westinghouse Electric was in trouble. The near collapse of Barings Bank in London triggered the financial panic of 1890, causing investors to call in their loans to Westinghouse Electric. The sudden cash shortage forced the company to refinance its debts. The new lenders demanded that Westinghouse cut back on what looked like excessive spending on acquisition of other companies, research, and patents, including the per motor royalty in the Tesla contract. At that point, the Tesla induction motor had been unsuccessful and was stuck in development. Westinghouse was paying a $15,000-a-year guaranteed royalty even though operating examples of the motor were rare and polyphase power systems needed to run it were even rarer.
In early 1891, George Westinghouse explained his financial difficulties to Tesla in stark terms, saying that, if he did not meet the demands of his lenders, he would no longer be in control of Westinghouse Electric and Tesla would have to "deal with the bankers" to try to collect future royalties. The advantages of having Westinghouse continue to champion the motor probably seemed obvious to Tesla and he agreed to release the company from the royalty payment clause in the contract. Six years later Westinghouse purchased Tesla's patent for a lump sum payment of $216,000 as part of a patent-sharing agreement signed with General Electric (a company created from the 1892 merger of Edison and Thomson-Houston).


== New York laboratories ==

The money Tesla made from licensing his AC patents made him independently wealthy and gave him the time and funds to pursue his own interests. In 1889, Tesla moved out of the Liberty Street shop Peck and Brown had rented and for the next dozen years worked out of a series of workshop/laboratory spaces in Manhattan. These included a lab at 175 Grand Street (1889–1892), the fourth floor of 33–35 South Fifth Avenue (1892–1895), and sixth and seventh floors of 46 & 48 East Houston Street (1895–1902).


=== Tesla coil ===

In the summer of 1889, Tesla traveled to the 1889 Exposition Universelle in Paris and learned of Heinrich Hertz's 1886–1888 experiments that proved the existence of electromagnetic radiation, including radio waves. In repeating and then expanding on these experiments Tesla tried powering a Ruhmkorff coil with a high speed alternator he had been developing as part of an improved arc lighting system but found that the high-frequency current overheated the iron core and melted the insulation between the primary and secondary windings in the coil. To fix this problem Tesla came up with his "oscillating transformer", with an air gap instead of insulating material between the primary and secondary windings and an iron core that could be moved to different positions in or out of the coil. Later called the Tesla coil, it would be used to produce high-voltage, low-current, high frequency alternating-current electricity. He would use this resonant transformer circuit in his later wireless power work.


=== Wireless lighting ===

After 1890, Tesla experimented with transmitting power by inductive and capacitive co

#9.1 CharacterTextSplitter

In [150]:
from langchain_text_splitters import CharacterTextSplitter

text_spliter = CharacterTextSplitter(
    separator ="",
    chunk_size = 100,
    length_function = len,
    chunk_overlap = 20
)

In [151]:
normal_chunks = text_spliter.create_documents(documents, metadatas=metadatas)

In [152]:
len(normal_chunks)

500

In [153]:
normal_chunks[4]

Document(metadata={'document': 'Nikola Tesla'}, page_content='receiving a degree. He then gained practical experience in the early 1880s working in telephony and')

In [154]:
len(normal_chunks[300].page_content)

100

In [155]:
## Without overLab
text_spliter = CharacterTextSplitter(
    separator = "",
    chunk_size = 100 ,
    length_function = len,
    chunk_overlap = 0,
)

In [156]:
normal_chunks1 = text_spliter.create_documents(documents , metadatas=metadatas)

In [157]:
normal_chunks1[1].page_content

'. He is known for his contributions to the design of the modern alternating current (AC) electricity'

#9.2 NLTK

In [158]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [159]:
from langchain_text_splitters import NLTKTextSplitter

In [160]:
text_splitter = NLTKTextSplitter(
    chunk_size = 300,
    chunk_overlap = 50
)

In [161]:
nltk_chunks = text_splitter.create_documents(documents , metadatas = metadatas)

WARNING:langchain_text_splitters.base:Created a chunk of size 315, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 316, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 334, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 430, which is longer than the specified 300

In [162]:
len(nltk_chunks)

176

In [163]:
print(nltk_chunks[3].page_content)

With the help of partners to finance and market his ideas, Tesla set up laboratories and companies in New York to develop a range of electrical and mechanical devices.

In [164]:
print(nltk_chunks[3].metadata)

{'document': 'Nikola Tesla'}

#9.3 TikToken

In [165]:
from langchain_text_splitters import TokenTextSplitter
text_splitter = TokenTextSplitter(
    model_name = "gpt-4o-mini",
    chunk_size=100,
    chunk_overlap=20,
)

In [166]:
token_chunks = text_splitter.create_documents(
    documents , metadatas= metadatas
)

In [167]:
len(token_chunks)

102

In [168]:
token_chunks[5].page_content

" he could complete it.\nAfter Wardenclyffe, Tesla experimented with a series of inventions in the 1910s and 1920s with varying degrees of success. Having spent most of his money, Tesla lived in a series of New York hotels, leaving behind unpaid bills. He died in New York City in January 1943. Tesla's work fell into relative obscurity following his death, until 1960, when the General Conference on Weights and Measures named the International System of"

#9.4 Transformers Tokens

In [169]:
from transformers import AutoTokenizer
model_id = "stabilityai/stablelm-tuned-alpha-3b"
tokenizer = AutoTokenizer.from_pretrained(model_id)

tokenizer_config.json:   0%|          | 0.00/264 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

In [170]:
from langchain_text_splitters import CharacterTextSplitter
text_splitter = CharacterTextSplitter.from_huggingface_tokenizer(
    tokenizer,
    chunk_size = 400,
    chunk_overlap = 0,
)

In [171]:
chunks = text_splitter.create_documents(documents, metadatas=metadatas)

WARNING:langchain_text_splitters.base:Created a chunk of size 540, which is longer than the specified 400
WARNING:langchain_text_splitters.base:Created a chunk of size 592, which is longer than the specified 400
WARNING:langchain_text_splitters.base:Created a chunk of size 459, which is longer than the specified 400
WARNING:langchain_text_splitters.base:Created a chunk of size 448, which is longer than the specified 400
WARNING:langchain_text_splitters.base:Created a chunk of size 665, which is longer than the specified 400
WARNING:langchain_text_splitters.base:Created a chunk of size 439, which is longer than the specified 400
WARNING:langchain_text_splitters.base:Created a chunk of size 501, which is longer than the specified 400

In [172]:
chunks[0].page_content

"Nikola Tesla (10 July 1856 – 7 January 1943) was a Serbian-American engineer, futurist, and inventor. He is known for his contributions to the design of the modern alternating current (AC) electricity supply system.\nBorn and raised in the Austrian Empire, Tesla first studied engineering and physics in the 1870s without receiving a degree. He then gained practical experience in the early 1880s working in telephony and at Continental Edison in the new electric power industry. In 1884, he migrated to the United States, where he became a naturalized citizen. He worked for a short time at the Edison Machine Works in New York City before he struck out on his own. With the help of partners to finance and market his ideas, Tesla set up laboratories and companies in New York to develop a range of electrical and mechanical devices. His AC induction motor and related polyphase AC patents, licensed by Westinghouse Electric in 1888, earned him a considerable amount of money and became the cornerstone of the polyphase system, which Westinghouse marketed.\nTesla conducted a range of experiments with mechanical oscillators/generators, electrical discharge tubes, and early X-ray imaging among other things, in an attempt to develop inventions he could patent and market. He built a wirelessly controlled boat, one of the first wirelessly controlled vehicles ever produced. Tesla became well known as an inventor and demonstrated his achievements to celebrities and wealthy patrons at his lab. He was noted for his showmanship at public lectures. Throughout the 1890s, Tesla pursued his ideas for wireless lighting and worldwide wireless electric power distribution in his high-voltage, high-frequency power experiments in New York and Colorado Springs. In 1893, he made pronouncements on the possibility of wireless communication with his devices. Tesla tried to put these ideas to practical use in his unfinished Wardenclyffe Tower project, an intercontinental wireless communication and power transmitter, but ran out of funding before he could complete it.\nAfter Wardenclyffe, Tesla experimented with a series of inventions in the 1910s and 1920s with varying degrees of success. Having spent most of his money, Tesla lived in a series of New York hotels, leaving behind unpaid bills. He died in New York City in January 1943. Tesla's work fell into relative obscurity following his death, until 1960, when the General Conference on Weights and Measures named the International System of Units (SI) measurement of magnetic flux density the tesla in his honor. There has been a resurgence in popular interest in Tesla since the 1990s. In 2013, Time named Tesla one of the 100 most significant figures of all time."

#. **Revision**

In [173]:
from langchain_community.document_loaders import WikipediaLoader
query_1 = "Mohamed salah"
query_2 = "Mohamed Aboutrika"


#=========================
docs_1 = WikipediaLoader(
    query = query_1,
    load_max_docs = 1,
    doc_content_chars_max= 20_000
).load()

text_documents_1 = docs_1[0].page_content

#===========================
docs_2 = WikipediaLoader(
    query = query_2 ,
    load_max_docs = 1 ,
    doc_content_chars_max = 20_000
).load()

text_documents_2  = docs_2[0].page_content

In [174]:
documents = [text_documents_1, text_documents_2]
metadatas = [{"document" : query_1} , {"document":query_2}]

In [175]:
documents[0]

'Mohamed Salah Hamed Mahrous Ghaly (born 15 June 1992) is an Egyptian professional footballer who plays as a right winger or right midfielder for Premier League club Liverpool and captains the Egypt national team. He is widely regarded as one of the best players of his generation and one of the greatest wingers of all time. He is the all-time top foreign goalscorer in the Premier League and the all-time top African goalscorer in the UEFA Champions League.\nSalah began his senior career in 2010 at Al-Mokawloon, departing in 2012 to join Basel, where he won two Swiss Super League titles. In 2014, he joined Chelsea for a reported fee of £11 million, but limited gametime led to successive loans to Fiorentina and Roma, who later signed him permanently for €15 million. In the 2016–17 season, Salah was a key figure in Roma\'s unsuccessful title bid, reaching double figures in both goals and assists. In 2017, Salah moved to Liverpool for £36.9 million, a club record at the time. In his first season, he set the record for most Premier League goals scored (32) in a 38-game season and helped Liverpool to the 2018 Champions League final. Having formed a formidable attacking trio with Roberto Firmino and Sadio Mané, Salah went on to be an integral player in the club\'s Champions League and Premier League title successes in the following two seasons. He has since also won the FA Cup, EFL Cup, FA Community Shield, UEFA Super Cup and the FIFA Club World Cup. In the 2024–25 season, he won a second league title while breaking the record for the most goal contributions in a 38 game Premier League campaign. For his performances during the season, he won the PFA Players\' Player of the Year award for a record-breaking third time.\nSalah\'s other individual accolades include three FWA Footballer of the Year awards, four Premier League Golden Boots, two Premier League Player of the Season awards, two Premier League Playmaker of the Season awards, finished third for the Best FIFA Men\'s Player in 2018 and 2021, and finished fourth in the 2025 Ballon d\'Or, respectively. He received the 2018 FIFA Puskás Award for his winning strike in the first Merseyside derby of the 2017–18 season. In 2023, Salah became Liverpool\'s all-time top goalscorer in the history of the Premier League, and also became the fifth player to score 200 goals for the club. In 2025, he became Liverpool\'s third-highest goalscorer in the club\'s history behind Roger Hunt and Ian Rush.\nAt international level, Salah represented Egypt at youth level before making his senior debut in 2011. Following his performances at the 2012 Summer Olympics, he was named CAF Most Promising African Talent of the Year. Since then, he finished as runner-up in the 2017 and 2021 Africa Cup of Nations, and was top scorer during CAF qualification as Egypt qualified for the 2018 FIFA World Cup. Salah was named CAF African Footballer of the Year (2017 and 2018), BBC African Footballer of the Year (2017 and 2018), and was selected in the 2017 Africa Cup of Nations Team of the Tournament, 2021 Africa Cup of Nations Team of the Tournament and the CAF Team of the Year on several occasions.\nSalah is regarded as a symbol of national pride in Egypt for his achievements and was named in theTime magazine\'s list of the 100 Most Influential People in 2019. Salah has also been credited for raising the profile of Liverpool among Egyptians.\n\n\n== Club career ==\n\n\n=== Al Mokawloon ===\nSalah started out playing for the youth setups of local teams Ittihad Basyoun and Othmason Tanta. He names Ronaldo, Zinedine Zidane and Francesco Totti as his childhood idols. In 2006, he joined the youth team of Al Mokawloon Al Arab aged 14 after being spotted by a scout who had originally come to watch another child play but was distracted by Salah. Salah frequently had to miss school to make the three-hour journey to training. When Salah was 15 he was noticed by first-team manager Mohamed Radwan, who moved him to the first-team squad immediately. Salah had to be given a special diet and training program due to his muscles not being fully formed because of his young age.\nSalah made his first-team debut on 3 May 2010 in the Egyptian Premier League, coming on as a substitute in a 1–1 away draw against El Mansoura. During the 2010–11 season Salah continued earning minutes on the pitch, eventually becoming a regular in the team. Even though he was getting regular game time, Salah struggled to score. In the dressing room after matches he would sometimes be in tears because of this, and Radwan says it only motivated him to become better. He scored his first goal for them on 25 December 2010 in a 1–1 away draw against Al Ahly. He remained a regular for Al Mokawloon, appearing in every game of the 2011–12 season. Following the Port Said Stadium riot on 1 February 2012, the Egyptian Premier League was suspended, and on 10 March, the Egyptian Football Association announced their decision to cancel the remainder of the season.\n\n\n=== Basel ===\n\n\n==== 2012–2013: Development and breakthrough ====\n\nSwiss Super League club Basel had been monitoring Salah for some time, so following the Egyptian Premier League suspension, the club organised a friendly match with the Egypt national under-23 team. The match took place on 16 March at the Stadion Rankhof in Basel, and despite only playing the second half, Salah scored twice, helping the Egyptians to a 4–3 win. Basel subsequently invited Salah to remain in the city for a week\'s training. On 10 April 2012, it was announced that Salah had signed for Basel on a four-year contract starting from 15 June 2012. He initially found it difficult to settle, having arrived unable to speak the language and been signed as a replacement for Xherdan Shaqiri. Salah scored on his unofficial debut on 23 June 2012 against FCSB during a friendly match, a 4–2 defeat. He made his official Basel debut in a UEFA Champions League preliminary stage match against the Norwegian club Molde on 8 August, coming on as a substitute in the 74th minute. He made his league debut on 12 August against Thun, playing the full match.\nHe scored his first league goal a week later, the second goal in a 2–0 home win against Lausanne-Sport. Salah scored his first UEFA Europa League goal in the quarter-finals on 11 April 2013, as Basel advanced to the semi-finals by beating Tottenham Hotspur 4–1 in a penalty shoot-out after a 4–4 aggregate draw. In the semi-final on 2 May, Salah scored away to Chelsea, although Basel were beaten 5–2 on aggregate. Despite late disappointment in Europe, Basel won the 2012–13 Swiss Super League title and finished runners-up in the Swiss Cup.\n\n\n==== 2013–2014: Final season and league championship ====\nAhead of the 2013–14 Swiss Super League season, Salah was a member of the Basel team that won the 2013 Uhrencup. Salah scored in his first league appearance of the season against Aarau on 13 July 2013. He scored his first Champions League goal a month later against Maccabi Tel Aviv on 6 August 2013 in the third qualifying round. Salah was the subject of major controversy following the game, after he appeared to deliberately avoid shaking hands with the players of the Israeli club in both the home and away legs.\nHe scored twice against the Bulgarian league champions PFC Ludogorets Razgrad on 21 August 2013 in the play-off round. On 18 September 2013, Salah scored the equaliser against Chelsea in the 2–1 away win during the group stage. During the return tie on 26 November at St. Jakob-Park, Salah scored the winning goal as Basel beat Chelsea for the second time with a 1–0 home win. However, he was unable to prevent Basel being eliminated in the group stage.\nOn the domestic stage, Salah continued to perform. Scoring four goals in 18 games, including a double against title rivals Young Boys, he helped Basel win the league title for the fifth time in a row.\nOn 23 January 2014, it was announced that Salah would leave Basel. During his time with the club, Salah played a total of 79 games for Basel, scoring a total of 20 goals. 47 of these games were in the Swiss Super League, six in the Swiss Cup, and 26 in UEFA competitions (Champions League and Europa League). He scored nine goals in the domestic league, four in the cup, and seven in European matches.\n\n\n=== Chelsea ===\n\n\n==== 2014 ====\nOn 23 January 2014, Premier League club Chelsea announced that a deal had been agreed with Basel to sign Salah for a fee reported to be in the region of £11 million. Three days later the transfer was completed, making him the first Egyptian to sign for the London-based club. Liverpool had been interested in Salah, and had made an offer of £11 million but were beaten to his signature by Chelsea.\nOn 8 February, Salah made his debut for Chelsea in the Premier League, coming on as a substitute in the 3–0 win over Newcastle United. Seven games later, on 22 March, Salah scored his first goal for Chelsea against Arsenal in the London derby, coming on as a substitute for Oscar, in a match which ended as a 6–0 home win. Then, on 5 April, Salah opened the scoring and later won a penalty and assisted the third goal in Chelsea\'s 3–0 win over Stoke City.\n\n\n==== 2014–2015 ====\n\nBefore the 2014–15 season, Salah\'s future with Chelsea looked to be in doubt after reports suggested he could be forced to return to Egypt to carry out military service after his registration for an education scheme was rescinded by the Egyptian Minister of Higher Education. He was spared from military service after a meeting with Egyptian prime minister Ibrahim Mahlab, the Minister of Higher Education, and the Egypt national team manager Shawky Gharieb. Salah changed squad numbers from 15 to 17 for the start of the season, with his new number having been vacated by Eden Hazard changing to number 10.\nSalah was rarely used during the season, making just three Premier League, two Champions League and three cup appearances, failing to score in any of them. On 28 October 2014, after a poor performance in a 2–1 win away to League Two team Shrewsbury Town in the fourth round of the League Cup, he and fellow winger André Schürrle were criticised publicly by manager José Mourinho. Although Salah only made three league appearances before his loan move to Fiorentina, Mourinho stated that he would receive a replica winner\'s medal from the club for his contributions that season.\n\n\n==== 2015: Loan to Fiorentina ====\n\nOn the transfer deadline day, 2 February 2015, Chelsea confirmed that Salah would join Italian club Fiorentina on an 18-month loan until the end of the 2015–16 season, as part of a transfer deal which saw Juan Cuadrado moving in the opposite direction. Six days after signing, he made his debut coming off the bench in the 65th minute as a replacement for Joaquín in a 3–2 home victory against Atalanta in Serie A. Salah chose the number 74 shirt in honour of the victims of the Port Said Stadium riot.\nSalah made his first start for Fiorentina on 14 February against Sassuolo, scoring his first goal for the club in the 30th minute. He then provided an assist to Khouma Babacar just two minutes after scoring; the match ended in a 3–1 win for Fiorentina. Twelve days later, Salah scored his first European goal for Fiorentina, as his side advanced to the round of sixteen of the Europa League, beating Tottenham 3–1 on aggregate. Salah scored the winning goal for Fiorentina against Inter Milan on 1 March, his third goal in Serie A. Four days after that, Salah scored both of Fiorentina\'s goals in their 2–1 win away to Juventus in the Coppa Italia semi-final first leg. At the end of the season, Fiorentina activated an option to make the loan move permanent, but Salah refused the move. Even though the loan agreement was for 18 months, Salah refused to return to Fiorentina and instead joined fellow Serie A club Roma. On 11 September, Fiorentina filed a complaint to FIFA, claiming that Chelsea had breached the agreed contract when they allowed Salah to join Roma on loan. The Court of Arbitration for Sport cleared Salah and Chelsea of any wrongdoing.\n\n\n==== 2015–2016: Loan to Roma ====\nOn 6 August 2015, Salah joined Roma on a season-long loan for €5 million; with the option to make the deal permanent, for a reported €15 million. He wore the number 11 shirt. He made his debut on 22 August, as the new season began with a 1–1 draw away Hellas Verona. On 20 September, Salah scored his first goal of the season against Sassuolo to help Roma salvage a point as the match ended in a 2–2 draw. He went on to score in his following two matches, a 2–1 loss against Sampdoria and a 5–1 win against Carpi. On 25 October, Salah scored the opener against his former club Fiorentina in a 2–1 away victory to help earn a fourth straight league win for Roma. On his return, Salah was also sent off after picking up a second yellow in the closing minutes of the match, just seconds after picking up his first yellow. On 4 November, he scored the opening goal of a 3–2 Champions League win over Bayer Leverkusen.\nOn 4 March, he faced his former side Fiorentina again and scored another double as Roma won 4–1 and broke into the top three. Salah would go onto score another three goals that season, scoring against Bologna, Genoa, and AC Milan, the latter on the final day. In the 2015–16 season, Salah scored 15 goals in 42 matches as Roma finished in third place in Serie A and qualified for the Champions League. In June, it was announced that Salah won the club\'s 2015–16 Player of the Season award.\n\n\n=== Roma ===\n\n\n==== 2016–2017: Permanent transfer, Serie A runner-up ====\nOn 3 August 2016, Roma announced the signing of Salah on a permanent deal for €15 million. He scored his first goal of the season in a 4–0 win over Udinese in the opening game of the season on 20 August. On 6 November, Salah scored a hat-trick in a 3–0 win over Bologna, his first club career hat-trick. However, a ruptured ankle ligament kept him out for the first half of December. He returned as a half-time substitute in a 1–0 defeat against title rivals Juventus on 17 December. Salah then endured a two-month period without a goal, he broke his drought on 19 February, scoring against Torino in a 4–1 win. On 9 March, he scored Roma\'s opening goal in an eventual 4–2 defeat to Lyon in the first leg of the round of sixteen in the 2016–17 Europa League. Despite winning the second leg 2–1, they were unable to turn the tie around and were knocked out 5–4 on aggregate. On 28 May, in the final game of the season, Salah was substituted for captain Francesco Totti, who was playing his final game with the club, in a 3–2 win over Genoa. Roma finished the season in second, just four points behind champions Juventus. Salah scored 19 goals in all competitions.\n\n\n=== Liverpool ===\n\n\n==== 2017–2018: Record-breaking individual success ====\n\nOn 22 June 2017, Salah agreed a transfer to Premier League club Liverpool. He signed a long-term contract with the Reds for an initial £36.5m fee that could rise to £43m. The fee was a club record, eclipsing the £35m spent on Andy Carroll in 2011. He was assigned the number 11 shirt previously worn by Roberto Firmino who instead switched to number 9. He joined the club on 1 July upon the opening of the summer transfer window, becoming Liverpool\'s first Egyptian player, and scored on his Premier League debut against Watford in a 3–3 away draw on 12 August. On 24 August, Salah scored his second goal for Liverpool, in a 2017–18 Champions League play-off round 4–2 win (6–3 agg) against 1899 Hoffenheim, his first goal at Anfield. Three days later, Salah scored and assisted a goal in a 4–0 victory over Arsenal. For his performances in August, Salah was awarded Player of the Month by Liverpool supporters. On 17 October, Salah netted twice in a 7–0 Champions League win over Maribor, helping Liverpool to the joint-largest ever away win in the competition, and the largest away win by an English club.\n\nOn 26 November 2017, Salah scored the opener and refused to celebrate in a 1–1 home draw with his former team Chelsea out of respect for the club as well as victims of the Sinai mosque attack two days earlier. Salah rose the top of the Premier League goalscoring charts by scoring twice after coming on as a substitute away at Stoke City on 29 November in a 3–0 win. The following month, Salah netted in a 4–0 win over Bournemouth; a result which saw Liverpool become the first team in Premier League history to win four consecutive away league matches by a margin of at least three goals. In the process, he also became the joint-second fastest player to reach 20 goals for Liverpool on his 26th appearance, behind George Allan who reached the milestone in 19 appearances in 1895. On 17 March 2018, Salah scored four goals in a 5–0 win over Watford, which was his first hat-trick for Liverpool. In this game, he also broke a record of scoring 36 times in his debut season for Liverpool, and also became the leading goalscorer in Europe\'s top five leagues – overtaking Barcelona\'s Lionel Messi and Tottenham striker Harry Kane. Following Salah\'s record-breaking goal exploits former Liverpool captain Steven Gerrard stated "we are witnessing the start of greatness".\nIn early April 2018, he scored in both Champions League quarter-final matches against Manchester City to help his side advance. On 22 April 2018, Salah was awarded the PFA Players\' Player of the Year award, having earlier been named in the PFA Team of the Year for the Premier League. Two days later, he scored a brace in a 5–2 Champions League semi-final first leg win over former club, Roma. In doing so, he simultaneously became the first player from Africa and the first Liverpool player to score 10 goals in a single campaign in the tournament. His double also took him to 43 goals for the season across all competitions, surpassing Roger Hunt\'s tally of 42, and making him Liverpool\'s second-highest goalscorer in a single season, behind Ian Rush. He had previously also broken the club\'s record for the Premier League era, surpassing Robbie Fowler\'s total of 36 goals set in the 1995–96 campaign, and Fernando Torres\' record of 33 for the most goals by a Liverpool player in a debut season. After his two goals and assists in the first leg against Roma, Salah featured in the second leg as Liverpool beat the Italian club 7–6 on aggregate to qualify for the final for the first time in eleven years. He would then become the Premier League\'s all-time goalscorer for a 38-game season, registering his 32nd league goal in a 4–0 win against Brighton & Hove Albion en route to being awarded the Premier League Golden Boot.\nIn the 2018 Champions League final against Real Madrid, Salah injured his left shoulder in the 30th minute after a challenge by Madrid defender Sergio Ramos. After initially carrying on, he left the field in tears after going to ground again; the match ended in a 3–1 defeat. The Egyptian FA stated that this would have no effect on his availability for the 2018 FIFA World Cup in Russia, and that Salah would still be named in the team\'s final squad on 4 June. The day after the match, Ramos wrote a message and sent him good wishes.\n\n\n==== 2018–2019: European champion and second Golden Boot ====\n\nOn 2 July 2018, Salah signed a new long-term contract with Liverpool. Manager Jürgen Klopp said the news was important as a statement of intent in terms of Liverpool\'s status in the football world in having Salah commit himself further to the club. On 12 August, Salah scored Liverpool\'s first goal of the season, in a 4–0 home win over West Ham United. On 30 August, Salah was named on the three-man shortlist for the UEFA Men\'s Player of the Year, coming in third place, and was also included on the three-man shortlist for the UEFA Forward of the Season, coming in second place. On 3 September he was named on the three-man shortlist for the Bes

In [176]:
documents[1]

'Mohamed Aboutrika (Arabic: محمد محمد محمد أبو تريكة; born 7 November 1978) is an Egyptian retired professional footballer who played as an attacking midfielder and a forward. He was voted first place in the African Footballer of the Year award in 2008, and was one of five nominees for the 2006 award, and one of the ten nominated for the 2013 award. He is widely regarded as one of the greatest African  players of all time.\nAboutrika won the African Cup of Nations in 2006 with the Egyptian national team. He also scored the winning goal to help Egypt win the 2008 Africa Cup of Nations. He helped his club Al Ahly to win the bronze medal in the FIFA Club World Cup in 2006.\nOff the pitch, he has been noted for both various humanitarian efforts as well as his philanthropy in Egypt.\n\n\n== Club career ==\n\n\n=== 2004: Debut season with Al Ahly ===\nIn the first half of Egyptian league 2003–2004, Aboutrika scored 3 goals for Tersana. In January 2004, he was offered a position in Al Ahly. He scored 11 goals in his first 13 appearances with Al Ahly in the 2003–2004 season (all in the league), becoming the second-highest scorer in the Egyptian League with 14 goals.\nAboutrika\'s efforts with Ahly drew attention from the Egyptian national team, he started his first game against Trinidad and Tobago in a friendly match before the World Cup 2006 qualifiers on 31 March 2004 in Arab Contractors Stadium. The first starting game for Aboutrika ended 2–1 for the Egyptians. He started as an attacker, but was found to play better when he played his normal position behind the attackers in the attacking midfield position. Aboutrika scored his first national goal in this game. He scored 5 goals in his first 6 appearances with Egypt between 2004 and 2005.\n\n\n=== 2005 season ===\nIn 2005, Al Ahly regained the Egyptian League Championship after four years out of the top position, Aboutrika finished 3rd in the goalscoring rankings in the Egyptian League, while also helping his teammate Emad Moteab finish as the competition\'s top scorer. Also in 2005, Aboutrika played a great role in Al Ahly victory of the 2005 CAF Champions League, he scored a goal in the final from 30 yards out against Étoile Sportive du Sahel of Tunisia in a game that ended 3–0 for Al Ahly.\nAl Ahly qualified for the 2005 FIFA Club World Championship but finished last, Aboutrika told FIFA.com the reason, saying: "Our problem was that we lost our form, for some reason we could not play like we had before arriving in Japan".\n\n\n=== 2006 ===\nHe proved to be his international team\'s trump card en route to victory in the 2006 Africa Cup of Nations in February, when he scored two important goals against Libya and Ivory Coast. He was the winning goal assistant, in the semi-final match against Senegal when Amr Zaki scored in the 80th minute. He was very dominant in that game, but his accurate shot hit the bar. In the final match, Aboutrika scored the decisive penalty in the shoot-out which gave Egypt the title.\nAboutrika led Al Ahly to the 2006 CAF Champions League title for the second successive time in November 2006. He was the top scorer of the competition with 8 goals, and scored the winning goal in the final against CS Sfaxien in the 91st\nminute.\nHe also participated with Al Ahly in winning the CAF Super Cup against FAR Rabat of Morocco, days after the Africa Cup of Nations in February.\nLocally, he got the Egyptian Premier League in June when he was the top scorer by 18 goals, and won Egypt Cup, then the Egyptian Super Cup in July when he scored the winning goal against ENPPI in the 92nd minute despite having suffered an injury in the first half.\nJapanese newspapers nominated Aboutrika to be one of the best players in 2006 FIFA Club World Cup in Japan, the last tournament in Aboutrika\'s year. Al Ahly was one of the African representatives, and the first team ever to be qualified two successive times to this championship, and the first African team to win a medal in that competition.\nIn the opening match of the tournament against Auckland City FC of New Zealand on 10 December 2006, Aboutrika helped Al Ahly to secure and book a semi-final date with Internacional of Brazil. Al Ahly won 2–0, and Aboutrika capped a fine display by stroking a superbly flighted free-kick over the wall, scoring the second goal for his team. As well as netting with his delightful right-foot effort, Aboutrika was at the heart of most his side\'s best moves, dictating the rhythm with his skill and vision.\nIn the semi-finals, Al Ahly faced Brazilian Internacional on 13 December 2006, and Aboutrika played a good game, but his accurate shot hit the Brazilian right-hand post to deprive his team from a draw. Al Ahly lost the match 2–1, but proved a good efficiency, yet the ball refused to be netted in many available chances to score in Brazilian goalkeeper.\nAl Ahly faced Club América of Mexico, for the third place, and Aboutrika gave Al Ahly the lead with an amazing free-kick over the wall, ending the first half 1–0 for Al Ahly. In the second half, America scored an equalizer, Aboutrika appeared in the 79th minute with a skilled ball, he showed yet again why he is on the shortlist for the African player of the year. After surging out of midfield and finding Flavio Amado with a pinpoint pass, the mercurial playmaker latched on to the Angolan\'s return ball and calmly slotted the ball past the Mexican goalkeeper for his third goal of the tournament. Al Ahly won the third place, after Aboutrika lifted his team to an unprecedented result for the Egyptian club or any African outfit. He finished as the tournament\'s top scorer with 3 goals in 3 matches.\nAboutrika won all but one of the competitions he participated in that year for club and country, and got the bronze medal for Al Ahly in 2006 FIFA Club World Cup. He was the top scorer in three competitions, which are 2006 FIFA Club World Cup with 3 goals, Egyptian Premier League with 18 goals and 2006 CAF Champions League with 8 goals. Aboutrika scored in other competitions, and made brilliant assistants to strikers.\n\n\n=== African Footballer of the Year 2006 Nomination ===\nTo the FIFA.com expression,  He was nominated to win the 2006 CAF African Footballer of the Year award along with Chelsea striker Didier Drogba and FC Barcelona forward Samuel Eto\'o. The other nominees for the honour were Chelsea and Ghana international midfielder Michael Essien, and Nigeria and Portsmouth striker Nwankwo Kanu, who previously won the award twice. Aboutrika said in November 2006: "I would love to be nominated for the CAF Best Player award. That would make 2006 a very special year!".\nAboutrika was the only African-based player between the nominees, but he was also the only one who made an achievement for his national team that year by winning 2006 Africa Cup of Nations. Aboutrika\'s brace in the 2006 FIFA Club World Cup and his dazzling performances throughout the season made him a serious contender for the CAF African Footballer of the Year award (as well as the BBC award) and secured his place as Egypt\'s most popular personality. He did not win the award but achieved second place and later was given "best interclub player" and "best player in the CAF Champions League."\n"Aboutrika has won the highest prize any person can achieve, that is the love of the people," sports columnist Hassan Mistikawi wrote in the state-owned Al-Ahram daily newspaper.\nFormer Al Ahly coach Manuel José de Jesus described Aboutrika as "the best football player in Africa", commenting that Aboutrika did not show more of his repertoire of skills while at the Club World Cup. He said: "Aboutrika didn\'t introduce all what he has in FIFA Club World Cup 2006, but he got the top scorer title and helped leading his team to the third place". José also mentioned Aboutrika as one of the best players he ever trained. He reinforced this statement, saying: "Aboutrika is priceless for us. I can\'t imagine my team without him".\n\n\n=== 2007 ===\nIn 2007, Al Ahly won the Egyptian Premier League (2006–2007) for the third successive season. Aboutrika scored 7 goals for his team, although he was injured. Al Ahly won the Egypt Cup 2007 for the second successive time. Aboutrika was the top goalscorer of the competition with 4 goals. He scored a double kick memorable goal against Tala\'ea El-Gaish SC in the 8-round game which ended 3–1 for Al Ahly. In the final, Al Ahly faced his rival Zamalek SC. Aboutrika made a one neck-saving equalizer in the last 2 minutes on 2 July 2007 in the Egypt Cup resulting in extra-time after tying 2–2. After Zamalek grabbed their third in the first half of extra-time, Aboutrika dazzled the stands with two great balls, one an assisted cross over the whites\' defense to Osama Hosny to score the equalizer in the second half of extra-time in the first seconds of the game and within a minute, he surged between the Zamalek\'s midfield and passed two Zamalek players before providing an accurate through pass to Ahmad Sedik on the wing who went through on goal and assisted again for Osama Hosny for the late winner and holding high the Egyptian Cup. After that, Al Ahly won the Egyptian Super Cup 2007 for the third successive time, through shoot-outs, after tying 1–1 with Ismaily.\nIn 2007 CAF Champions League, Aboutrika scored 4 goals for Al Ahly until now, to raise his African goals to the number 15. Al Ahly faced Étoile Sportive du Sahel of Tunisia in the final match. Al Ahly was having the chance to be the first team in the World to reach FIFA Club World Cup three successive times, and the first team in Africa to win CAF Champions League three successive times. However, the two legs ended, seeing Étoile Sportive du Sahel of Tunisia lifting the cup.\nHe won the title Best Player in Egypt for 2007 the fourth successive time after 2004, 2005, 2006 and 2007 setting a new Egyptian record.\n\n\n=== 2008 ===\nAfrican Cup of Nations 2008\nIn 2008, Aboutrika scored 4 goals for Egypt in the 2008 Africa Cup of Nations. He scored the winning goal against Cameroon in the final match, helping Egypt to win the African Cup of Nations for the second consecutive tournament. Aboutrika also scored a goal in the semi-final against the Ivory Coast, and scored twice against Sudan in Egypt\'s group stage match.\nAboutrika scored a goal in the final match. In the previous tournament in 2006, he scored the latest decisive penalty shoot-out in the final match against the Ivory Coast to give Egypt the cup. With his team Al Ahly of Egypt, Aboutrika was the hero of final matches again, through scoring a goal in the final match of both the 2006 and the 2005 CAF Champions League helping his team lift the continental cup.\n\n\n=== CAF Champions League 2008 ===\nAboutrika rehealed from injury in August, after missing the group stage start of 2008 CAF Champions League with his team Al Ahly. He marked his first participation in the group stage, scoring the winning goal for Al Ahly in the 93rd minute against Dynamos F.C. of Zimbabwe in an 8-round game that ended 2–1 for the Egyptian side. On 30 August, he helped Al Ahly to grab the 3 points from Zimbabwe, after making the winning goal, scored by his favourite teammate Mohamed Barakat; Al Ahly achieved a 1–0 win. On 14 September, Aboutrika scored the second goal for Al Ahly against their rivals, Zamalek SC of Egypt, in a group game that ended 2–2.\nAboutrika scored again in the final group match against ASEC Mimosas, a game ended 2–2 as Aboutrika netted the first goal for Al Ahly. A draw sealed first place in Group A for Al Ahly with 12 points from six matches, while Dynamos of Zimbabwe joined them in the semi-finals of the 3.5-million-dollar competition.\nAboutrika was crowned the 2008 BBC African Footballer of the Year. He won after taking more than half of the total ballot.\n\n\n=== 2008 African Footballer of the Year nomination ===\nMohamed Aboutrika (Al Ahly, Egypt), Emmanuel Adebayor (Arsenal, Togo), Amr Zaki (Wigan Athletic, Egypt), Didier Drogba (Chelsea F.C., Ivory Coast) and Michael Essien (Chelsea F.C., Ghana) make up the shortlist for the Glo-CAF African Footballer of the Year across the world.\nThe Confederation of African Football (CAF) on Wednesday in Lagos, Nigeria, announced the final shortlist of categories for the Glo-CAF Awards 2008. The final three for the title was decided following votes from the head coaches of the 53 national associations affiliated to CAF.\nFor the topmost honour, Glo-CAF Player of the Year across the world, the contenders are Emmanuel Adebayor (Arsenal and Togo), Michael Essien (Chelsea and Ghana) and Mohamed Aboutrika (Al Ahly and Egypt).\nThe shortlist for the Glo-CAF Best Player on the Continent are Mohamed Aboutrika (Al Ahly, Egypt), Ahmed Hassan (Al Ahly, Egypt), Flavio Amado (Al Ahly, Angola).\nThe winner of the two categories will be announced at the awards gala on 10 February, in Lagos, Nigeria.\nFIFA World Cup 2010 Qualifiers\nOn 7 June, Aboutrika scored in Egypt\'s world cup qualifier against Algeria in Algeria, but Egypt lost 3–1.\nOn 4 July, Aboutrika played in Egypt\'s world cup qualifier against Rwanda in Egypt, helping the Egyptians win 3–0, and scored the first and the third goal, making the Egyptian team second after Algeria, in their group. Aboutrika reached his fifth goal in FIFA World Cup 2010 Qualifiers.\n\n\n=== 2012 ===\nPort Said Stadium disaster\nAfter the Port Said Stadium disaster, on 1 February 2012, Aboutrika decided to retire from professional football, along with Emad Motaeb and Mohamed Barakat, then he decided to get back to football. Around a week later, the Egyptian Premier League had been cancelled. Aboutrika had finished the uncompleted campaign with 4 goals in 14 games.\nCAF Champions League\nAboutrika helped Al Ahly won their seventh CAF Champions League title after scoring 6 goals. His most impressive match was on 14 May 2012. Ahly were down 1–0 at home to Stade Malien in a second leg CAF Champions League match and were down 2–0 on aggregate. Aboutrika was subbed on in the 42nd minute for Mohamed Shawky and in the second half, he scored his first ever CAF Champions League hat-trick, 2 of which were scored in the last 8 minutes of the match. He scored the first from a wonderfully curled free-kick from 28 yards out. He then scored the second from the penalty spot in the 82nd minute. Finally, he blasted the third from into the top right corner from 12 yards out to get the hat-trick, complete the comeback, and secure Al Ahly a place in the 2012 CAF Champions League group stage. On 22 July 2012, he scored against Zamalek to win 1–0 in the group stage match.\nLondon 2012\nAboutrika was one of the three overage players participated with Egypt in London 2012, and was the team\'s captain. Aboutrika scored Egypt\'s first goal in the tournament against Brazil in a 3–2 loss. In the second game, Aboutrika\'s assist for Mohamed Salah picked a 1–1 draw against New Zealand. In the third game against Belarus, Aboutrika assisted a goal for Mohamed Salah and scored another to help Egypt win 3–1 and claim a quarter-final berth.\nClub World Cup\nAboutrika scored the winner goal for Al Ahly in a 2–1 victory over Japanese side Sanfrecce Hiroshima. A goal secured his team a place in the quarter-finals. Al Ahly came fourth in the tournament. Aboutrika became the joint all-time top scorer in the FIFA Club World Cup with 4 goals, alongside Lionel Messi and Denilson.\nAfrica Based Player of the Year\nAboutrika was crowned African player of the Year Based in Africa. The 34-year-old secured his third title after winning the same award in 2008 and 2006.\n\n\n=== 2013 ===\nIn the first half of the year, Aboutrika agreed to join Baniyas SC for loan. He helped the Emirati team to win Gulf Champions League, scoring in the semi-final and final matches. He also scored in his debut match with the team.\nAboutrika returned to Al Ahly to help Al Ahly retain his continental title. In his first match after return, he scored against Zamalek SC in the 2013 CAF Champions League group stage. The game ended 1–1 and this was Aboutrika\'s 12th goal in Cairo Derby, a personal record. On 15 September, Aboutrika scored his 13th goal in Cairo Derby. With this goal, he became the top goalscorer in all Cairo Derby matches, alongside Al Ahly Legend Mahmoud Mokhtar El-Tetsh. Al Ahly won 4–2 to advance to the semi-finals of the 2013 CAF Champions League. In the semi-final first leg held on 6 October at Cameroon, Aboutrika grabbed the equaliser against Coton Sport FC de Garoua in the first leg, which ended 1–1; in the final match first leg in Orlando Stadium Aboutrika scored Al Ahly\'s goal in a 1–1 draw against Orlando Pirates of South Africa on 2 November, and in the second leg held in Cairo on 10 November, Aboutrika opened the scoring for Al Ahly as they went on to win 2–0, retaining the title. That was Aboutrika\'s 32nd goal for Al Ahly in African Competitions. He is the second all-time top scorer after Al Ahly legend Mahmoud El Khatib who scored 37 goals. Aboutrika provided 21 assists in continental matches too in addition to his 32 goals.\nIndividually, Aboutrika was named in July by Goal.com in the Goal 50 list for (2012/2013) season. He took the 29th spot. He is the first Africa-based player to appear in the Goal 50 for a second time, after being named in 45th spot in 2009.\nAt the international level, on 26 March, Aboutrika grabbed a last minute goal for Egypt national football team against Zimbabwe national football team in a World Cup Qualifier helping hosts to win 2–1. On 9 June, he started the scoresheet in Harare and Egypt won 4–2, and made two assists for his teammate Mohamed Salah. On 10 September, Aboutrika played his 100th historic cap with Egypt national football team against Guinea national football team in a World Cup Qualifier. He scored a goal and assisted two goals for Mohamed Salah and Amr Zaki. Egypt won 4–2 and set to advance to a two-leg play-off during October and November against Ghana, with the winners qualifying for Brazil 2014. Aboutrika is the second joint top scorer of the CAF second round qualifiers with 5 goals in 6 qualifiers, and 9 assists. After scoring in the play-off against Ghana, he became the all-time top scorer of Egypt in the World Cup Qualifiers with 14 goals.\n\n\n=== 2013 African Footballer of the Year nomination ===\nOn 5 December 2013, the Confederation of African Football\'s (CAF) announced its reduced shortlist of ten nominees for the 2013 Player of the Year award. Aboutrika was one of the final ten nominees. The head coaches of the national football associations affiliated to CAF voted to decide the eventual winner of the award. The winner, Yaya Touré, was announced at the Glo-CAF Awards Gala on 9 January in Lagos, Nigeria.\n\n\n=== Retirement ===\nHe announced his retirement via Twitter on 20 December 2013, after Egypt failed to qualify for the 2014 FIFA World Cup in Brazil.\n\n\n== International career ==\n\n\n=== Summary ===\nAs of 19 November 2013, Aboutrika scored 38 goals in 100 matches for Egypt. He debuted against Estonia on 19 March 2001, but had to wait for 3 years to receive another call-up. His second call-up witnessed his first international goal against Trinidad and Tobago on 31 March 2004. He became an essential player since then, and scored 5 goals in his first 6 appearances with Egypt in 2004 and 2005. Aboutrika helped Egypt win two consecutive African Cup of Nations in 2006 and 2008 scoring the decisive penalty kick in the 2006 final match, and the only winning goal in the 2008 final. Also, he is the all-time top scorer of Egypt in the World Cup Qualifiers with 14 goals.\n\n\n=== 2006 FIFA World Cup Qualification ===\nAboutrika was an essential member of the Egyptian team at the 2006 FIFA World Cup qualifier. He scored 3 goals in the first 3 matches of the qualifiers. The first goal was against Sudan on 6 June 2004 in a 3–0 victory in Khartoum Stadium. The second goal

In [177]:
from langchain_text_splitters import NLTKTextSplitter
import nltk
nltk.download("punkt")
nltk.download('punkt_tab')

text_splitter = NLTKTextSplitter(
    chunk_size = 300,
    chunk_overlap = 50
)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [178]:
token_chunks = text_splitter.create_documents(documents , metadatas=metadatas)

WARNING:langchain_text_splitters.base:Created a chunk of size 339, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 545, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 329, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 449, which is longer than the specified 300

In [179]:
len(token_chunks)

174

In [180]:
token_chunks[5]

Document(metadata={'document': 'Mohamed salah'}, page_content='In his first season, he set the record for most Premier League goals scored (32) in a 38-game season and helped Liverpool to the 2018 Champions League final.')

#10. Embeddings

##10.1 Embedding with Gemini API

In [181]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from dotenv import dotenv_values
env_values = dotenv_values("./app.env")
gemini_api_key = env_values["GEMINI_API_KEY"]

In [182]:
embedding_llm = GoogleGenerativeAIEmbeddings(
    model = "models/text-embedding-004",
     google_api_key = gemini_api_key
)

In [183]:
vector = embedding_llm.embed_query("Hello World")

In [184]:
vector[:5]

[0.0141921565, -0.009106877, -0.04076159, 0.003782954, -0.00571815]

In [185]:
# embed multiple string at once
vectors = embedding_llm.embed_documents(
    [
        "Today is Monday",
        "Today is Tuesday",
        "Today is April Fools day"
    ]
)
len(vectors) , len(vectors[0])

(3, 768)

##Embedding Source Data

In [186]:
docs_1[0]

Document(metadata={'title': 'Mohamed Salah', 'summary': "Mohamed Salah Hamed Mahrous Ghaly (born 15 June 1992) is an Egyptian professional footballer who plays as a right winger or right midfielder for Premier League club Liverpool and captains the Egypt national team. He is widely regarded as one of the best players of his generation and one of the greatest wingers of all time. He is the all-time top foreign goalscorer in the Premier League and the all-time top African goalscorer in the UEFA Champions League.\nSalah began his senior career in 2010 at Al-Mokawloon, departing in 2012 to join Basel, where he won two Swiss Super League titles. In 2014, he joined Chelsea for a reported fee of £11 million, but limited gametime led to successive loans to Fiorentina and Roma, who later signed him permanently for €15 million. In the 2016–17 season, Salah was a key figure in Roma's unsuccessful title bid, reaching double figures in both goals and assists. In 2017, Salah moved to Liverpool for £36.9 million, a club record at the time. In his first season, he set the record for most Premier League goals scored (32) in a 38-game season and helped Liverpool to the 2018 Champions League final. Having formed a formidable attacking trio with Roberto Firmino and Sadio Mané, Salah went on to be an integral player in the club's Champions League and Premier League title successes in the following two seasons. He has since also won the FA Cup, EFL Cup, FA Community Shield, UEFA Super Cup and the FIFA Club World Cup. In the 2024–25 season, he won a second league title while breaking the record for the most goal contributions in a 38 game Premier League campaign. For his performances during the season, he won the PFA Players' Player of the Year award for a record-breaking third time.\nSalah's other individual accolades include three FWA Footballer of the Year awards, four Premier League Golden Boots, two Premier League Player of the Season awards, two Premier League Playmaker of the Season awards, finished third for the Best FIFA Men's Player in 2018 and 2021, and finished fourth in the 2025 Ballon d'Or, respectively. He received the 2018 FIFA Puskás Award for his winning strike in the first Merseyside derby of the 2017–18 season. In 2023, Salah became Liverpool's all-time top goalscorer in the history of the Premier League, and also became the fifth player to score 200 goals for the club. In 2025, he became Liverpool's third-highest goalscorer in the club's history behind Roger Hunt and Ian Rush.\nAt international level, Salah represented Egypt at youth level before making his senior debut in 2011. Following his performances at the 2012 Summer Olympics, he was named CAF Most Promising African Talent of the Year. Since then, he finished as runner-up in the 2017 and 2021 Africa Cup of Nations, and was top scorer during CAF qualification as Egypt qualified for the 2018 FIFA World Cup. Salah was named CAF African Footballer of the Year (2017 and 2018), BBC African Footballer of the Year (2017 and 2018), and was selected in the 2017 Africa Cup of Nations Team of the Tournament, 2021 Africa Cup of Nations Team of the Tournament and the CAF Team of the Year on several occasions.\nSalah is regarded as a symbol of national pride in Egypt for his achievements and was named in theTime magazine's list of the 100 Most Influential People in 2019. Salah has also been credited for raising the profile of Liverpool among Egyptians.", 'source': 'https://en.wikipedia.org/wiki/Mohamed_Salah'}, page_content='Mohamed Salah Hamed Mahrous Ghaly (born 15 June 1992) is an Egyptian professional footballer who plays as a right winger or right midfielder for Premier League club Liverpool and captains the Egypt national team. He is widely regarded as one of the best players of his generation and one of the greatest wingers of all time. He is the all-time top foreign goalscorer in the Premier League and the all-time top African goalscorer in the UEFA Champions League.\nSalah began his senior career in 2010 at Al-Mokawloon, departing in 2012 to join Basel, where he won two Swiss Super League titles. In 2014, he joined Chelsea for a reported fee of £11 million, but limited gametime led to successive loans to Fiorentina and Roma, who later signed him permanently for €15 million. In the 2016–17 season, Salah was a key figure in Roma\'s unsuccessful title bid, reaching double figures in both goals and assists. In 2017, Salah moved to Liverpool for £36.9 million, a club record at the time. In his first season, he set the record for most Premier League goals scored (32) in a 38-game season and helped Liverpool to the 2018 Champions League final. Having formed a formidable attacking trio with Roberto Firmino and Sadio Mané, Salah went on to be an integral player in the club\'s Champions League and Premier League title successes in the following two seasons. He has since also won the FA Cup, EFL Cup, FA Community Shield, UEFA Super Cup and the FIFA Club World Cup. In the 2024–25 season, he won a second league title while breaking the record for the most goal contributions in a 38 game Premier League campaign. For his performances during the season, he won the PFA Players\' Player of the Year award for a record-breaking third time.\nSalah\'s other individual accolades include three FWA Footballer of the Year awards, four Premier League Golden Boots, two Premier League Player of the Season awards, two Premier League Playmaker of the Season awards, finished third for the Best FIFA Men\'s Player in 2018 and 2021, and finished fourth in the 2025 Ballon d\'Or, respectively. He received the 2018 FIFA Puskás Award for his winning strike in the first Merseyside derby of the 2017–18 season. In 2023, Salah became Liverpool\'s all-time top goalscorer in the history of the Premier League, and also became the fifth player to score 200 goals for the club. In 2025, he became Liverpool\'s third-highest goalscorer in the club\'s history behind Roger Hunt and Ian Rush.\nAt international level, Salah represented Egypt at youth level before making his senior debut in 2011. Following his performances at the 2012 Summer Olympics, he was named CAF Most Promising African Talent of the Year. Since then, he finished as runner-up in the 2017 and 2021 Africa Cup of Nations, and was top scorer during CAF qualification as Egypt qualified for the 2018 FIFA World Cup. Salah was named CAF African Footballer of the Year (2017 and 2018), BBC African Footballer of the Year (2017 and 2018), and was selected in the 2017 Africa Cup of Nations Team of the Tournament, 2021 Africa Cup of Nations Team of the Tournament and the CAF Team of the Year on several occasions.\nSalah is regarded as a symbol of national pride in Egypt for his achievements and was named in theTime magazine\'s list of the 100 Most Influential People in 2019. Salah has also been credited for raising the profile of Liverpool among Egyptians.\n\n\n== Club career ==\n\n\n=== Al Mokawloon ===\nSalah started out playing for the youth setups of local teams Ittihad Basyoun and Othmason Tanta. He names Ronaldo, Zinedine Zidane and Francesco Totti as his childhood idols. In 2006, he joined the youth team of Al Mokawloon Al Arab aged 14 after being spotted by a scout who had originally come to watch another child play but was distracted by Salah. Salah frequently had to miss school to make the three-hour journey to training. When Salah was 15 he was noticed by first-team manager Mohamed Radwan, who moved him to the first-team squad immediately. Salah had to be given a special diet and training program due to his muscles not being fully formed because of his young age.\nSalah made his first-team debut on 3 May 2010 in the Egyptian Premier League, coming on as a substitute in a 1–1 away draw against El Mansoura. During the 2010–11 season Salah continued earning minutes on the pitch, eventually becoming a regular in the team. Even though he was getting regular game time, Salah struggled to score. In the dressing room after matches he would sometimes be in tears because of this, and Radwan says it only motivated him to become better. He scored his first goal for them on 25 December 2010 in a 1–1 away draw against Al Ahly. He remained a regular for Al Mokawloon, appearing in every game of the 2011–12 season. Following the Port Said Stadium riot on 1 February 2012, the Egyptian Premier League was suspended, and on 10 March, the Egyptian Football Association announced their decision to cancel the remainder of the season.\n\n\n=== Basel ===\n\n\n==== 2012–2013: Development and breakthrough ====\n\nSwiss Super League club Basel had been monitoring Salah for some time, so following the Egyptian Premier League suspension, the club organised a friendly match with the Egypt national under-23 team. The match took place on 16 March at the Stadion Rankhof in Basel, and despite only playing the second half, Salah scored twice, helping the Egyptians to a 4–3 win. Basel subsequently invited Salah to remain in the city for a week\'s training. On 10 April 2012, it was announced that Salah had signed for Basel on a four-year contract starting from 15 June 2012. He initially found it difficult to settle, having arrived unable to speak the language and been signed as a replacement for Xherdan Shaqiri. Salah scored on his unofficial debut on 23 June 2012 against FCSB during a friendly match, a 4–2 defeat. He made his official Basel debut in a UEFA Champions League preliminary stage match against the Norwegian club Molde on 8 August, coming on as a substitute in the 74th minute. He made his league debut on 12 August against Thun, playing the full match.\nHe scored his first league goal a week later, the second goal in a 2–0 home win against Lausanne-Sport. Salah scored his first UEFA Europa League goal in the quarter-finals on 11 April 2013, as Basel advanced to the semi-finals by beating Tottenham Hotspur 4–1 in a penalty shoot-out after a 4–4 aggregate draw. In the semi-final on 2 May, Salah scored away to Chelsea, although Basel were beaten 5–2 on aggregate. Despite late disappointment in Europe, Basel won the 2012–13 Swiss Super League title and finished runners-up in the Swiss Cup.\n\n\n==== 2013–2014: Final season and league championship ====\nAhead of the 2013–14 Swiss Super League season, Salah was a member of the Basel team that won the 2013 Uhrencup. Salah scored in his first league appearance of the season against Aarau on 13 July 2013. He scored his first Champions League goal a month later against Maccabi Tel Aviv on 6 August 2013 in the third qualifying round. Salah was the subject of major controversy following the game, after he appeared to deliberately avoid shaking hands with the players of the Israeli club in both the home and away legs.\nHe scored twice against the Bulgarian league champions PFC Ludogorets Razgrad on 21 August 2013 in the play-off round. On 18 September 2013, Salah scored the equaliser against Chelsea in the 2–1 away win during the group stage. During the return tie on 26 November at St. Jakob-Park, Salah scored the winning goal as Basel beat Chelsea for the second time with a 1–0 home win. However, he was unable to prevent Basel being eliminated in the group stage.\nOn the domestic stage, Salah continued to perform. Scoring four goals in 18 games, including a double against title rivals Young Boys, he helped Basel win the league title for the fifth time in a row.\nOn 23 January 2014, it was announced that Salah would leave Basel. During his time with the club, Salah played a total of 79 games for Basel, scoring a total of 20 goals. 47 of these games were in the Swiss Super League, six in the Swiss Cup, and 26 in UEFA competitions (Champions League and Europa League). He scored nine goals in the domestic league, four in the cup, and seven in European matches.\n\n\n=== Chelsea ===\n\n\n==== 2014 ====\nOn 23 January 2014, Premier League club Chelsea announced that a deal had been agreed with Basel to sign Salah for a fee reported to be in the region of £11 million. Three days later the transfer was completed, making him the first Egyptian to sign for the London-based club. Liverpool had been interested in Salah, and had made an offer of £11 million but were beaten to his signature by Chelsea.\nOn 8 February, Salah made his debut for Chelsea in the Premier League, coming on as a substitute in the 3–0 win over Newcastle United. Seven games later, on 22 March, Salah scored his first goal for Chelsea against Arsenal in the London derby, coming on as a substitute for Oscar, in a match which ended as a 6–0 home win. Then, on 5 April, Salah opened the scoring and later won a penalty and assisted the third goal in Chelsea\'s 3–0 win over Stoke City.\n\n\n==== 2014–2015 ====\n\nBefore the 2014–15 season, Salah\'s future with Chelsea looked to be in doubt after reports suggested he could be forced to return to Egypt to carry out military service after his registration for an education scheme was rescinded by the Egyptian Minister of Higher Education. He was spared from military service after a meeting with Egyptian prime minister Ibrahim Mahlab, the Minister of Higher Education, and the Egypt national team manager Shawky Gharieb. Salah changed squad numbers from 15 to 17 for the start of the season, with his new number having been vacated by Eden Hazard changing to number 10.\nSalah was rarely used during the season, making just three Premier League, two Champions League and three cup appearances, failing to score in any of them. On 28 October 2014, after a poor performance in a 2–1 win away to League Two team Shrewsbury Town in the fourth round of the League Cup, he and fellow winger André Schürrle were criticised publicly by manager José Mourinho. Although Salah only made three league appearances before his loan move to Fiorentina, Mourinho stated that he would receive a replica winner\'s medal from the club for his contributions that season.\n\n\n==== 2015: Loan to Fiorentina ====\n\nOn the transfer deadline day, 2 February 2015, Chelsea confirmed that Salah would join Italian club Fiorentina on an 18-month loan until the end of the 2015–16 season, as part of a transfer deal which saw Juan Cuadrado moving in the opposite direction. Six days after signing, he made his debut coming off the bench in the 65th minute as a replacement for Joaquín in a 3–2 home victory against Atalanta in Serie A. Salah chose the number 74 shirt in honour of the victims of the Port Said Stadium riot.\nSalah made his first start for Fiorentina on 14 February against Sassuolo, scoring his first goal for the club in the 30th minute. He then provided an assist to Khouma Babacar just two minutes after scoring; the match ended in a 3–1 win for Fiorentina. Twelve days later, Salah scored his first European goal for Fiorentina, as his side advanced to the round of sixteen of the Europa League, beating Tottenham 3–1 on aggregate. Salah scored the winning goal for Fiorentina against Inter Milan on 1 March, his third goal in Serie A. Four days after that, Salah scored both of Fiorentina\'s goals in their 2–1 win away to Juventus in the Coppa Italia semi-final first leg. At the end of the season, Fiorentina activated an option to make the loan move permanent, but Salah refused the move. Even though the loan agreement was for 18 months, Salah refused to return to Fiorentina and instead joined fellow Serie A club Roma. On 11 September, Fiorentina filed a complaint to FIFA, claiming that Chelsea had breached the agreed contract when they allowed Salah to join Roma on loan. The Court of Arbitration for Sport cleared Salah and Chelsea of any wrongdoing.\n\n\n==== 2015–2016: Loan to Roma ====\nOn 6 August 2015, Salah joined Roma on a season-long loan for €5 million; with the option to make the deal permanent, for a reported €15 million. He wore the number 11 shirt. He made his debut on 22 August, as the new season began with a 1–1 draw away Hellas Verona. On 20 September, Salah scored his first goal of the season against Sassuolo to help Roma salvage a point as the match ended in a 2–2 draw. He went on to score in his following two matches, a 2–1 loss against Sampdoria and a 5–1 win against Carpi. On 25 October, Salah scored the opener against his former club Fiorentina in a 2–1 away victory to help earn a fourth straight league win for Roma. On his return, Salah was also sent off after picking up a second yellow in the closing minutes of the match, just seconds after picking up his first yellow. On 4 November, he scored the opening goal of a 3–2 Champions League win over Bayer Leverkusen.\nOn 4 March, he faced his former side Fiorentina again and scored another double as Roma won 4–1 and broke into the top three. Salah would go onto score another three goals that season, scoring against Bologna, Genoa, and AC Milan, the latter on the final day. In the 2015–16 season, Salah scored 15 goals in 42 matches as Roma finished in third place in Serie A and qualified for the Champions League. In June, it was announced that Salah won the club\'s 2015–16 Player of the Season award.\n\n\n=== Roma ===\n\n\n==== 2016–2017: Permanent transfer, Serie A runner-up ====\nOn 3 August 2016, Roma announced the signing of Salah on a permanent deal for €15 million. He scored his first goal of the season in a 4–0 win over Udinese in the opening game of the season on 20 August. On 6 November, Salah scored a hat-trick in a 3–0 win over Bologna, his first club career hat-trick. However, a ruptured ankle ligament kept him out for the first half of December. He returned as a half-time substitute in a 1–0 defeat against title rivals Juventus on 17 December. Salah then endured a two-month period without a goal, he broke his drought on 19 February, scoring against Torino in a 4–1 win. On 9 March, he scored Roma\'s opening goal in an eventual 4–2 defeat to Lyon in the first leg of the round of sixteen in the 2016–17 Europa League. Despite winning the second leg 2–1, they were unable to turn the tie around and were knocked out 5–4 on aggregate. On 28 May, in the final game of the season, Salah was substituted for captain Francesco Totti, who was playing his final game with the club, in a 3–2 win over Genoa. Roma finished the season in second, just four points behind champions Juventus. Salah scored 19 goals in all competitions.\n\n\n=== Liverpool ===\n\n\n==== 2017–2018: Record-breaking individual success ====\n\nOn 22 June 2017, Salah agreed a transfer to Premier League club Liverpool. He signed a long-term contract with the Reds for an initial £36.5m fee that could rise to £43m. The fee was a club record, eclipsing the £35m spent on Andy Carroll in 2011. He was assigned the number 11 shirt previously worn by Roberto Firmino who instead switched to number 9. He joined the club on 1 July upon the opening of the summer transfer window, becoming Liverpool\'s first Egyptian player, and scored on his Premier League debut against Watford in a 3–3 away draw on 12 August. On 24 August, Salah scored his second goal for Liverpool, in a 2017–18 Champions League play-off round 4–2 win (6–3 agg) against 1899 Hoffenheim, his first goal at Anfield. Three days later, Salah scored and assisted a goal in a 4–0 victory over Arsenal. For his performances in August, Salah was awarded Player of the Month by Liverpool supporters. On 17 October, Salah netted twice in a 7–0 Champions League win over Maribor, helping Liverpool to the joint-largest ever away win in the competition, and the largest away win by an English club.\n\nOn 26 November 2017, Salah scored the opener and refused to celebrate in a 1–1 home draw with his former team Chelsea out of respect for the club as well as victims of the Sinai mosque attack two days earlier. Salah rose the top of the Premier League goalscoring charts by scoring twice after coming on as a substitute away at Stoke City on 29 November in a 3–0 win. The following month, Salah netted in a 4–0 win over Bournemouth; a

In [187]:
token_chunks[5]

Document(metadata={'document': 'Mohamed salah'}, page_content='In his first season, he set the record for most Premier League goals scored (32) in a 38-game season and helped Liverpool to the 2018 Champions League final.')

In [188]:
docs_text = [chunk.page_content for chunk in token_chunks]

In [189]:
docs_embeddings = embedding_llm.embed_documents(docs_text)

In [190]:
docs_text[5]

'In his first season, he set the record for most Premier League goals scored (32) in a 38-game season and helped Liverpool to the 2018 Champions League final.'

##Query Embedding

In [191]:
query = "Can You Tell me Which is the frist Team That Mohammed Salah Played For"

In [192]:
query_embedding = embedding_llm.embed_query(query)
query_embedding[:5]

[-0.025411913, 0.010051718, -0.04284002, 0.0014236755, 0.05462529]

##10.2 Embedding with HuggingFace

In [193]:
from sentence_transformers import SentenceTransformer
model =  SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [194]:
query_embeddings = model.encode(query)

In [195]:
vector[:5]

[0.0141921565, -0.009106877, -0.04076159, 0.003782954, -0.00571815]

##10.3 Embedding with Cohere

In [196]:
from dotenv import dotenv_values
env_values = dotenv_values("app.env")
cohere_api_key = env_values['COHERE_API_KEY']

In [197]:
from langchain_community.embeddings.cohere import CohereEmbeddings
embedding_llm = CohereEmbeddings(cohere_api_key = cohere_api_key , user_agent = "langchain")

/tmp/ipython-input-139777362.py:2: LangChainDeprecationWarning: The class `CohereEmbeddings` was deprecated in LangChain 0.0.30 and will be removed in 1.0. An updated version of the class exists in the `langchain-cohere package and should be used instead. To use it run `pip install -U `langchain-cohere` and import as `from `langchain_cohere import CohereEmbeddings``.
  embedding_llm = CohereEmbeddings(cohere_api_key = cohere_api_key , user_agent = "langchain")

In [198]:
token_chunks[4]

Document(metadata={'document': 'Mohamed salah'}, page_content="In the 2016–17 season, Salah was a key figure in Roma's unsuccessful title bid, reaching double figures in both goals and assists.\n\nIn 2017, Salah moved to Liverpool for £36.9 million, a club record at the time.")

In [199]:
## Source Data
docs_text = [ chunk.page_content for chunk in token_chunks]
docs_embeddings = embedding_llm.embed_documents(docs_text)

In [200]:
docs_text[4]

"In the 2016–17 season, Salah was a key figure in Roma's unsuccessful title bid, reaching double figures in both goals and assists.\n\nIn 2017, Salah moved to Liverpool for £36.9 million, a club record at the time."

In [201]:
#Query Embedding
query_text = "How many  and which clubs that salah played for it?"
query_embeddings = embedding_llm.embed_query(query_text)

In [202]:
print(query_embeddings)

[0.5625, -0.6508789, -0.28808594, 1.875, 3.0175781, -0.19799805, -1.2675781, -1.2792969, 3.4296875, -0.88964844, 0.66503906, 1.7148438, -0.8979492, -1.2460938, 0.69873047, 0.3239746, -1.7861328, -0.8964844, 1.8789062, 0.5991211, 0.9550781, 0.3955078, -0.29052734, 1.7910156, 1.4570312, 3.4355469, -0.9238281, -1.0585938, -0.6621094, 2.4023438, -2.6367188, 0.47753906, -2.5078125, -0.96533203, -1.84375, 0.37158203, -1.1533203, -0.14343262, 1.1445312, -0.93066406, -0.1463623, 0.625, -0.91503906, -0.94433594, 2.1933594, 0.4951172, 0.5097656, 2.1542969, -1.4599609, -0.32666016, -1.6416016, -0.06781006, 1.4638672, 1.6152344, -0.76464844, 0.4086914, -1.4316406, -1.5957031, -0.083862305, 0.2758789, -0.8535156, -0.3701172, -0.8413086, -2.0097656, -1.3808594, 2.1074219, -0.9057617, -0.6386719, -0.6459961, 0.088256836, -0.6191406, -0.27319336, 1.4746094, 0.3894043, -1.8300781, -1.7207031, -1.0078125, 0.48657227, -1.59375, 1.2539062, 0.70410156, 1.2519531, -1.2285156, -0.9658203, -0.6142578, -1.4580078, 0.89746094, 0.6894531, 0.6567383, -0.014526367, 0.9116211, -1.3330078, 0.6508789, -3.1210938, -0.26464844, -0.15319824, 2.8125, 0.04736328, -0.59228516, 1.5957031, 1.1933594, 1.0820312, -0.9604492, 0.18444824, -0.31201172, 1.0146484, -1.0087891, -1.0722656, 0.15893555, -1.3164062, 1.9570312, 0.9433594, -0.0637207, 2.4902344, 0.9584961, 1.0869141, -1.1005859, 1.0351562, -0.9692383, 0.7109375, 0.5932617, -2.4785156, 0.12756348, -0.7363281, 1.9863281, 0.6660156, -0.6933594, 0.08685303, 0.0028495789, 0.49658203, -2.0957031, 1.9365234, -2.0019531, 0.90527344, 3.2949219, -0.12658691, -1.6386719, -0.41357422, -0.25952148, -0.8198242, -0.75341797, -1.4072266, -0.16711426, -1.4150391, 1.8808594, -1.6923828, 1.1582031, 0.24694824, 1.0976562, -2.2167969, 1.8730469, -0.32202148, -0.4038086, -0.19934082, 0.8535156, -2.2167969, 1.8134766, -0.71777344, -1.1542969, -0.31591797, -0.29492188, 0.60498047, 1.5292969, -0.8276367, -1.2724609, 0.453125, 0.016601562, 0.7426758, -0.9536133, -0.7910156, -0.27246094, 0.6455078, 1.8232422, -0.7001953, -0.8803711, 0.46826172, -0.34326172, 0.93310547, -1.8320312, -1.6289062, -0.48828125, 1.3398438, 0.090270996, 0.1182251, -1.5556641, 1.1142578, 1.8945312, 0.4189453, 2.3984375, 0.3359375, 0.14172363, -1.1855469, -0.22460938, -1.5976562, -2.6464844, -0.9248047, -0.31982422, 0.19921875, 0.9086914, 0.9350586, -0.07751465, 2.1269531, 0.96435547, 1.3115234, 1.3769531, -0.18334961, 1.3300781, -1.1679688, 1.3115234, -0.46972656, 0.22351074, -0.61279297, -1.3886719, 0.02166748, 0.3095703, 3.2089844, 0.19750977, -0.6098633, 0.043945312, 0.06573486, -0.08483887, -2.6035156, -1.6152344, 0.6801758, -0.25610352, -1.0732422, 2.6210938, -0.5966797, -0.37329102, 2.1035156, 0.059631348, -1.8222656, 0.6044922, -2.1132812, -0.30444336, 1.1777344, -0.9189453, 0.6123047, -0.98339844, 0.11456299, -1.1914062, -1.4892578, -0.5341797, 0.8149414, 1.5351562, -2.1640625, -2.3769531, -0.8779297, 0.14196777, 0.3876953, -1.1679688, -0.15698242, -1.9833984, 1.5146484, -0.38842773, -0.36694336, 1.1826172, 0.14538574, -0.35375977, -2.0253906, 1.1435547, 1.4570312, 1.8730469, -0.046691895, -0.39160156, -2.3457031, -1.3134766, 0.6904297, 2.2128906, -2.7597656, 0.06652832, 0.6772461, -2.34375, 1.359375, 0.55126953, -0.09954834, -3.3769531, -0.13671875, 1.2978516, 1.5625, 0.63964844, 1.2949219, -0.12573242, 1.7392578, -0.6401367, -0.6098633, 2.9277344, 1.2753906, 3.2617188, 0.6899414, -0.47827148, -0.49194336, 2.2675781, 1.3076172, 0.5136719, -0.8833008, -1.0400391, 0.46240234, 1.9863281, 0.5498047, -0.6245117, 1.6777344, -3.0507812, 2.3261719, 1.5048828, 0.81689453, 0.4831543, 0.30322266, -1.0117188, 0.5708008, 0.16320801, 0.7763672, -3.5917969, -1.0058594, -0.08331299, 0.26220703, 0.5175781, -0.62841797, 1.1269531, 2.9394531, -0.4819336, -1.7871094, -0.80566406, 0.890625, -0.020019531, -1.71875, 0.0713501, -3.8242188, 1.0351562, -2.0195312, 0.7998047, 0.31030273, -0.12939453, 0.859375, -0.60058594, 0.2631836, 1.8798828, 1.9541016, -1.5419922, 1.1904297, -2.9785156, 0.7397461, 0.5151367, -0.9975586, -0.49243164, -0.8535156, -0.265625, -0.9819336, -0.7636719, -2.5351562, -1.1064453, 0.31640625, -1.484375, 0.27490234, 1.5634766, -0.2368164, 0.1496582, -0.8051758, -1.2402344, -0.47094727, -0.7080078, -0.5395508, -2.2617188, -2.2167969, 2.1425781, 0.43530273, 0.96777344, 1.3681641, 1.1074219, -0.6743164, -0.5449219, 2.3027344, -0.46777344, 0.3449707, 1.1865234, 0.86816406, -0.71777344, -0.35913086, -1.0136719, -1.0302734, -0.55810547, 1.1464844, -0.07727051, 0.17883301, 2.1679688, 1.5976562, -0.034118652, -0.45581055, 2.1914062, -0.3642578, 0.44921875, -0.70654297, -0.8208008, 2.3398438, 0.8066406, -1.1914062, -0.8730469, 0.765625, -0.103515625, -1.0976562, -0.35961914, -0.6557617, -0.44970703, -0.08557129, -0.8510742, -1.4238281, -1.8701172, -0.34399414, -0.18884277, 0.060546875, 0.6464844, 0.54345703, 1.3554688, -0.03302002, 1.2011719, 0.9321289, -0.2512207, 0.027160645, 0.52441406, -0.3623047, 1.7822266, -0.36987305, 0.81347656, 2.1289062, 1.8769531, -0.625, 0.00806427, -0.49072266, -0.6069336, 0.02809143, 1.1513672, -3.5410156, 1.1230469, 0.09106445, 0.38549805, -3.1855469, 1.0195312, 0.77783203, -0.48608398, 0.92626953, -1.96875, -1.2431641, 1.1679688, 2.7402344, -0.49487305, -2.5292969, 0.38110352, -0.9682617, -1.0117188, -1.9462891, -0.086242676, 1.7832031, 1.0517578, -1.3261719, -1.3730469, 0.6323242, -0.3076172, -1.1962891, -1.9667969, 0.035369873, -1.3769531, -0.26293945, -1.5869141, -0.91503906, 0.9277344, 0.33154297, 2.0644531, -0.06781006, -0.08648682, -2.1777344, -1.1416016, 0.9814453, -3.2539062, -0.08129883, -2.2910156, -0.17370605, 1.1787109, -1.0820312, -0.38378906, 2.0605469, -0.7495117, -1.3847656, -0.27905273, 1.2861328, -0.5283203, 0.09509277, -1.4550781, 1.9638672, 0.7661133, -0.4597168, 1.4111328, -0.35839844, 0.85253906, -0.31762695, -0.3383789, -1.9130859, 1.4072266, 1.1083984, 0.6176758, 0.1821289, -0.35058594, 0.7348633, -1.1914062, -0.26489258, -1.9912109, -3.7382812, -0.13354492, -1.1855469, 0.41308594, 1.2460938, 0.9140625, -1.0644531, -0.28027344, 1.6816406, -0.9819336, -0.18383789, 0.56591797, -1.5644531, -0.7138672, -1.5166016, 0.4091797, -1.7275391, -0.9614258, -0.57128906, 0.7739258, 1.5556641, 0.47216797, -0.14746094, -0.10101318, 2.2167969, 11.1171875, -2.6210938, 0.7133789, -1.0996094, 1.5869141, 1.8662109, 0.0914917, -1.6630859, 0.117492676, 3.0625, 1.8916016, -1.0615234, 0.7416992, -0.8183594, -3.1113281, -0.6455078, -1.2666016, 0.7416992, -0.4909668, 0.91748047, 0.02986145, -1.546875, -1.1025391, -0.08728027, 0.8330078, 0.94433594, 0.58691406, 1.0917969, 0.3779297, 0.093444824, 1.6992188, 1.8867188, 0.70751953, -0.21472168, -1.8730469, -3.3789062, 2.0917969, -0.7006836, 1.3789062, -0.13269043, -1.9628906, 0.33569336, 2.5449219, -0.30908203, -1.0527344, -0.7807617, 0.07019043, -0.328125, -1.1552734, -0.3947754, -0.67285156, 1.546875, -0.9604492, 0.70214844, 0.9238281, 0.021972656, -1.90625, 0.30810547, 1.2490234, -1.0322266, 1.3037109, 0.011642456, 0.9121094, 1.1152344, 0.15808105, 0.8232422, 0.095703125, 0.4675293, -1.0166016, 0.46923828, -0.24780273, -0.6845703, 0.036621094, -1.4257812, 0.4013672, -0.3503418, -0.3791504, -0.6923828, 2.6035156, 0.09240723, -0.91748047, 1.3212891, -1.1074219, -0.6894531, 0.9121094, -0.1829834, 0.9082031, -2.5136719, -0.31591797, -2.1132812, -0.6347656, 4.765625, -1.1445312, -0.9863281, 0.7963867, 0.6767578, -4.9960938, 2.4121094, 1.0019531, 1.7226562, -0.84277344, -1.2871094, -1.6826172, 0.5390625, -0.4621582, -0.4951172, 1.953125, 3.4414062, 0.4111328, 0.15490723, 0.5546875, 0.703125, -0.38452148, -0.6459961, -0.14282227, -1.1894531, -1.1728516, -2.3085938, -1.6582031, 1.2705078, 1.5712891, 0.018585205, 1.8759766, -1.296875, 1.0742188, -0.0541687, -1.1992188, -0.50439453, 0.88183594, 1.3232422, 0.19458008, -1.6738281, -1.1083984, -0.3256836, 0.13317871, 0.06317139, 1.2119141, 0.5551758, 0.8208008, -2.8027344, 0.75439453, 1.7197266, -1.5732422, -1.4794922, -0.093811035, 0.7993164, 0.3503418, 0.5415039, 0.1541748, -0.8417969, 1.1025391, 0.55566406, -0.6777344, 1.3994141, 0.6616211, -0.57470703, 1.4160156, -1.0068359, 0.5703125, 2.5859375, 0.2939453, 0.83496094, -0.62841797, 0.09515381, 0.22473145, -0.1850586, 1.2021484, 2.3261719, 1.3945312, -0.5888672, 2.0917969, 0.8701172, 1.1650391, 1.4199219, -1.1738281, -0.07055664, 0.2763672, 0.27856445, -1.7832031, 1.1630859, -1.4257812, -0.6220703, 0.7578125, 0.3503418, 1.5419922, 1.7617188, -2.2011719, 0.86376953, 0.4267578, 1.0322266, 2.2753906, 1.1181641, -1.5996094, -0.18359375, 1.2832031, -0.5703125, 0.9980469, 0.12561035, -0.16235352, -0.44580078, 1.2753906, 0.17907715, -2.0292969, 1.2265625, -1.1269531, -0.6748047, -1.2255859, -5.0, -1.3388672, -0.40478516, -2.1503906, -0.9067383, 0.29516602, -0.7792969, -0.84716797, 1.7646484, 1.8144531, 1.1865234, -0.54833984, -0.6303711, 2.6894531, -0.95214844, 0.13977051, -0.17602539, -1.2714844, 1.7910156, -0.3293457, 0.16015625, -0.7114258, 0.95751953, 0.9145508, 0.60009766, -0.43701172, -0.36376953, -0.20300293, 1.3759766, 0.9760742, 0.9638672, 3.3925781, 0.69628906, -0.0390625, -1.3964844, 0.6879883, -2.2675781, 1.4755859, -0.40771484, -0.43310547, 1.5732422, 0.28100586, -1.0751953, 0.8510742, 0.31518555, -0.80126953, 0.009712219, -1.0371094, -0.43920898, 0.24047852, -1.5175781, -0.2626953, -0.57714844, 0.29296875, -1.1162109, 3.8613281, -0.99121094, -1.0283203, 1.828125, -0.06817627, -0.9873047, -0.6152344, -1.9980469, 2.0371094, 4.015625, 3.8007812, 0.9506836, -1.90625, -0.8510742, 1.8369141, 0.8144531, -0.54589844, 1.6855469, 0.6821289, 0.2043457, 0.06384277, 0.5444336, -0.07940674, 0.52197266, 3.9375, 0.46118164, -6.3789062, -0.36816406, 0.9550781, 0.7558594, 0.08996582, -0.3293457, 0.29760742, 2.7890625, -1.0947266, -0.25927734, -0.1772461, -2.0605469, -1.5722656, -0.31274414, -0.13232422, 1.7490234, 0.36743164, 0.6015625, -0.06903076, -1.3330078, 0.0003004074, 0.032684326, -1.5302734, 3.1445312, 1.0449219, 0.5913086, 0.74560547, -1.7197266, 1.5615234, 0.8041992, 0.77001953, 2.2695312, 0.052856445, 2.3457031, 1.8193359, -0.21362305, -0.7607422, -4.0546875, -0.56689453, 0.3244629, 1.8544922, 1.0273438, 1.0644531, -1.3886719, -2.2890625, -1.5273438, -1.6044922, -2.0722656, -2.3046875, 2.0742188, -0.20129395, 0.12548828, -0.44702148, -0.4338379, -1.4589844, 0.9003906, -0.28833008, -1.5576172, 1.1474609, 0.6738281, 1.0234375, -1.1171875, 1.0332031, 0.34765625, -0.5751953, 3.6640625, -0.7050781, -0.5961914, 0.48486328, -0.50439453, -0.20654297, 0.61816406, -0.44262695, 0.25561523, -1.6669922, -0.7553711, 1.296875, 2.1015625, 0.17468262, -0.7675781, 0.8432617, 1.7861328, -0.5161133, 1.0263672, -1.0292969, -1.6992188, -0.07788086, -0.52246094, 0.36816406, 0.25463867, 1.3378906, 0.58154297, 0.3803711, 1.359375, -2.5097656, 0.9584961, -0.036499023, -0.74121094, -0.005519867, 0.7348633, -0.69970703, 1.6679688, -0.94091797, 1.1337891, -2.1269531, 1.2070312, -0.47045898, -0.8901367, -1.8222656, -1.9902344, 0.9501953, -0.4333496, -0.6611328, 1.2089844, -1.4570312, -0.7817383, 1.4023438, -1.6259766, 0.27514648, -0.9370117, 0.28125, 3.2773438, 0.35913086, 0.9824219, -0.22729492, 0.25341797, 0.2310791, -0.59277344, 3.3261719, -0.92529297, -1.3398438, -2.1328125, -0.80126953, 2.03125, 1.2089844, 1.6650391, 1.6113281, -1.3183594, 0.5336914, -0.89160156, 1.3349609, 1.1708984, 0.4333496, -0.75097656, -0.02557373, 1.3300781, 1.0898438, -2.3867188, -0.4807129, 2.8652344, -0.56689453, -1.7285156, 2.0214844, 0.9506836, -0.9951172, 0.8676758, -0.6791992, -0.8417969, 1.5371094, -0.8359375, 1.6318359, -0.9042969, -1.3837891, -1.1142578, -0.018539429, 0.6904297, 4.1953125, 0.58447266, -1.3291016, 2.1464844, -1.0488281, 0.94873047, -1.1308594, 1.8525391, 0.32788086, -0.7949219, -1.8789062, -0.19067383, -0.087646484, -2.1347656, -2.8261719, 2.1054688, 1.8769531, 0.6142578, -0.5395508, 1.8789062, 2.6875, -0.4729004, -1.3583984, -1.7919922, 1.4042969, 3.4257812, 0.37353516, 3.34375, -0.11920166, 0.18310547, 2.4335938, 0.03086853, 1.1943359, -0.0029716492, -1.9980469, 2.0410156, 0.9111328, 0.79785156, -0.5966797, 0.16723633, 0.7680664, 0.42016602, 0.9277344, 0.5126953, -0.70751953, 0.36889648, -1.8701172, -0.21557617, 2.5429688, 0.6323242, -1.8115234, -1.4628906, 1.0634766, 0.4104004, 1.0322266, 1.1904297, 1.2792969, 0.67626953, -2.0976562, -0.8745117, 2.3886719, -1.6152344, 0.8334961, 1.3144531, -0.5708008, 0.09466553, 0.7392578, -1.2333984, 0.5732422, 0.39697266, 0.2980957, -1.1669922, -0.10827637, -0.43115234, 1.6494141, 2.6875, -0.7001953, 1.2167969, 0.9921875, -1.2099609, -0.5888672, -1.9892578, 0.24023438, -2.0117188, -2.3867188, 0.5053711, 0.07141113, -0.47827148, -0.4777832, 1.4150391, -2.2636719, -0.27929688, -0.28759766, 0.1227417, 1.5986328, 1.5205078, 0.0491333, 0.01612854, 0.3762207, 0.21154785, -2.6152344, -0.28100586, 1.9433594, -2.7226562, 0.40283203, -2.5332031, -1.0664062, 0.111694336, -1.6464844, 0.12646484, 1.0830078, 0.45874023, 2.3789062, -0.7915039, -0.8364258, 2.7265625, 1.2148438, -1.4414062, -0.8383789, 1.0263672, 2.2167969, -1.2119141, -2.6230469, 0.4182129, 0.3708496, 0.9658203, 1.5576172, -0.23266602, 2.3789062, -1.265625, -0.7739258, -1.2226562, 1.03125, -0.18701172, 0.1751709, 0.4794922, 0.4946289, -1.6943359, 1.1894531, 1.2705078, -1.2607422, -1.6416016, 0.8022461, -1.5957031, 2.1523438, 0.19592285, -0.73095703, 0.1998291, -0.65625, 2.0703125, -0.52685547, 1.2861328, 0.5703125, 0.17578125, 1.1445312, -1.0625, 0.35131836, -1.6572266, -0.98876953, 0.17993164, 2.5585938, 1.9384766, -1.109375, -0.9941406, 0.54345703, -0.15563965, 0.58154297, 1.3076172, 1.4179688, 1.140625, 0.7675781, -3.1738281, 2.1367188, -0.095825195, -0.23291016, -1.4169922, 1.7705078, 0.044158936, 2.7011719, -0.28198242, 1.3164062, 0.63720703, -1.2050781, -1.6494141, 1.1875, 1.9638672, 0.5239258, -0.9589844, -1.7607422, -0.074645996, -1.2597656, -2.5625, -1.0234375, 0.19091797, 0.5371094, 1.1416016, -2.6972656, -0.42822266, 0.16589355, -2.0175781, -1.2333984, -0.92871094, 1.4951172, -0.7392578, -2.3710938, 0.026290894, 0.40478516, 0.26733398, 0.7470703, 1.203125, 2.4472656, 0.31201172, 0.3022461, 1.5, -0.18945312, -0.49609375, -0.9628906, 1.3486328, -0.030029297, -0.28198242, 2.2363281, -0.37158203, -0.015098572, 1.6572266, 1.2568359, 1.3535156, -1.53125, 0.20825195, 0.72314453, 2.7910156, 1.6738281, 0.40966797, -1.1210938, 0.52490234, -0.23095703, -1.8632812, 0.23376465, -0.59472656, 0.28759766, 0.43310547, -0.09265137, -0.61083984, -1.8085938, -0.7480469, -1.3652344, -0.52490234, -1.0722656, -2.9804688, -1.1835938, -1.3554688, 0.9375, 0.37280273, 0.10192871, 0.4165039, 1.7900391, -0.9511719, 2.0390625, -2.3066406, 0.7651367, -0.28149414, 0.84375, 1.2050781, 0.3005371, -1.8681641, -1.0214844, -0.9628906, -0.14538574, -1.0634766, 1.0996094, 0.42993164, -0.5410156, 0.30126953, 0.9838867, -0.6977539, 2.6132812, 1.1728516, -1.0058594, 0.3786621, -0.0050315857, -1.8007812, -1.1464844, 0.4909668, 3.8710938, 1.6210938, 1.3769531, -1.7324219, 1.3603516, 0.14770508, -3.1035156, -2.2304688, -1.8505859, 2.4199219, -0.96875, -0.6123047, -1.6308594, 2.3613281, -2.3789062, 4.4609375, 0.5263672, -0.30249023, 1.5742188, -0.24890137, 2.1914062, -0.49951172, 2.1757812, 2.1269531, -0.08270264, 2.0976562, 2.0859375, 1.7988281, -1.3134766, -0.3190918, 0.22277832, -2.5820312, -1.0244141, -1.9794922, 0.18383789, -0.10046387, 0.027038574, 0.2454834, -0.9453125, -0.20812988, -2.4648438, 0.1652832, 0.4296875, -0.33081055, -1.8173828, 1.0380859, -1.6933594, -0.21008301, 0.3647461, 0.18115234, -0.4296875, -2.109375, 0.5029297, 0.38720703, -0.9814453, 2.8515625, -1.140625, 1.2832031, -0.39990234, 0.5654297, 0.85839844, -0.8310547, -0.59814453, 3.65625, -0.37719727, -0.25756836, -0.46191406, 1.4414062, 0.7910156, -2.2988281, -1.6884766, -1.5117188, -0.23803711, 0.37109375, 2.3652344, 0.11682129, 0.16552734, 0.41235352, -0.23840332, -1.1103516, 1.5888672, -2.6113281, 1.2597656, 0.58691406, -0.19873047, 2.9335938, 0.058532715, -0.4519043, -0.6933594, 4.015625, -0.1027832, -1.3427734, -0.37451172, -0.73876953, -0.94873047, -0.25634766, 1.9902344, 0.53027344, 1.6318359, 0.6660156, 1.4570312, 0.5317383, -2.2890625, -0.3544922, -2.5605469, 0.22644043, -0.8701172, -1.4462891, 4.1015625, -1.4326172, 0.2064209, 1.3769531, -0.89501953, -0.62939453, 0.48339844, 0.3791504, 0.4116211, 1.2363281, 0.34887695, -2.8847656, 0.83496094, -1.2050781, 0.3010254, 2.1445312, 0.20141602, -0.35205078, -1.4257812, -0.37329102, 0.48339844, 0.049346924, -3.0273438, 1.1835938, 1.7763672, 2.6171875, 1.2675781, -0.875, -1.6728516, 1.5449219, 0.27172852, 1.6113281, -0.2109375, 1.7617188, -0.8754883, -1.7041016, -0.49194336, 1.6132812, -0.3413086, -1.5917969, -1.3017578, 0.68310547, -0.6088867, 0.63623047, 0.76220703, 0.9838867, 0.8774414, -1.3554688, 1.953125, 0.9746094, -0.5292969, -1.5507812, -0.7524414, -1.2636719, -4.671875, 0.5786133, -1.7597656, 0.40063477, -0.9770508, -0.9824219, -0.7294922, -1.0117188, 1.7177734, 0.3137207, 0.036132812, 2.3085938, 0.13537598, 0.50341797, 0.46362305, 0.4345703, 0.093811035, 2.1621094, -0.6616211, 1.6103516, 0.16809082, 0.17797852, 1.2167969, -0.7285156, -0.58935547, 0.4074707, -1.5361328, -1.8017578, -2.3496094, 0.92089844, -0.9433594, -1.6914062, 0.8442383, -0.56347656, 0.7026367, -0.7163086, -1.2207031, 0.7241211, 0.26416016, -0.3486328, -1.0205078, -2.5332031, -1.0703125, 0.6040039, -1.7597656, -0.5966797, -1.671875, 1.7763672, -0.059509277, -0.07128906, -0.9746094, -0.015731812, 0.26391602, -0.5678711, 1.0058594, 0.24133301, -1.2900391, 0.2932129, -0.3479004, -0.6533203, -1.8330078, 1.3681641, 1.0048828, 2.5292969, -3.1699219, 0.029037476, -2.3203125, -0.7270508, -0.7578125, -0.6665039, 0.016906738, 0.6064453, 0.10961914, -0.6723633, -0.36206055, 2.1328125, -2.6289062, -2.8867188, 1.0908203, -0.2290039, 0.90185547, -1.3125, -0.14379883, 0.8515625, -0.75097656, 0.9482422, -2.1015625, -0.6923828, -2.25, 1.4443359, -0.47094727, -0.42797852, 3.4082031, -2.5664062, -0.42700195, 8.296875, 0.2631836, -0.48706055, -0.24108887, 0.5722656, 1.0244141, -0.0051841736, -0.23486328, -0.1517334, -0.30371094, -1.7861328, -0.9980469, -0.60058594, -0.82470703, -1.2646484, -0.5878906, 0.19616699, -1.2333984, -4.4609375, 1.6503906, -1.2246094, -0.2927246, -1.1708984, 0.057006836, 0.5932617, 1.6728516, 1.4433594, 2.4980469, 0.059936523, 1.2539062, 1.5253906, 1.1259766, 0.15637207, 2.2402344, 0.7114258, 1.2021484, -0.98339844, 1.4824219, -0.7241211, -0.7441406, -1.0839844, -1.6630859, 0.7558594, -0.6376953, 1.4833984, 1.2666016, 1.7978516, 0.8984375, -0.01878357, 0.07116699, 0.44628906, -1.6181641, -1.359375, 3.1953125, 0.2388916, 0.85498047, -0.45166016, 0.1796875, -4.1484375, 0.7109375, 0.33251953, -1.4550781, 0.36889648, -0.9614258, -1.4980469, -0.031677246, -3.1953125, 0.2919922, 1.0498047, -1.2802734, -2.0136719, -0.46923828, 0.7636719, -0.5024414, -0.34350586, 0.48046875, 1.0820312, -1.3789062, -1.3964844, -0.14282227, 3.2851562, -2.6542969, -2.2070312, -1.265625, -1.4824219, 0.9785156, 0.06036377, 0.37890625, 2.0136719, -1.9667969, -0.05697632, -0.67871094, -0.19128418, -0.6928711, -1.4628906, 0.9663086, 3.2714844, 0.07312012, 0.3942871, 0.35986328, -0.008560181, 0.91748047, 1.4482422, 1.5263672, -0.12017822, 0.11456299, -0.46850586, -1.3212891, 0.5620117, -0.7895508, -0.037719727, 1.5205078, -3.1757812, 0.3293457, 0.120788574, 0.6279297, -0.32421875, 2.3789062, 2.7148438, -2.5351562, -1.0654297, -3.2109375, -1.2041016, -0.28442383, -1.8925781, 0.8935547, 0.52441406, -0.38378906, -1.6269531, -2.2734375, 0.3942871, 0.5019531, -0.36450195, 0.7680664, 0.43530273, 0.42285156, 0.6982422, 2.0878906, -1.0722656, -2.4648438, -0.45703125, -1.4277344, 1.0117188, 0.9213867, -1.3867188, 0.8823242, -0.9658203, -1.6083984, 1.1289062, -0.6376953, 1.0292969, -0.828125, 1.2324219, -0.09484863, -0.29492188, 0.44189453, -2.1015625, 0.9614258, -1.4160156, -1.4072266, -1.2177734, -1.1230469, -1.8925781, -0.7050781, -2.0644531, -1.0449219, 0.042510986, 1.5263672, -2.5429688, 0.5419922, 2.6894531, -1.5791016, -0.6767578, -0.42016602, 0.89746094, 1.3603516, -0.5371094, 4.

In [203]:
len(docs_embeddings[2])

4096

#11. Vector Database

In [204]:
from langchain_community.document_loaders import WikipediaLoader
from langchain_text_splitters import NLTKTextSplitter
import nltk
nltk.download('punkt')
from langchain_google_genai import GoogleGenerativeAIEmbeddings

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [205]:
query = "Nikola Tesla"

docs = WikipediaLoader(
    query = query,
    load_max_docs = 1,
    doc_content_chars_max = 20_000
).load()

In [206]:
document_1 = docs[0].page_content

In [207]:
document_1

'Nikola Tesla (10 July 1856 – 7 January 1943) was a Serbian-American engineer, futurist, and inventor. He is known for his contributions to the design of the modern alternating current (AC) electricity supply system.\nBorn and raised in the Austrian Empire, Tesla first studied engineering and physics in the 1870s without receiving a degree. He then gained practical experience in the early 1880s working in telephony and at Continental Edison in the new electric power industry. In 1884, he migrated to the United States, where he became a naturalized citizen. He worked for a short time at the Edison Machine Works in New York City before he struck out on his own. With the help of partners to finance and market his ideas, Tesla set up laboratories and companies in New York to develop a range of electrical and mechanical devices. His AC induction motor and related polyphase AC patents, licensed by Westinghouse Electric in 1888, earned him a considerable amount of money and became the cornerstone of the polyphase system, which Westinghouse marketed.\nTesla conducted a range of experiments with mechanical oscillators/generators, electrical discharge tubes, and early X-ray imaging among other things, in an attempt to develop inventions he could patent and market. He built a wirelessly controlled boat, one of the first wirelessly controlled vehicles ever produced. Tesla became well known as an inventor and demonstrated his achievements to celebrities and wealthy patrons at his lab. He was noted for his showmanship at public lectures. Throughout the 1890s, Tesla pursued his ideas for wireless lighting and worldwide wireless electric power distribution in his high-voltage, high-frequency power experiments in New York and Colorado Springs. In 1893, he made pronouncements on the possibility of wireless communication with his devices. Tesla tried to put these ideas to practical use in his unfinished Wardenclyffe Tower project, an intercontinental wireless communication and power transmitter, but ran out of funding before he could complete it.\nAfter Wardenclyffe, Tesla experimented with a series of inventions in the 1910s and 1920s with varying degrees of success. Having spent most of his money, Tesla lived in a series of New York hotels, leaving behind unpaid bills. He died in New York City in January 1943. Tesla\'s work fell into relative obscurity following his death, until 1960, when the General Conference on Weights and Measures named the International System of Units (SI) measurement of magnetic flux density the tesla in his honor. There has been a resurgence in popular interest in Tesla since the 1990s. In 2013, Time named Tesla one of the 100 most significant figures of all time.\n\n\n== Early years ==\n\n\n=== Childhood ===\n\nNikola Tesla was born on 10 July 1856 in the village of Smiljan, in the Military Frontier of the Austrian Empire (present-day Croatia) into an ethnic Serb family. His father, Milutin Tesla (1819–1879), was a priest of the Eastern Orthodox Church. His father\'s brother Josif was a lecturer at a military academy who wrote several textbooks on mathematics.\nTesla\'s mother, Georgina "Đuka" Mandić (1822–1892), whose father was also an Eastern Orthodox priest, had a talent for making home craft tools and mechanical appliances and the ability to memorize Serbian epic poems. Đuka had never received a formal education. Tesla credited his eidetic memory and creative abilities to his mother\'s genetics and influence.\nTesla was the fourth of five children. In 1861, Tesla attended primary school in Smiljan where he studied German, arithmetic, and religion. In 1862, the Tesla family moved to the nearby town of Gospić, where Tesla\'s father worked as parish priest. Nikola completed primary school, followed by middle school. Later in his patent applications, before he obtained American citizenship, Tesla would identify himself as "of Smiljan, Lika, border country of Austria-Hungary".\n\n\n=== Education ===\n\nIn 1870, Tesla moved to Karlovac to attend high school at the Higher Real Gymnasium where the classes were held in German, as it was usual throughout schools within the Austro-Hungarian Military Frontier. Tesla later wrote that he became interested in his physics professor\'s demonstrations of electricity. The "mysterious phenomena" made him want "to know more of this wonderful force". He was able to perform integral calculus in his head, prompting his teachers to believe that he was cheating. He finished a four-year term in three years, graduating in 1873.\nAfter graduating Tesla returned to Smiljan but soon contracted cholera, was bedridden for nine months and was near death several times. In a moment of despair, Tesla\'s father (who had originally wanted him to enter the priesthood), promised to send him to the best engineering school if he recovered from the illness. Tesla later said that he had read Mark Twain\'s earlier works while recovering from his illness.\nThe next year Tesla evaded conscription into the Austro-Hungarian Army in Smiljan by running away southeast of Lika to Tomingaj, near Gračac. There he explored the mountains wearing hunter\'s garb. Tesla said that this contact with nature made him stronger, both physically and mentally. He enrolled at the Imperial-Royal Technical College in Graz in 1875 on a Military Frontier scholarship. Tesla passed nine exams (nearly twice as many as required) and received a letter of commendation from the dean of the technical faculty to his father, which stated, "Your son is a star of first rank." At Graz, Tesla was fascinated by the lectures on electricity presented by professor Jakob Pöschl. But by his third year he was failing in school and never graduated, leaving Graz in December 1878. One biographer suggests Tesla was not studying and may have been expelled for gambling and womanizing.\n\nTesla\'s family did not hear from him after he left school. There was a rumor among his classmates that he had drowned in the nearby river Mur but in January one of them ran into Tesla in the town of Maribor and reported that encounter to Tesla\'s family. It turned out Tesla had been working there as a draftsman for 60 florins per month. In March 1879, Milutin finally located his son and tried to convince him to return home and take up his education in Prague. Tesla returned to Gospić later that month when he was deported for not having a residence permit. Tesla\'s father died the next month, on 17 April 1879, at the age of 60 after an unspecified illness.\nIn January 1880, two of Tesla\'s uncles paid for him to leave Gospić for Prague, where he was to study. He arrived too late to enroll at Charles-Ferdinand University; he had never studied Greek, a required subject; and he was illiterate in Czech, another required subject. He attended lectures in philosophy at the university as an auditor, but he did not receive grades for the courses.\n\n\n=== Budapest Telephone Exchange ===\nTesla moved to Budapest, Hungary, in 1881 to work under Tivadar Puskás at a telegraph company, the Budapest Telephone Exchange. Upon arrival, Tesla realized that the company, then under construction, was not functional, so he worked as a draftsman in the Central Telegraph Office instead. Within a few months, the Budapest Telephone Exchange became functional, and Tesla was allocated the chief electrician position. Tesla later described how he made many improvements to the Central Station equipment including an improved telephone repeater or amplifier.\n\n\n== Working at Edison ==\nIn 1882, Tivadar Puskás got Tesla another job in Paris with the Continental Edison Company. Tesla began working in what was then a brand new industry, installing indoor incandescent lighting citywide in large scale electric power utility. The company had several subdivisions and Tesla worked at the Société Electrique Edison, the division in the Ivry-sur-Seine suburb of Paris, in charge of installing the lighting system. There he gained a great deal of practical experience in electrical engineering. Management took notice of his advanced knowledge in engineering and physics, and soon had him designing and building improved versions of generating dynamos and motors. \n\n\n=== Moving to the United States ===\n\nIn 1884, Edison manager Charles Batchelor, who had been overseeing the Paris installation, was brought back to the United States to manage the Edison Machine Works, a manufacturing division situated in New York City, and asked that Tesla be brought to the United States as well. In June 1884, Tesla emigrated and began working almost immediately at the Machine Works on Manhattan\'s Lower East Side, an overcrowded shop with a workforce of several hundred machinists, laborers, managing staff, and 20 "field engineers" struggling with the task of building the large electric utility in that city. As in Paris, Tesla was working on troubleshooting installations and improving generators. \nHistorian W. Bernard Carlson notes Tesla may have met company founder Thomas Edison only a couple of times. One of those times was noted in Tesla\'s autobiography where, after staying up all night repairing the damaged dynamos on the ocean liner SS Oregon, he ran into Batchelor and Edison, who made a quip about their "Parisian" being out all night. After Tesla told them he had been up all night fixing the Oregon, Edison commented to Batchelor that "this is a damned good man". One of the projects given to Tesla was to develop an arc lamp–based street lighting system. Arc lighting was the most popular type of street lighting but it required high voltages and was incompatible with the Edison low-voltage incandescent system, causing the company to lose contracts in some cities. Tesla\'s designs were never put into production, possibly because of technical improvements in incandescent street lighting or because of an installation deal that Edison made with an arc lighting company.\nTesla had been working at the Machine Works for a total of six months when he quit. What event precipitated his leaving is unclear. It may have been over a bonus he did not receive, either for redesigning generators or for the arc lighting system that was shelved. Tesla had previous run-ins with the Edison company over unpaid bonuses he believed he had earned. In his autobiography, Tesla stated the manager of the Edison Machine Works offered a $50,000 bonus to design "twenty-four different types of standard machines" "but it turned out to be a practical joke". Later versions of this story have Thomas Edison himself offering and then reneging on the deal, quipping: "Tesla, you don\'t understand our American humor". The size of the bonus in either story has been noted as odd, since Machine Works manager Batchelor was stingy with pay, and the company did not have that amount of cash (equal to $1,749,815 today) on hand. Tesla\'s diary contains just one comment on what happened at the end of his employment, a note he scrawled across the two pages covering 7 December 1884, to 4 January 1885, saying "Good By to the Edison Machine Works".\n\n\n== Tesla Electric Light and Manufacturing ==\nSoon after leaving the Edison company, Tesla was working on patenting an arc lighting system, possibly the same one he had developed at Edison. In March 1885, he met with patent attorney Lemuel W. Serrell, the same attorney used by Edison, to obtain help with submitting the patents. Serrell introduced Tesla to two businessmen, Robert Lane and Benjamin Vail, who agreed to finance an arc lighting manufacturing and utility company in Tesla\'s name, the Tesla Electric Light and Manufacturing Company. Tesla worked for the rest of the year obtaining the patents that included an improved DC generator, the first patents issued to Tesla in the US, and building and installing the system in Rahway, New Jersey. \nThe investors showed little interest in Tesla\'s ideas for new types of alternating current motors and electrical transmission equipment. After the utility was up and running in 1886, they decided that the manufacturing side of the business was too competitive and opted to simply run an electric utility. They formed a new utility company, abandoning Tesla\'s company and leaving the inventor penniless. Tesla even lost control of the patents he had generated, since he had assigned them to the company in exchange for stock. He had to work at various electrical repair jobs and as a ditch digger for $2 per day. Later in life, Tesla recounted that part of 1886 as a time of hardship, writing "My high education in various branches of science, mechanics and literature seemed to me like a mockery".\n\n\n== AC and the induction motor ==\n\nIn late 1886, Tesla met Alfred S. Brown, a Western Union superintendent, and New York attorney Charles Fletcher Peck. The two men were experienced in setting up companies and promoting inventions and patents for financial gain. Based on Tesla\'s new ideas for electrical equipment, including a thermo-magnetic motor idea, they agreed to back the inventor financially and handle his patents. Together they formed the Tesla Electric Company in April 1887, with an agreement that profits from generated patents would go 1⁄3 to Tesla, 1⁄3 to Peck and Brown, and 1⁄3 to fund development. They set up a laboratory for Tesla at 89 Liberty Street in Manhattan, where he worked on improving and developing new types of electric motors, generators, and other devices.\nIn 1887, Tesla developed an induction motor that ran on alternating current (AC), a power system format that was rapidly expanding in Europe and the United States because of its advantages in long-distance, high-voltage transmission. The motor used polyphase current, which generated a rotating magnetic field to turn the motor (a principle that Tesla claimed to have conceived in 1882). This innovative electric motor, patented in May 1888, was a simple self-starting design that did not need a commutator, thus avoiding sparking and the high maintenance of constantly servicing and replacing mechanical brushes.\nAlong with getting the motor patented, Peck and Brown arranged to get the motor publicized, starting with independent testing to verify it was a functional improvement, followed by press releases sent to technical publications for articles to run concurrently with the issue of the patent. Physicist William Arnold Anthony (who tested the motor) and Electrical World magazine editor Thomas Commerford Martin arranged for Tesla to demonstrate his AC motor on 16 May 1888 at the American Institute of Electrical Engineers. Engineers working for the Westinghouse Electric & Manufacturing Company reported to George Westinghouse that Tesla had a viable AC motor and related power system—something Westinghouse needed for the alternating current system he was already marketing. Westinghouse looked into getting a patent on a similar commutator-less, rotating magnetic field-based induction motor developed in 1885 and presented in a paper in March 1888 by Italian physicist Galileo Ferraris, but decided that Tesla\'s patent would probably control the market.\n\nIn July 1888, Brown and Peck negotiated a licensing deal with George Westinghouse for Tesla\'s polyphase induction motor and transformer designs for $60,000 in cash and stock and a royalty of $2.50 per AC horsepower produced by each motor. Westinghouse also hired Tesla for one year for the large fee of $2,000 ($70,000 in today\'s dollars) per month to be a consultant at the Westinghouse Electric & Manufacturing Company\'s Pittsburgh labs.\nDuring that year, Tesla worked in Pittsburgh, helping to create an alternating current system to power the city\'s streetcars. He found it a frustrating period because of conflicts with the other Westinghouse engineers over how best to implement AC power. Between them, they settled on a 60-cycle AC system that Tesla proposed (to match the working frequency of Tesla\'s motor), but they soon found that it would not work for streetcars, since Tesla\'s induction motor could run only at a constant speed. They ended up using a DC traction motor instead.\n\n\n=== Market turmoil ===\nTesla\'s demonstration of his induction motor and Westinghouse\'s subsequent licensing of the patent, both in 1888, came at the time of extreme competition between electric companies. The three big firms, Westinghouse, Edison, and Thomson-Houston Electric Company, were trying to grow in a capital-intensive business while financially undercutting each other. There was even a "war of currents" propaganda campaign going on, with Edison Electric claiming their direct current system was better and safer than the Westinghouse alternating current system and Thomson-Houston sometimes siding with Edison. Competing in this market meant Westinghouse would not have the cash or engineering resources to develop Tesla\'s motor and the related polyphase system right away.\nTwo years after signing the Tesla contract, Westinghouse Electric was in trouble. The near collapse of Barings Bank in London triggered the financial panic of 1890, causing investors to call in their loans to Westinghouse Electric. The sudden cash shortage forced the company to refinance its debts. The new lenders demanded that Westinghouse cut back on what looked like excessive spending on acquisition of other companies, research, and patents, including the per motor royalty in the Tesla contract. At that point, the Tesla induction motor had been unsuccessful and was stuck in development. Westinghouse was paying a $15,000-a-year guaranteed royalty even though operating examples of the motor were rare and polyphase power systems needed to run it were even rarer. \nIn early 1891, George Westinghouse explained his financial difficulties to Tesla in stark terms, saying that, if he did not meet the demands of his lenders, he would no longer be in control of Westinghouse Electric and Tesla would have to "deal with the bankers" to try to collect future royalties. The advantages of having Westinghouse continue to champion the motor probably seemed obvious to Tesla and he agreed to release the company from the royalty payment clause in the contract. Six years later Westinghouse purchased Tesla\'s patent for a lump sum payment of $216,000 as part of a patent-sharing agreement signed with General Electric (a company created from the 1892 merger of Edison and Thomson-Houston).\n\n\n== New York laboratories ==\n\nThe money Tesla made from licensing his AC patents made him independently wealthy and gave him the time and funds to pursue his own interests. In 1889, Tesla moved out of the Liberty Street shop Peck and Brown had rented and for the next dozen years worked out of a series of workshop/laboratory spaces in Manhattan. These included a lab at 175 Grand Street (1889–1892), the fourth floor of 33–35 South Fifth Avenue (1892–1895), and sixth and seventh floors of 46 & 48 East Houston Street (1895–1902). \n\n\n=== Tesla coil ===\n\nIn the summer of 1889, Tesla traveled to the 1889 Exposition Universelle in Paris and learned of Heinrich Hertz\'s 1886–1888 experiments that proved the existence of electromagnetic radiation, including radio waves. In repeating and then expanding on these experiments Tesla tried powering a Ruhmkorff coil with a high speed alternator he had been developing as part of an improved arc lighting system but found that the high-frequency current overheated the iron core and melted the insulation between the primary and secondary windings in the coil. To fix this problem Tesla came up with his "oscillating transformer", with an air gap instead of insulating material between the primary and secondary windings and an iron core that could be moved to different positions in or out of the coil. Later called the Tesla coil, it would be used to produce high-voltage, low-current, high frequency alternating-current electricity. He would use this resonant transformer circuit in his later wireless power work.\n\n\n=== W

In [208]:
text_splitter = NLTKTextSplitter(
    chunk_size = 300,
    chunk_overlap = 50
)


token_chunks = text_splitter.create_documents(
    [document_1],
    metadatas = [{"document" : query}]
)

WARNING:langchain_text_splitters.base:Created a chunk of size 315, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 316, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 334, which is longer than the specified 300

In [209]:
embedding_llm = GoogleGenerativeAIEmbeddings(
    google_api_key = gemini_api_key ,
    model = "models/text-embedding-004"
)

##Vector Stores | FAISS

In [210]:
from langchain_community.vectorstores import FAISS
vector_db = FAISS.from_documents(token_chunks , embedding_llm)

In [211]:
query_text = "In which year did Tesla's fathre die? "
similar_docs = vector_db.similarity_search(query_text)

In [212]:
similar_docs[0]

Document(id='ba7318c7-be8a-448f-a747-66e36027fa6a', metadata={'document': 'Nikola Tesla'}, page_content="Tesla's father died the next month, on 17 April 1879, at the age of 60 after an unspecified illness.\n\nIn January 1880, two of Tesla's uncles paid for him to leave Gospić for Prague, where he was to study.")

##Vector Stores | Chroma

In [213]:
from langchain_community.vectorstores import Chroma

# Store text documents as vector
save_to_dir = "/content/wiki_chroma_db"

docs_ids = list(range(len(token_chunks)))
docs_ids = [ str(d) for d in docs_ids]

vector_db = Chroma.from_documents(
    token_chunks ,
    embedding_llm ,
    persist_directory = save_to_dir,
    ids = docs_ids
)

In [214]:
# Search for most similarity document to a query

query_text = "In which year did Tesla's fathre die?"

similar_docs = vector_db.similarity_search(
    query_text ,
    k =5,
    filter = {'document':'Nikola Tesla'}
)

In [215]:
## Save to disk
vector_db.persist()

/tmp/ipython-input-3343235541.py:2: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  vector_db.persist()

In [216]:
## Load from disk
load_from_dir = '/content/wiki_chroma_db'

load_vector_db = Chroma(
    persist_directory = load_from_dir ,
    embedding_function = embedding_llm
)

/tmp/ipython-input-1971478383.py:4: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-chroma package and should be used instead. To use it run `pip install -U `langchain-chroma` and import as `from `langchain_chroma import Chroma``.
  load_vector_db = Chroma(

In [217]:
## Search for most similar document to a query
query_text = "In which year did Tesla's fathre die?"

similar_docs = load_vector_db.similarity_search(
    query_text ,
    k =5,
    filter = {'document' : 'Nikola Tesla'}
)

In [218]:
print( similar_docs[0] )

page_content='Tesla's father died the next month, on 17 April 1879, at the age of 60 after an unspecified illness.

In January 1880, two of Tesla's uncles paid for him to leave Gospić for Prague, where he was to study.' metadata={'document': 'Nikola Tesla'}

#Example Source Data (RAG test case)

In [219]:
from langchain_community.document_loaders import WikipediaLoader
from langchain_text_splitters import NLTKTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma
import nltk
nltk.download('punkt')

#load document
query = 'Nikola Tesla'
docs = WikipediaLoader(
    query = query,
    load_max_docs = 1,
    doc_content_chars_max =20_000
).load()

document = docs[0].page_content
metadatas = [{"document" : query}]

text_splitter = NLTKTextSplitter(chunk_size=300 ,
                                 chunk_overlap = 50
)

token_chunks = text_splitter.create_documents([document] ,
                                              metadatas = metadatas)

embedding_llm = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004",
                                              google_api_key = gemini_api_key)

save_to_dir = "/content/Wiki_chroma_db"
vector_db = Chroma.from_documents(
    token_chunks ,
    embedding_llm ,
    persist_directory = save_to_dir
)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
WARNING:langchain_text_splitters.base:Created a chunk of size 315, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 316, which is longer than the specified 300
WARNING:langchain_text_splitters.base:Created a chunk of size 334, which is longer than the specified 300

In [220]:
document

'Nikola Tesla (10 July 1856 – 7 January 1943) was a Serbian-American engineer, futurist, and inventor. He is known for his contributions to the design of the modern alternating current (AC) electricity supply system.\nBorn and raised in the Austrian Empire, Tesla first studied engineering and physics in the 1870s without receiving a degree. He then gained practical experience in the early 1880s working in telephony and at Continental Edison in the new electric power industry. In 1884, he migrated to the United States, where he became a naturalized citizen. He worked for a short time at the Edison Machine Works in New York City before he struck out on his own. With the help of partners to finance and market his ideas, Tesla set up laboratories and companies in New York to develop a range of electrical and mechanical devices. His AC induction motor and related polyphase AC patents, licensed by Westinghouse Electric in 1888, earned him a considerable amount of money and became the cornerstone of the polyphase system, which Westinghouse marketed.\nTesla conducted a range of experiments with mechanical oscillators/generators, electrical discharge tubes, and early X-ray imaging among other things, in an attempt to develop inventions he could patent and market. He built a wirelessly controlled boat, one of the first wirelessly controlled vehicles ever produced. Tesla became well known as an inventor and demonstrated his achievements to celebrities and wealthy patrons at his lab. He was noted for his showmanship at public lectures. Throughout the 1890s, Tesla pursued his ideas for wireless lighting and worldwide wireless electric power distribution in his high-voltage, high-frequency power experiments in New York and Colorado Springs. In 1893, he made pronouncements on the possibility of wireless communication with his devices. Tesla tried to put these ideas to practical use in his unfinished Wardenclyffe Tower project, an intercontinental wireless communication and power transmitter, but ran out of funding before he could complete it.\nAfter Wardenclyffe, Tesla experimented with a series of inventions in the 1910s and 1920s with varying degrees of success. Having spent most of his money, Tesla lived in a series of New York hotels, leaving behind unpaid bills. He died in New York City in January 1943. Tesla\'s work fell into relative obscurity following his death, until 1960, when the General Conference on Weights and Measures named the International System of Units (SI) measurement of magnetic flux density the tesla in his honor. There has been a resurgence in popular interest in Tesla since the 1990s. In 2013, Time named Tesla one of the 100 most significant figures of all time.\n\n\n== Early years ==\n\n\n=== Childhood ===\n\nNikola Tesla was born on 10 July 1856 in the village of Smiljan, in the Military Frontier of the Austrian Empire (present-day Croatia) into an ethnic Serb family. His father, Milutin Tesla (1819–1879), was a priest of the Eastern Orthodox Church. His father\'s brother Josif was a lecturer at a military academy who wrote several textbooks on mathematics.\nTesla\'s mother, Georgina "Đuka" Mandić (1822–1892), whose father was also an Eastern Orthodox priest, had a talent for making home craft tools and mechanical appliances and the ability to memorize Serbian epic poems. Đuka had never received a formal education. Tesla credited his eidetic memory and creative abilities to his mother\'s genetics and influence.\nTesla was the fourth of five children. In 1861, Tesla attended primary school in Smiljan where he studied German, arithmetic, and religion. In 1862, the Tesla family moved to the nearby town of Gospić, where Tesla\'s father worked as parish priest. Nikola completed primary school, followed by middle school. Later in his patent applications, before he obtained American citizenship, Tesla would identify himself as "of Smiljan, Lika, border country of Austria-Hungary".\n\n\n=== Education ===\n\nIn 1870, Tesla moved to Karlovac to attend high school at the Higher Real Gymnasium where the classes were held in German, as it was usual throughout schools within the Austro-Hungarian Military Frontier. Tesla later wrote that he became interested in his physics professor\'s demonstrations of electricity. The "mysterious phenomena" made him want "to know more of this wonderful force". He was able to perform integral calculus in his head, prompting his teachers to believe that he was cheating. He finished a four-year term in three years, graduating in 1873.\nAfter graduating Tesla returned to Smiljan but soon contracted cholera, was bedridden for nine months and was near death several times. In a moment of despair, Tesla\'s father (who had originally wanted him to enter the priesthood), promised to send him to the best engineering school if he recovered from the illness. Tesla later said that he had read Mark Twain\'s earlier works while recovering from his illness.\nThe next year Tesla evaded conscription into the Austro-Hungarian Army in Smiljan by running away southeast of Lika to Tomingaj, near Gračac. There he explored the mountains wearing hunter\'s garb. Tesla said that this contact with nature made him stronger, both physically and mentally. He enrolled at the Imperial-Royal Technical College in Graz in 1875 on a Military Frontier scholarship. Tesla passed nine exams (nearly twice as many as required) and received a letter of commendation from the dean of the technical faculty to his father, which stated, "Your son is a star of first rank." At Graz, Tesla was fascinated by the lectures on electricity presented by professor Jakob Pöschl. But by his third year he was failing in school and never graduated, leaving Graz in December 1878. One biographer suggests Tesla was not studying and may have been expelled for gambling and womanizing.\n\nTesla\'s family did not hear from him after he left school. There was a rumor among his classmates that he had drowned in the nearby river Mur but in January one of them ran into Tesla in the town of Maribor and reported that encounter to Tesla\'s family. It turned out Tesla had been working there as a draftsman for 60 florins per month. In March 1879, Milutin finally located his son and tried to convince him to return home and take up his education in Prague. Tesla returned to Gospić later that month when he was deported for not having a residence permit. Tesla\'s father died the next month, on 17 April 1879, at the age of 60 after an unspecified illness.\nIn January 1880, two of Tesla\'s uncles paid for him to leave Gospić for Prague, where he was to study. He arrived too late to enroll at Charles-Ferdinand University; he had never studied Greek, a required subject; and he was illiterate in Czech, another required subject. He attended lectures in philosophy at the university as an auditor, but he did not receive grades for the courses.\n\n\n=== Budapest Telephone Exchange ===\nTesla moved to Budapest, Hungary, in 1881 to work under Tivadar Puskás at a telegraph company, the Budapest Telephone Exchange. Upon arrival, Tesla realized that the company, then under construction, was not functional, so he worked as a draftsman in the Central Telegraph Office instead. Within a few months, the Budapest Telephone Exchange became functional, and Tesla was allocated the chief electrician position. Tesla later described how he made many improvements to the Central Station equipment including an improved telephone repeater or amplifier.\n\n\n== Working at Edison ==\nIn 1882, Tivadar Puskás got Tesla another job in Paris with the Continental Edison Company. Tesla began working in what was then a brand new industry, installing indoor incandescent lighting citywide in large scale electric power utility. The company had several subdivisions and Tesla worked at the Société Electrique Edison, the division in the Ivry-sur-Seine suburb of Paris, in charge of installing the lighting system. There he gained a great deal of practical experience in electrical engineering. Management took notice of his advanced knowledge in engineering and physics, and soon had him designing and building improved versions of generating dynamos and motors. \n\n\n=== Moving to the United States ===\n\nIn 1884, Edison manager Charles Batchelor, who had been overseeing the Paris installation, was brought back to the United States to manage the Edison Machine Works, a manufacturing division situated in New York City, and asked that Tesla be brought to the United States as well. In June 1884, Tesla emigrated and began working almost immediately at the Machine Works on Manhattan\'s Lower East Side, an overcrowded shop with a workforce of several hundred machinists, laborers, managing staff, and 20 "field engineers" struggling with the task of building the large electric utility in that city. As in Paris, Tesla was working on troubleshooting installations and improving generators. \nHistorian W. Bernard Carlson notes Tesla may have met company founder Thomas Edison only a couple of times. One of those times was noted in Tesla\'s autobiography where, after staying up all night repairing the damaged dynamos on the ocean liner SS Oregon, he ran into Batchelor and Edison, who made a quip about their "Parisian" being out all night. After Tesla told them he had been up all night fixing the Oregon, Edison commented to Batchelor that "this is a damned good man". One of the projects given to Tesla was to develop an arc lamp–based street lighting system. Arc lighting was the most popular type of street lighting but it required high voltages and was incompatible with the Edison low-voltage incandescent system, causing the company to lose contracts in some cities. Tesla\'s designs were never put into production, possibly because of technical improvements in incandescent street lighting or because of an installation deal that Edison made with an arc lighting company.\nTesla had been working at the Machine Works for a total of six months when he quit. What event precipitated his leaving is unclear. It may have been over a bonus he did not receive, either for redesigning generators or for the arc lighting system that was shelved. Tesla had previous run-ins with the Edison company over unpaid bonuses he believed he had earned. In his autobiography, Tesla stated the manager of the Edison Machine Works offered a $50,000 bonus to design "twenty-four different types of standard machines" "but it turned out to be a practical joke". Later versions of this story have Thomas Edison himself offering and then reneging on the deal, quipping: "Tesla, you don\'t understand our American humor". The size of the bonus in either story has been noted as odd, since Machine Works manager Batchelor was stingy with pay, and the company did not have that amount of cash (equal to $1,749,815 today) on hand. Tesla\'s diary contains just one comment on what happened at the end of his employment, a note he scrawled across the two pages covering 7 December 1884, to 4 January 1885, saying "Good By to the Edison Machine Works".\n\n\n== Tesla Electric Light and Manufacturing ==\nSoon after leaving the Edison company, Tesla was working on patenting an arc lighting system, possibly the same one he had developed at Edison. In March 1885, he met with patent attorney Lemuel W. Serrell, the same attorney used by Edison, to obtain help with submitting the patents. Serrell introduced Tesla to two businessmen, Robert Lane and Benjamin Vail, who agreed to finance an arc lighting manufacturing and utility company in Tesla\'s name, the Tesla Electric Light and Manufacturing Company. Tesla worked for the rest of the year obtaining the patents that included an improved DC generator, the first patents issued to Tesla in the US, and building and installing the system in Rahway, New Jersey. \nThe investors showed little interest in Tesla\'s ideas for new types of alternating current motors and electrical transmission equipment. After the utility was up and running in 1886, they decided that the manufacturing side of the business was too competitive and opted to simply run an electric utility. They formed a new utility company, abandoning Tesla\'s company and leaving the inventor penniless. Tesla even lost control of the patents he had generated, since he had assigned them to the company in exchange for stock. He had to work at various electrical repair jobs and as a ditch digger for $2 per day. Later in life, Tesla recounted that part of 1886 as a time of hardship, writing "My high education in various branches of science, mechanics and literature seemed to me like a mockery".\n\n\n== AC and the induction motor ==\n\nIn late 1886, Tesla met Alfred S. Brown, a Western Union superintendent, and New York attorney Charles Fletcher Peck. The two men were experienced in setting up companies and promoting inventions and patents for financial gain. Based on Tesla\'s new ideas for electrical equipment, including a thermo-magnetic motor idea, they agreed to back the inventor financially and handle his patents. Together they formed the Tesla Electric Company in April 1887, with an agreement that profits from generated patents would go 1⁄3 to Tesla, 1⁄3 to Peck and Brown, and 1⁄3 to fund development. They set up a laboratory for Tesla at 89 Liberty Street in Manhattan, where he worked on improving and developing new types of electric motors, generators, and other devices.\nIn 1887, Tesla developed an induction motor that ran on alternating current (AC), a power system format that was rapidly expanding in Europe and the United States because of its advantages in long-distance, high-voltage transmission. The motor used polyphase current, which generated a rotating magnetic field to turn the motor (a principle that Tesla claimed to have conceived in 1882). This innovative electric motor, patented in May 1888, was a simple self-starting design that did not need a commutator, thus avoiding sparking and the high maintenance of constantly servicing and replacing mechanical brushes.\nAlong with getting the motor patented, Peck and Brown arranged to get the motor publicized, starting with independent testing to verify it was a functional improvement, followed by press releases sent to technical publications for articles to run concurrently with the issue of the patent. Physicist William Arnold Anthony (who tested the motor) and Electrical World magazine editor Thomas Commerford Martin arranged for Tesla to demonstrate his AC motor on 16 May 1888 at the American Institute of Electrical Engineers. Engineers working for the Westinghouse Electric & Manufacturing Company reported to George Westinghouse that Tesla had a viable AC motor and related power system—something Westinghouse needed for the alternating current system he was already marketing. Westinghouse looked into getting a patent on a similar commutator-less, rotating magnetic field-based induction motor developed in 1885 and presented in a paper in March 1888 by Italian physicist Galileo Ferraris, but decided that Tesla\'s patent would probably control the market.\n\nIn July 1888, Brown and Peck negotiated a licensing deal with George Westinghouse for Tesla\'s polyphase induction motor and transformer designs for $60,000 in cash and stock and a royalty of $2.50 per AC horsepower produced by each motor. Westinghouse also hired Tesla for one year for the large fee of $2,000 ($70,000 in today\'s dollars) per month to be a consultant at the Westinghouse Electric & Manufacturing Company\'s Pittsburgh labs.\nDuring that year, Tesla worked in Pittsburgh, helping to create an alternating current system to power the city\'s streetcars. He found it a frustrating period because of conflicts with the other Westinghouse engineers over how best to implement AC power. Between them, they settled on a 60-cycle AC system that Tesla proposed (to match the working frequency of Tesla\'s motor), but they soon found that it would not work for streetcars, since Tesla\'s induction motor could run only at a constant speed. They ended up using a DC traction motor instead.\n\n\n=== Market turmoil ===\nTesla\'s demonstration of his induction motor and Westinghouse\'s subsequent licensing of the patent, both in 1888, came at the time of extreme competition between electric companies. The three big firms, Westinghouse, Edison, and Thomson-Houston Electric Company, were trying to grow in a capital-intensive business while financially undercutting each other. There was even a "war of currents" propaganda campaign going on, with Edison Electric claiming their direct current system was better and safer than the Westinghouse alternating current system and Thomson-Houston sometimes siding with Edison. Competing in this market meant Westinghouse would not have the cash or engineering resources to develop Tesla\'s motor and the related polyphase system right away.\nTwo years after signing the Tesla contract, Westinghouse Electric was in trouble. The near collapse of Barings Bank in London triggered the financial panic of 1890, causing investors to call in their loans to Westinghouse Electric. The sudden cash shortage forced the company to refinance its debts. The new lenders demanded that Westinghouse cut back on what looked like excessive spending on acquisition of other companies, research, and patents, including the per motor royalty in the Tesla contract. At that point, the Tesla induction motor had been unsuccessful and was stuck in development. Westinghouse was paying a $15,000-a-year guaranteed royalty even though operating examples of the motor were rare and polyphase power systems needed to run it were even rarer. \nIn early 1891, George Westinghouse explained his financial difficulties to Tesla in stark terms, saying that, if he did not meet the demands of his lenders, he would no longer be in control of Westinghouse Electric and Tesla would have to "deal with the bankers" to try to collect future royalties. The advantages of having Westinghouse continue to champion the motor probably seemed obvious to Tesla and he agreed to release the company from the royalty payment clause in the contract. Six years later Westinghouse purchased Tesla\'s patent for a lump sum payment of $216,000 as part of a patent-sharing agreement signed with General Electric (a company created from the 1892 merger of Edison and Thomson-Houston).\n\n\n== New York laboratories ==\n\nThe money Tesla made from licensing his AC patents made him independently wealthy and gave him the time and funds to pursue his own interests. In 1889, Tesla moved out of the Liberty Street shop Peck and Brown had rented and for the next dozen years worked out of a series of workshop/laboratory spaces in Manhattan. These included a lab at 175 Grand Street (1889–1892), the fourth floor of 33–35 South Fifth Avenue (1892–1895), and sixth and seventh floors of 46 & 48 East Houston Street (1895–1902). \n\n\n=== Tesla coil ===\n\nIn the summer of 1889, Tesla traveled to the 1889 Exposition Universelle in Paris and learned of Heinrich Hertz\'s 1886–1888 experiments that proved the existence of electromagnetic radiation, including radio waves. In repeating and then expanding on these experiments Tesla tried powering a Ruhmkorff coil with a high speed alternator he had been developing as part of an improved arc lighting system but found that the high-frequency current overheated the iron core and melted the insulation between the primary and secondary windings in the coil. To fix this problem Tesla came up with his "oscillating transformer", with an air gap instead of insulating material between the primary and secondary windings and an iron core that could be moved to different positions in or out of the coil. Later called the Tesla coil, it would be used to produce high-voltage, low-current, high frequency alternating-current electricity. He would use this resonant transformer circuit in his later wireless power work.\n\n\n=== W

#12. QnA Chain

In [221]:
from langchain_core.prompts import PromptTemplate
from langchain_core.prompts import ChatPromptTemplate

In [222]:
prompt = PromptTemplate(
    input_variables = ["context" ,"question"],
    template = """
    Use the following context to answer the question.
    if the answer is not contained in the context, say "No Answer is Available"

    Context:
    {context}

    Question:
    {question}

    Answer
    """
)

In [223]:
question = "when was Nicola Tesla born?"

similar_docs = vector_db.similarity_search(question , k = 3)

In [224]:
def stuff_chain(docs , question):
  context = "\n\n".join(doc.page_content for doc in docs)
  return chat.invoke(prompt.format(context = context , question = question))

In [225]:
answer = stuff_chain(similar_docs, question)
print(answer.text.strip())

10 July 1856

In [226]:
question="what is the favourite food for Nicola Tesla"
answer = stuff_chain(similar_docs, question)
print(answer.text.strip())

No Answer is Available

## 12.2 MapReduce chain (LCEL 2025)

In [227]:
map_prompt = PromptTemplate(
    input_variables =['document'],
    template = """
    You are given a document chunk. summarize the core meaning consisely.

    Document:
    {document}

    Summary:
    """
)

reduce_prompt = PromptTemplate(
    input_variables=["summaries","question"],
    template="""
    You are given multiple summaries. use them to answer the question
    if the answer is not contained in the summaries, say "No Answer is Available"
    Summaries:
   {summaries}

   Question:
   {question}

   Answer:
    """
)

In [228]:
def map_reduce_chain(docs, question):
  summaries = []
  for doc in docs:
    summaries.append(chat.invoke(map_prompt.format(document=doc.page_content)).text.strip())
  return chat.invoke(reduce_prompt.format(summaries = summaries , question = question)).text.strip()

In [229]:
question = "what did Tesla invent?"

similar_docs = vector_db.similarity_search(question, k=3)

In [230]:
answer = map_reduce_chain(similar_docs, question)
print(answer)

Tesla invented an AC induction motor in 1887. He also experimented with wirelessly controlled vehicles, oscillators, and X-ray imaging.

## 12.3 Refine chain (LCEL 2025)

---

In [231]:
initial_prompt = PromptTemplate(
    input_variables = ["document", "question"],
    template="""
    Answer the following question using the provided document,

    Document:
    {document}

    Question:
    {question}

    Answer:
    """
)

refine_prompt = PromptTemplate(
    input_variables = ["existing_answer", "document", "question"],
    template="""
    We have an exsiting answer:
    {existing_answer}

    Here is new information from another document:
    {document}

    Question:
    {question}

    Refine the existing answer to include this ew information
    If the new document does not add anything, keep the answer unchanged

    Refined Answer:
    """
)

In [232]:
def refine_chain(docs, question):
  # initial step (given best match doc)
  answer = chat.invoke(initial_prompt.format(document=docs[0].page_content, question=question)).text.strip()
  # refine step (given rest of docs)
  for doc in docs[1:]:
    answer =  chat.invoke(refine_prompt.format(existing_answer=answer,
                                                        document=doc.page_content,
                                                        question=question)).text.strip()
  return answer

In [233]:
question = "what did Tesla invent?"

similar_docs = vector_db.similarity_search(question, k=2)

In [234]:
answer = refine_chain(similar_docs, question)
print(answer)

Tesla invented a wirelessly controlled boat, and conducted experiments with mechanical oscillators/generators, electrical discharge tubes, and early X-ray imaging in an attempt to develop inventions he could patent and market.